<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script type="text/javascript" charset="utf8" src="assets/js/datatables/datatables.js"></script>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".reporte").addClass("active");

    $(document).ready(function () {

        $(".btnGenerarReporte").click(function () {
            if ($("form[name='formreporte']").valid()) {

                $.ajax({
                    url: 'assets/reporteventa/reporteventa_controller.php',
                    type: 'POST',
                    data: {
                        tipoReporte: $("#selectReporte").val(),
                        fechaInicio: $("#fechaInicioreporte").val(),
                        fechaFin: $("#fechaFinreporte").val(),
                    },
                    success: function (reporte) {

                        if ($("#selectReporte").val() == "reporteProductos") {
                            $(".tituloReporte").html("Reporte de productos vendidos (Del <b style='color:red;'>" + convertDate($("#fechaInicioreporte").val()) + "</b> al <b style='color:red;'>" + convertDate($("#fechaFinreporte").val()) + "</b>) ");
                        }

                        $(".contenedorReporte").html(reporte);

                        $('.contenedorReporte .table').DataTable({
                            "pageLength": 5,
                            "bLengthChange": false,
                            "language": {
                                "search": "BUSCAR:"
                            }
                        });

                        $(".opcionesReporte").show();



                    },
                    error: function (error) {
                        console.log('Disculpe, existió un problema');
                        console.log(error);
                    },
                    complete: function (xhr, status) {
                        console.log('Petición realizada');
                    }
                });

            }
        });

    });

    function convertDate(inputFormat) {
        function pad(s) {
            return (s < 10) ? '0' + s : s;
        }
        var d = new Date(inputFormat);
        return [pad(d.getDate() + 1), pad(d.getMonth() + 1), d.getFullYear()].join('/');
    }

    $(document).ready(function () {

        $("form[name='formreporte']").validate({
            rules: {
                selectReporte: {
                    required: true,
                },
                fechaInicioreporte: {
                    required: true,
                },
                fechaFinreporte: {
                    required: true,
                }
            },
            messages: {
                selectReporte: {
                    required: "Seleccione un tipo de reporte."
                },
                fechaInicioreporte: {
                    required: "Establezca una fecha de inicio.",
                },
                fechaFinreporte: {
                    required: "Establezca una fecha fin.",
                }
            }
        });

    });
</script>