<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li>Reportes </li>
</ul>
<!-- FIN BREADCRUMB -->

<div class="page-title">                    
    <h2><span class="fa fa-list-alt"></span> Reportes</h2>
</div>

<div class="row">
    <div class="col-md-12">
        <form name="formreporte">
            <div class="col-md-12">
                <h4>Establesca el tipo de reporte, la fecha inicial y final para generar un reporte.</h4>
                <br>
            </div>
            <div class="col-md-3" >
                <div class="form-group">
                    <div class="form_error"></div>
                    <div class="form_label"><label for="selectReporte">Tipo de reporte : </label></div>
                    <div class="form_input">
                        <select class="form-control" id="selectReporte" name="selectReporte">
                            <option value="">Seleccione .. </option>
                            <option value="reporteProductos">Reporte de productos vendidos</option>
                            <option value="reporteIngredientes">Reporte de ingredientes vendidos</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-3" >
                <div class="form-group">
                    <div class="form_error"></div>
                    <div class="form_label"><label for="fechaInicioreporte">Fecha inicio:</label></div>
                    <div class="form_input"><input type="date" id="fechaInicioreporte" name="fechaInicioreporte" class="form-control" required></div>
                </div>
            </div>
            <div class="col-md-3" >
                <div class="form-group">
                    <div class="form_error"></div>
                    <div class="form_label"><label for="fechaFinreporte">Fecha fin:</label></div>
                    <div class="form_input"><input type="date" id="fechaFinreporte" name="fechaFinreporte" class="form-control" required></div>
                </div>
            </div>
        </form>
        <div class="col-md-3" >
            <div class="form-group">
                <div class="form_error"></div>
                <div class="form_label"><label><br></label></div>
                <div class="form_input"><button type="button" class="btn btn-block btn-primary btnGenerarReporte">Generar reporte</button></div>
            </div>
        </div>
    </div>

    <div class="col-md-12" style="background-color: #eeeded;">
        <div class="col-md-12">
            <br><br>
            <center><h3 class="tituloReporte"></h3></center>
        </div>
        <div class="col-md-6 contenedorReporte">
        </div>
        <div class="col-md-6 opcionesReporte" hidden>
            <br><br><br><br>
            <div class="col-md-6">                        
                <a href="#" class="tile tile-primary tile-valign"><span class="fa fa-print"></span><br><h5 style="color:white;">Imprimir</h5></a>                        
            </div>
        </div>
    </div>
</div>