<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */

//              CONSTANTES DEL SISTEMA
define('__APPNAME__', 'DROOM');
define('__APPDESC__', 'Sistema inteligente de control de Restaurantes');
define('__AUTHORNAME__', 'Burton Technology');
define('__AUTHORURL__', 'https://burtonservers.com');

// VALIDAMOS SI EL USUARIO ESTA LOGUEADO //
session_start();
if (isset($_SESSION["usuario"])) {
    // VALIDAMOS SI TIENE PANEL ASIGNADO //
    if (isset($_GET['show'])) {
        $module = $_GET['show'];
        $page = 'app';
    } else {
        session_destroy();
        $page = 'login';
    }
} else {
    session_destroy();
    $page = 'login';
}

//          CONFIGURAMOS LA UI
$sb = $_SESSION["usuario"]['sidebar'];
$fw = $_SESSION["usuario"]['fullwidth'];

if ($sb == '1') {
    $sidebar = "page-navigation-toggled";
    $checkedsb = 'checked';
} else {
    $sidebar = "";
    $checkedsb = '';
}

if ($fw == '1') {
    $fullwidth = "";
    $checkedfw = 'checked';
} else {
    $fullwidth = "page-container-boxed";
    $checkedfw = '';
}

//                  RANDOM VIDEO BACKGROUND
$r = rand(1, 7);
switch ($r) {
    case 1:$video = "FaHTfgV7ii4";break;
    case 2:$video = "95SNbn340TE";break;
    case 3:$video = "5LE8mg8Khbo";break;
    case 4:$video = "p2bCtDXwQQI";break;
    case 5:$video = "0I4bUOYK3rA";break;
    case 6:$video = "FIubfE2JkDE";break; 
    case 8:$video = "96v_ZcPtE44";break; 
}
$videoTag = '       <div class="video-background">' .
        '            <div class="video-foreground">' .
        '                <iframe src="https://www.youtube.com/embed/' . $video . '?controls=0&showinfo=0&rel=0&mute=1&modestbranding=1&autoplay=1&loop=1&playlist=' . $video . '" frameborder="0" allowfullscreen></iframe>' .
        '            </div>' .
        '            <div class="video-overlay">' .
        '            </div>' .
        '       </div>';
?>