<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- MENSAJE DE SALIDA-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fas fa-sign-out-alt"></span> Salir de la <strong>App</strong> ?</div>
            <div class="mb-content">
                <p>¿Est&aacute; seguro que desea salir?</p>                    
                <p>Presione No para continuar trabajando. Presione Si para salir.</p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <a href="#" class="btn btn-info btn-lg btnSalir">Si</a>
                    <button class="btn btn-default btn-lg mb-control-close">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="notificacion" hidden></div>
<!-- FIN MENSAJE DE SALIDA-->
<script type="text/javascript" src="assets/js/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap.min.js"></script>    
<script type="text/javascript" src="assets/js/plugins/tour/intro.min.js"></script>  
<script type="text/javascript" src="assets/js/supersized.3.2.7.min.js"></script>
<script type="text/javascript" src="assets/js/supersized-init.js"></script>
<script type="text/javascript" src="assets/js/plugins/notify/notify.js"></script>
<script type='text/javascript' src='assets/js/plugins/icheck/icheck.min.js'></script>        
<script type="text/javascript" src="assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="assets/js/plugins/morris/morris.min.js"></script>       
<script type="text/javascript" src="assets/js/plugins/rickshaw/d3.v3.js"></script>
<script type="text/javascript" src="assets/js/plugins/rickshaw/rickshaw.min.js"></script>
<script type='text/javascript' src='assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'></script>
<script type='text/javascript' src='assets/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'></script>                
<script type='text/javascript' src='assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>                
<script type="text/javascript" src="assets/js/plugins/owl/owl.carousel.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/moment.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="assets/js/plugins/dropzone/dropzone.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="assets/js/plugins/form/jquery.form.js"></script>
<script type="text/javascript" src="assets/js/plugins/cropper/cropper.min.js"></script>
<script type='text/javascript' src='assets/js/plugins/jquery-validation/jquery.validate.js'></script>
<script type="text/javascript" src="assets/js/plugins/smartwizard/jquery.smartWizard-2.0.min.js"></script>     
<script type="text/javascript" src="assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/tableExport.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jquery.base64.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/html2canvas.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/libs/sprintf.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/jspdf.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/libs/base64.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-timepicker.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-select.js"></script>
<script type="text/javascript" src="assets/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="assets/js/plugins.js"></script>        
<script type="text/javascript" src="assets/js/actions.js"></script>
<script type="text/javascript" src="assets/js/demo_edit_profile.js"></script>
<script type='text/javascript' src='assets/js/plugins/noty/jquery.noty.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topCenter.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topLeft.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topRight.js'></script> 
<script type='text/javascript' src='assets/node_modules/dragula/dist/dragula.min.js'></script>
<script type='text/javascript' src='assets/node_modules/easy-autocomplete/dist/jquery.easy-autocomplete.min.js'></script>
<script type='text/javascript' src='assets/js/plugins/filestyle/bootstrap-filestyle.min.js'></script>
<script type="text/javascript" src="assets/js/plugins/fileinput/fileinput.min.js"></script> 
<script type='text/javascript' src='assets/js/modalMultiple.js'></script>
<script type='text/javascript' src='assets/salir/script_salir.js'></script>
<script type="text/javascript" src="//cdn.rawgit.com/icons8/bower-webicon/v0.10.7/jquery-webicon.min.js"></script>
<script src='assets/js/velocity.min.js'></script>
<script src='assets/js/velocity.ui.min.js'></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.js"></script>
<script>
    var listhas = 0;
    $(document).ready(function () {
        $('#loginForm').submit(function (e) {
            e.preventDefault();
            var username = $(this).find('.email').val();
            var password = $(this).find('.password').val();

            if (username == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '27px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.email').focus();
                });

                return false;
            }
            if (password == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '96px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.password').focus();
                });
                return false;
            }

            /// VALIDAMOS QUE NO EXISTAN CAMPOS VACIOS ///
            if (username != '' && password != '') {

                var formData = new FormData();
                formData.append('email', username);
                formData.append('password', password);
                formData.append('meth', 'login');
                $.ajax({
                    url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                    success: function (data) {
                        if (data.scriptResp == "noMatch") {
                            $(".customalert_text").html("No pudimos validar sus datos, intente nuevamente");
                            $(".customalert").velocity("transition.slideRightBigIn", 500);
                            $('.password').val('');
                            //console.log(data);
                        }
                        if (data.scriptResp == "match") {
                            if (data.userIntel.statusUsuario == '0') {
                                $(".customalert_text").html("Su usuario se encunetra suspendido, contacte a su asesor de cuenta");
                                $(".customalert").velocity("transition.slideRightBigIn", 500);
                                return;
                            }
                            if (data.userIntel.statusUsuario == '1') {
                                if (data.userIntel.idPerfil == '8') {
                                    window.location.href = "/?show=newUser";
                                } else {
                                    window.location.href = "/?show=home";
                                    return;
                                }
                            }
                        }
                    },
                    error: function (error) {
                        console.log("Hubo un error de internet, intente de nuevo");
                        console.log(error);
                    }
                });
            }
        });

        $('#registerForm').submit(function (e) {
            e.preventDefault();
            var name = $(this).find('.names').val();
            var phone = $(this).find('.phone').val();
            var email = $(this).find('.email').val();
            var regpassword = $(this).find('.regpassword').val();
            var repassword = $(this).find('.repassword').val();

            /// VALIDADORES ///
            if (name == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '27px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.names').focus();
                });

                return false;
            }
            if (phone == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '96px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.phone').focus();
                });

                return false;
            }
            if (email == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '165px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.email').focus();
                });

                return false;
            }
            if (regpassword == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '234px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.regpassword').focus();
                });

                return false;
            }
            if (repassword == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '303px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.repassword').focus();
                });
                return false;
            }
            if (regpassword.length < 7) {
                $(".customalert_text").html("La contraseña debe tener un m&iacute;nimo de 8 caracteres");
                $(".customalert").velocity("transition.slideRightBigIn", 500);
                return false;
            }
            if (regpassword != repassword) {
                $(".customalert_text").html("Las contraseñas no coinciden");
                $(".customalert").velocity("transition.slideRightBigIn", 500);
                return false;
            }

            var formData = new FormData();
            formData.append('names', name);
            formData.append('phone', phone);
            formData.append('email', email);
            formData.append('password', regpassword);
            formData.append('meth', 'register');
            $.ajax({
                url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                success: function (data) {

                    if (data.scriptResp == "emailExists") {
                        $(".customalert_text").html("Esta cuenta de correo ya se encuentra registrada");
                        $(".customalert").velocity("transition.slideRightBigIn", 500);
                    }
                    if (data.scriptResp == "regTrue") {
                        window.location.href = "/?show=newUser";
                    }
                },
                error: function (error) {
                    console.log("Hubo un error de internet, intente de nuevo");
                    console.log(error);
                }
            });
        });

        $('#loginForm .password, #loginForm .username').keyup(function () {
            $(this).parent().find('.error').fadeOut('fast');
        });

        $(document).find("div.page-container.login .overlayLogin").delay(500).velocity("transition.slideDownBigIn", 500);
        showLogin();

        $(document).on("click", "#registerBoxBtn", function () {
            showReg();
        });

        $(document).on("click", "#loginBoxBtn", function () {
            showLogin();
        });

    });

    //                  CERRAMOS LA VENTNA DE NOTIFICACION CON CLIC EN CUALQUIER PARTE DE LA PANTALLA
    $(document).on("click", function () {
        if ($(".customalert").is(':visible')) {
            $(".customalert").velocity("transition.slideRightBigOut", 500);
        }
        if ($("#mb-signout").is(':visible')) {
            $("#mb-signout").removeClass("open");
        }
    });

    $('.numonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9-]/g, ''));
    });

    $('.alphanumonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9a-zA-Z-]/g, ''));
    });

    $('.alphaonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^a-zA-Z\-\s]/g, ''));
    });

    $("li.menuItem").hover(function () {
        if ($(this).hasClass("xn-openable")) {
            $("li.xn-openable").removeClass("active");
            $(this).addClass("active");
        } else {
            $("li.xn-openable").removeClass("active");
        }
    }, function () {
        var self = this;
        return true;
    });

    /*
     *          *************************************************************************
     *          *******************||  FUNCIONES PUBLICAS DE LA APP   ||*****************
     *          *************************************************************************
     */

    //              DESPLEGAMOS LAS CARACTERISTICAS DEL PRODUCTO SELECCIONADO           //
    function displayProduct(idProduct, container) {
        var formData = new FormData();
        formData.append('id', idProduct);
        formData.append('meth', 'loadProdutSpecs');
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                console.log(data);
                var htmlforlist = '';
                var htmlcontent = '<div class="col-md-4 showProductPanelContainer hidethis">' +
                        '           <div class="panel panel-default showProductPanel">' +
                        '             <div class="panel-body profile itemMenuBg">' +
                        '                   <div class="profile-image">' +
                        '                       <img src="api/assets/img/productos/' + data.producto.idProducto + '.jpg"/>' +
                        '                   </div>' +
                        '                   <div class="profile-data">' +
                        '                       <div class="profile-data-name">' + data.producto.nombreProducto + '</div>' +
                        '                       <div class="profile-data-title" style="color: #FFF;">' + data.producto.nombreMenu + '</div>' +
                        '                   </div>' +
                        '               </div>' +
                        '               <div class="panel-body redbg">' +
                        '                   <div class="row">' +
                        '                       <ul class="list-tags thisProdIngs">';
                $.each(data.ings, function (ii, nn) {
                    htmlcontent += '<li><a><i class="fas fa-pepper-hot"></i> ' + nn.nombreIngrediente + '</a></li>';
                    htmlforlist += '<span class="label label-danger push5">+ ' + nn.nombreIngrediente + '</span> \n\ ';
                });
                htmlcontent += '        </ul>' +
                        '                   <ul class="list-tags">' +
                        '                       <li class="pull-right editCurrentIngs"><span class="hidethis editIngIdProd">' + data.producto.idProducto + '</span><button class="btn btn-info"><i class="fas fa-pencil-alt"></i> Modificar</button></li>' +
                        '                   </ul>' +
                        '               </div>' +
                        '           </div>' +
                        '           <div class="panel-body list-group border-bottom">   ' +
                        '               <a  class="list-group-item active"> ' + data.producto.descProducto + '</a>' +
                        '               <a  class="list-group-item  fontx1-5"><span class="fas fa-money-bill-wave"></span> <span class="pull-right currentViewShowPrice"> ' + data.producto.precioProducto + ' $</span></a>' +
                        '           </div>' +
                        '           <div class="panel-body">' +
                        '               <div class="form-group">' +
                        '                   <select class="form-control select" data-style="btn-primary" id="tamProdsSelect">';
                var tamsArray = JSON.parse(data.producto.tamProducto);
                $.each(tamsArray, function (tami, tamv) {
                    htmlcontent += '<option value="' + (+data.producto.precioProducto + +tamv) + '">' + tami + ' ( $' + (+data.producto.precioProducto + +tamv) + ')</option>';
                });
                htmlcontent += '            </select>' +
                        '               </div>' +
                        '           </div>' +
                        '           <div class="panel-body"> ' +
                        '               <div class="form-group">   ' +
                        '                   <select class="form-control select" data-style="btn-info"  id="varsProdsSelect">';
                var vars = data.producto.varsProducto.split(',');
                $.each(vars, function (ii, nn) {
                    htmlcontent += '<option>' + nn + '</option>';
                });
                if (listhas == 1) {
                    var textListhas = '';
                } else {
                    var textListhas = ' hidethis ';
                }
                htmlcontent += '</select>' +
                        '            </div>   ' +
                        '        </div>' +
                        '        <div class="panel-body">    ' +
                        '            <div class="col-md-12">' +
                        '                <h4 class="pull-left">Comentarios:</h4>' +
                        '                <textarea type="text" class="form-control" rows="3" placeholder="Ingresa el texto" id="comentProdCurrent"></textarea>   ' +
                        '            </div>  ' +
                        '        </div>' +
                        '        <div class="panel-body">    ' +
                        '            <div class="col-md-12">' +
                        '                <h4 class="pull-left">Cantidad:</h4>' +
                        '                <input id="cantProdCurrent" type="number" class="form-control" value="1" />   ' +
                        '            </div>  ' +
                        '        </div>' +
                        '        <div class="hidethis idProdCurrentView">' + data.producto.idProducto + '</div>' +
                        '        <div class="hidethis nombProdCurrentView">' + data.producto.nombreProducto + '</div>' +
                        '        <div class="hidethis ingsProductoCurrentView">' + data.producto.ingsProducto + '</div>' +
                        '        <div class="hidethis ingNamesProductoCurrentView">' + htmlforlist + '</div>' +
                        '        <div class="hidethis idMenuProductoCurrentView">' + data.producto.idMenu + '</div>' +
                        '        <div class="hidethis precProdCurrentView">' + data.producto.precioProducto + '</div>' +
                        '        <div class="panel-body">   ' +
                        '            <button class="btn btn-success addThisToList"><i class="fas fa-plus"></i> AGREGAR</button>' +
                        '            <button class="btn btn-info ShowThisList pull-right ' + textListhas + '"><i class="fas fa-list"></i> Lista</button>' +
                        '        </div>' +
                        '    </div>   ' +
                        '</div>';
                $.when(
                        $(document).find(".showProductPanelContainer,.listPanelCont").velocity("transition.slideUpBigOut", 400)
                        ).then(function () {
                    $(".showProductPanelContainer").remove();
                    $(container).append(htmlcontent);
                    $(document).find(".showProductPanelContainer").delay(500).velocity("transition.slideUpBigIn", 400);
                    $('select').selectpicker('refresh');
                });
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //                         ANIMAMOS LA VENTANA DE LOGIN PAR AAPARECER
    function showLogin() {

        $(document).find("div.page-container.login .registerBox").velocity("transition.slideRightBigOut", 500);
        setTimeout(function () {
            $(document).find("div.page-container.login > div.login-center.registerBox > form > button ,div.page-container.login .registerBox .ctaDiv").css('transition', '');
            $(document).find("div.page-container.login > div.login-center.registerBox > form > button").css('transform', '');
            $(document).find("div.page-container.login .registerBox .ctaDiv").velocity("transition.slideRightBigOut", 50);

            $(document).find("div.page-container.login .loginBox").velocity("transition.slideRightBigIn", 500);
            $(document).find("div.page-container.login .loginBox .ctaDiv").delay(500).velocity("transition.slideRightBigIn", {stagger: 400});
            setTimeout(function () {
                $(document).find("div.page-container.login .loginBox .ctaDiv").css('transition', 'transform 1s');
                $(document).find("div.page-container.login > div.login-center.loginBox > form > button").css('transform', 'translateX(60px)');
                setTimeout(function () {
                    $(document).find("div.page-container.login .loginBox .ctaDiv1").css('transform', 'translateX(30px)');
                    setTimeout(function () {
                        $(document).find("div.page-container.login .loginBox .ctaDiv2").css('transform', 'translateX(30px)');
                        setTimeout(function () {
                            $(document).find("div.page-container.login .loginBox .ctaDiv3").css('transform', 'translateX(40px)');
                        }, 200);
                    }, 200);
                }, 200);
            }, 2000);
        }, 500);
    }

    //                         ANIMAMOS LA VENTANA DE REGISTRO PAR AAPARECER
    function showReg() {

        $(document).find("div.page-container.login .loginBox").velocity("transition.slideRightBigOut", 500);
        setTimeout(function () {
            $(document).find("div.page-container.login > div.login-center.loginBox > form > button ,div.page-container.login .loginBox .ctaDiv").css('transition', '');
            $(document).find("div.page-container.login > div.login-center.loginBox > form > button").css('transform', '');
            $(document).find("div.page-container.login .loginBox .ctaDiv").velocity("transition.slideRightBigOut", 50);

            $(document).find("div.page-container.login .registerBox").velocity("transition.slideRightBigIn", 500);
            $(document).find("div.page-container.login .registerBox .ctaDiv").delay(500).velocity("transition.slideRightBigIn", {stagger: 400});
            setTimeout(function () {
                $(document).find("div.page-container.login .registerBox .ctaDiv").css('transition', 'transform 1s');
                $(document).find("div.page-container.login > div.login-center.registerBox > form > button").css('transform', 'translateX(60px)');
                setTimeout(function () {
                    $(document).find("div.page-container.login .registerBox .ctaDiv1").css('transform', 'translateX(45px)');
                    setTimeout(function () {
                        $(document).find("div.page-container.login .registerBox .ctaDiv2").css('transform', 'translateX(30px)');
                        setTimeout(function () {
                            $(document).find("div.page-container.login .registerBox .ctaDiv3").css('transform', 'translateX(40px)');
                        }, 200);
                    }, 200);
                }, 200);
            }, 2000);
        }, 500);
    }
</script>
<?php
require ("modules/" . $module . "/scripts.php");
?>
