<?php

/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script type="text/javascript" src="assets/js/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap.min.js"></script>  
<script type="text/javascript" src="assets/js/supersized.3.2.7.min.js"></script>
<script type="text/javascript" src="assets/js/supersized-init.js"></script>
<script type="text/javascript" src="assets/js/plugins/notify/notify.js"></script>
<script type='text/javascript' src='assets/js/plugins/icheck/icheck.min.js'></script>        
<script type="text/javascript" src="assets/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="assets/js/plugins/morris/morris.min.js"></script>       
<script type="text/javascript" src="assets/js/plugins/rickshaw/d3.v3.js"></script>
<script type="text/javascript" src="assets/js/plugins/rickshaw/rickshaw.min.js"></script>
<script type='text/javascript' src='assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'></script>
<script type='text/javascript' src='assets/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'></script>                
<script type='text/javascript' src='assets/js/plugins/bootstrap/bootstrap-datepicker.js'></script>                
<script type="text/javascript" src="assets/js/plugins/owl/owl.carousel.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/moment.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="assets/js/plugins/dropzone/dropzone.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="assets/js/plugins/form/jquery.form.js"></script>
<script type="text/javascript" src="assets/js/plugins/cropper/cropper.min.js"></script>
<script type='text/javascript' src='assets/js/plugins/jquery-validation/jquery.validate.js'></script>
<script type="text/javascript" src="assets/js/plugins/smartwizard/jquery.smartWizard-2.0.min.js"></script>     
<script type="text/javascript" src="assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/tableExport.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jquery.base64.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/html2canvas.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/libs/sprintf.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/jspdf.js"></script>
<script type="text/javascript" src="assets/js/plugins/tableexport/jspdf/libs/base64.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-timepicker.min.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="assets/js/plugins/bootstrap/bootstrap-select.js"></script>
<script type="text/javascript" src="assets/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="assets/js/plugins.js"></script>        
<script type="text/javascript" src="assets/js/actions.js"></script>
<script type="text/javascript" src="assets/js/demo_edit_profile.js"></script>
<script type='text/javascript' src='assets/js/plugins/noty/jquery.noty.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topCenter.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topLeft.js'></script>
<script type='text/javascript' src='assets/js/plugins/noty/layouts/topRight.js'></script> 
<script type='text/javascript' src='assets/node_modules/dragula/dist/dragula.min.js'></script>
<script type='text/javascript' src='assets/node_modules/easy-autocomplete/dist/jquery.easy-autocomplete.min.js'></script>
<script type='text/javascript' src='assets/js/plugins/filestyle/bootstrap-filestyle.min.js'></script>
<script type="text/javascript" src="assets/js/plugins/fileinput/fileinput.min.js"></script> 
<script type='text/javascript' src='assets/js/modalMultiple.js'></script>
<script type='text/javascript' src='assets/salir/script_salir.js'></script>
<script type="text/javascript" src="//cdn.rawgit.com/icons8/bower-webicon/v0.10.7/jquery-webicon.min.js"></script>
<script src='assets/js/velocity.min.js'></script>
<script src='assets/js/velocity.ui.min.js'></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.js"></script>
<script>

    $(document).ready(function () {
        $('.page-container.login form').submit(function (e) {
            e.preventDefault();
            var username = $(this).find('.username').val();
            var password = $(this).find('.password').val();

            if (username == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '27px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.username').focus();
                });

                return false;
            }
            if (password == '') {
                $(this).find('.error').fadeOut('fast', function () {
                    $(this).css('top', '96px');
                });
                $(this).find('.error').fadeIn('fast', function () {
                    $(this).parent().find('.password').focus();
                });
                return false;
            }

            /// VALIDAMOS QUE NO EXISTAN CAMPOS VACIOS ///
            if (username != '' && password != '') {

                var formData = new FormData();
                formData.append('username', username);
                formData.append('password', password);
                formData.append('meth', 'login');
                $.ajax({
                    url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                    success: function (data) {

                        if (data.scriptResp == "noMatch") {
                            $(".notificacion").html('<b style="font-size: 24px;">Error ! </b><p>Nombre de usuario y/o contraseñas incorrectos, intente nuevamente</p>');
                            $(".notificacion").show('slow').delay(4000).hide('slow');
                            $('.username').val('');
                            $('.password').val('');
                        } else {
                            window.location.href = "/?show=home#autoscroll";
                        }
                    },
                    error: function (error) {
                        console.log("Hubo un error de internet, intente de nuevo");
                        console.log(error);
                    }
                });
            }
        });

        $('.page-container form .username, .page-container form .password').keyup(function () {
            $(this).parent().find('.error').fadeOut('fast');
        });

    });

////////////////////////CERRAMOS LA VENTNA DE NOTIFICACION CON CLIC EN CUALQUIER PARTE DE LA PAGINA
    $(document).on("click", function () {
        $(".customalert").animate({width: 'hide'}, 600);
    });

    $('.numonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9-]/g, ''));
    });

    $('.alphanumonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9a-zA-Z-]/g, ''));
    });

    $('.alphaonly').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^a-zA-Z\-\s]/g, ''));
    });
</script>
<?php

require ("modules/" . $module . "/scripts.php");

//
//switch ($panel) {///////////////////////////////////////////////////////////////SELECTOR DE PANEL, DEPENDIENDO DEL PANEL HACE LAS LLAMADAS A LOS ARCHIVOS CORRESPONDINETES
//    case "cocina.php":
//        echo "<script type='text/javascript' src='assets/cocina/scriptcocina.js'></script>";
//        break;
//    case "procesos.php":
//        require ("assets/procesos/model.php");
//        break;
//    case "anadirpedido.php":
//        echo "<script type='text/javascript' src='assets/js/script_anadirpedido.js'></script>";
//        echo "<script type='text/javascript' src='assets/anadirpedido/script_anadirpedido.js'></script>";
//        break;
//    case "dashboard.php":
//        echo "<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyA_s9AhhJurXNx1UHeK_6hm6CdSB8AR14c\"></script>";
//        echo "<script type='text/javascript' src='assets/dashboard/dashboard.js'></script>";
//        echo "<script type='text/javascript' src=\"assets/dashboard/echarts/dist/echarts.js\"></script>";
//        require ("assets/dashboard/dashboardscripts.php");
//        break;
//    case "caja.php":
//        echo "<script type='text/javascript' src='assets/caja/script_caja.js'></script>";
//        require ("assets/caja/caja_scripts.php");
//        break;
//    case "factura.php":
//        echo "<script type='text/javascript' src='assets/factura/script_factura.js'></script>";
//        echo "<script type='text/javascript' src='assets/cliente/script_cliente.js'></script>";
//        echo "<script type='text/javascript' src='assets/cliente/script_validacionCliente.js'></script>";
//        echo "<script type='text/javascript' src='assets/js/script_validaMoney.js'></script>";
//        break;
//    case "domicilio.php":
//        require ("assets/domicilio/dom_scripts.php");
//        echo "<script type='text/javascript' src='assets/domicilio/dom_facturardom.js'></script>";
//        break;
//    case "nuevodomicilio.php":
//        echo "<script type='text/javascript' src='assets/js/script_menu_seleccion_productos.js'></script>";
//        echo "<script type='text/javascript' src='assets/domicilio/dom_seleccionproducto.js'></script>";
//        echo "<script type='text/javascript' src='assets/js/script_validaMoney.js'></script>";
//        echo "<script type='text/javascript' src='assets/cliente/script_cliente.js'></script>";
//        echo "<script type='text/javascript' src='assets/cliente/script_validacionCliente.js'></script>";
//        break;
//    case "parallevar.php":
//        echo "<script type='text/javascript' src='assets/cliente/script_cliente.js'></script>";
//        echo "<script type='text/javascript' src='assets/cliente/script_validacionCliente.js'></script>";
//        echo "<script type='text/javascript' src='assets/js/script_validaMoney.js'></script>";
//        echo "<script type='text/javascript' src='assets/js/script_menu_seleccion_productos.js'></script>";
//        echo "<script type='text/javascript' src='assets/parallevar/script_seleccionproductos.js'></script>";
//        break;
//    case "reporte.php":
//        echo '<script type="text/javascript" charset="utf8" src="assets/js/datatables/datatables.js"></script>';
//        echo "<script type='text/javascript' src='assets/reporteventa/script_validacionReporte.js'></script>";
//        echo "<script type='text/javascript' src='assets/reporteventa/script_reporteventa.js'></script>";
//        break;
//    case "user_config.php":
//        echo '<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.js"></script>';
//        echo '<script type="text/javascript" src="assets/user_config/script_user_config.js"></script>';
//        break;
//    case "entregas.php":
//        echo "<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyA_s9AhhJurXNx1UHeK_6hm6CdSB8AR14c\"></script>";
//        echo "<script type='text/javascript' src='assets/entregas/ent_scripts.js'></script>";
//        echo "<script type='text/javascript' src='assets/entregas/ent_scripts.php'></script>";
//        require ("assets/entregas/ent_scripts.php");
//        break;
//    case "inventory.php":
//        require ("assets/inventory/model.php");
//        break;
//    case "user.php":
//        require ("assets/users/model.php");
//        break;
//    case "carta.php":
//        require ("assets/carta/model.php");
//        break;
//}
?>
