<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".newpedido").addClass("active");

    //          CARGAMOS LAS MESAS Y LOS PEDIDOS           //
    cargarMesasNiveles();
    actualizaTabla();

    //      MOSTRAR MESAS Y NIVELES AL HACER CLIC    //
    $(document).on("click", ".mostratMesasBtn", function () {
        $(".menuItemTabs").delay(500).slideToggle(500, "easeInOutBack");
    });

    //      Seleccionar Mesa Para nuevo pedido  //
    $(document).on("click", ".menuItemBox", function () {
        var html = '';
        $(".menuItemBox").removeClass('tile-selected');
        $(this).addClass('tile-selected');
        html += '<span class="hidethis idmesaSelected">' + $(this).parent().find('.idMesaContainer').html() + '</span>';
        html += '<span class="namemesaSelected">' + $(this).text() + '</span>';
        $('.mesaSelected').html(html);
    });

    //              VALIDAMOS  EL NUEVO PEDIDO QUE SE VA A CARGAR Y SI LA MESA YA FUE SELECCIONADA      //
    $(".btnNuevoPedido").click(function () {
        if ($(".mesaSelected").html() != "" && $(".mesaSelected").html() != "Seleccione") {
            var formData = new FormData();
            formData.append('idmesa', $(".mesaSelected .idmesaSelected").html());
            formData.append('numeromesa', $(".mesaSelected .namemesaSelected").html());
            formData.append('meth', 'asignaMesa');
            $.ajax({
                url: 'api/api.php',
                type: 'POST',
                dataType: "json",
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function (data) {
                    window.location.replace("/?show=pedido");
                },
                error: function (error) {
                    console.log("Hubo un error de internet, intente de nuevo");
                    console.log(error);
                }
            });
        } else {
            $.notify('Mesa no seleccionada !\n Seleccione una mesa e intente nuevamente', "error");
        }
    });

    //          EDITAR EL PEDIDO SELECCIONADO EN EL MODAL           //
    $(".editThisOrder").click(function () {
        var formData = new FormData();
        formData.append('idpedido', $(".idPedidoContainer").html());
        formData.append('idmesa', $(".idMesaContainer").html());
        formData.append('numeromesa', $(".numeroMesaContainer").html());
        formData.append('meth', 'asignaMesa');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                window.location.replace("/?show=pedido");
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    });

    //      AL HACER CLIC EN CADA PEDIDO DE LA TABLA        //
    var idMesa, numeroMesa, idPedido, estadoPedido;
    $(document).on('click', '.estadoPedido', function (e) {

        idMesa = $(this).find(".idMesa").html();
        numeroMesa = $(this).find(".numeroMesa").html();
        idPedido = $(this).find(".idPedido").html();
        estadoPedido = $(this).find(".estadoPedido").html();

        var formData = new FormData();
        formData.append('idmesa', idMesa);
        formData.append('numeromesa', numeroMesa);
        formData.append('idpedido', idPedido);
        formData.append('meth', 'asignaMesa');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                asignaPedido(idPedido);
                $(".tituloEstadoPedido").html("<center>Pedido # " + idPedido + " en " + numeroMesa + "</center>");
                $(".idPedidoContainer").html(idPedido);
                $(".numeroMesaContainer").html(numeroMesa);
                $(".idMesaContainer").html(idMesa);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    });

    //                  LLENAMOS EL MODAL CON LOS DATOS DEL PEDIDO          //
    function asignaPedido(idpedido) {
        var formData = new FormData();
        formData.append('idpedido', idpedido);
        formData.append('meth', 'consultaProductos');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                $(".contenidoEstadoPedido").html(data.output);
                $("#ModalEstadoPedido").modal("show");
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //           PARA CANCELAR EL PEDIDO        //
    var idpedidoproducto, idpedidoproductocombinado1, idpedidoproductocombinado2, idpedidoproductocombinado3, descripcionpedidoproducto, menupedidoproducto;
    $(document).on('click', '.cancelarPedido', function (e) {

        //                      CONSTRUIMOS EL MODAL DE OCNFIRMACION            //
        idpedidoproducto = $(this).parent().parent().find(".idpedidoproducto").html();
        var nombrepedidoproducto = $(this).parent().parent().find(".nombrepedidoproducto").html();
        var submenupedidoproducto = $(this).parent().parent().find(".submenupedidoproducto").html();
        descripcionpedidoproducto = $(this).parent().parent().find(".descripcionpedidoproducto").html();
        menupedidoproducto = $(this).parent().parent().find(".menupedidoproducto").html();

        var html = "<br>" +
                "<div style='padding: 20px;'><div class='tile tile-primary' style='padding: 20px;'>" +
                "<p style='font-size: 20px;text-align: center;'>" + nombrepedidoproducto + "</p>";

        if ((descripcionpedidoproducto != "Unitario" && descripcionpedidoproducto !== "entera")) {
            if (descripcionpedidoproducto == "Combinada 1/2") {
                idpedidoproductocombinado1 = $(this).parent().parent().find(".idpedidoproductocombinado1").html();
                html += "<p style='font-size: 20px;text-align: center;'>" + submenupedidoproducto + "</p>";
                html += "<p style='font-size: 20px;text-align: center;'>" + $(this).parent().parent().find(".nombrepedidoproductocombinado1").html() + "</p>";
            } else
            if (descripcionpedidoproducto == "Combinada 1/4") {
                idpedidoproductocombinado1 = $(this).parent().parent().find(".idpedidoproductocombinado1").html();
                html += "<p style='font-size: 20px;text-align: center;'>" + submenupedidoproducto + "</p>";
                html += "<p style='font-size: 20px;text-align: center;'>" + $(this).parent().parent().find(".nombrepedidoproductocombinado1").html() + "</p>";
            } else
            if (descripcionpedidoproducto == "Personalizada") {
                idpedidoproductocombinado1 = $(this).parent().parent().find(".idpedidoproductocombinado1").html();
                idpedidoproductocombinado2 = $(this).parent().parent().find(".idpedidoproductocombinado2").html();
                idpedidoproductocombinado3 = $(this).parent().parent().find(".idpedidoproductocombinado3").html();

                html += "<p style='font-size: 20px;text-align: center;'>" + submenupedidoproducto + "</p>";
                html += "<p style='font-size: 20px;text-align: center;'>" + $(this).parent().parent().find(".submenupedidoproductocombinado1").html() + "</p>";
                html += "<p style='font-size: 20px;text-align: center;'>" + $(this).parent().parent().find(".submenupedidoproductocombinado2").html() + "</p>";
                html += "<p style='font-size: 20px;text-align: center;'>" + $(this).parent().parent().find(".submenupedidoproductocombinado3").html() + "</p>";
            }
            html += "<p style='font-size: 15px;text-align: center;padding-top: 15px;font-style: italic;'>" + descripcionpedidoproducto + "</p>";
        } else {
            if (menupedidoproducto != "Bebidas") {
                html += "<p style='font-size: 20px;text-align: center;'>" + submenupedidoproducto + "</p>";
            }
        }

        html += "</div></div>" +
                "<br>" +
                "<p style='font-size: 20px;text-align: center;'> Desea realmente cancelar el pedido actual ?</p>";
        $(".contenidoCancelar").html(html);
        $(".modalCancelar").modal("show");

    });

    //          SI EL CLIENTE CONFIRMA LA CANCELACION DEL PEDIDO            //
    $(document).on('click', '.confirmaCancelaPedido', function (e) {

        var formData = new FormData();
        formData.append('idpedidoproducto', idpedidoproducto);
        formData.append('descripcionpedidoproducto', descripcionpedidoproducto);
        formData.append('menupedidoproducto', menupedidoproducto);
        formData.append('numeromesa', numeroMesa);
        formData.append('idpedido', idPedido);
        formData.append('meth', 'cancelaPedido');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                actualizaTabla();
                $(".modalCancelar,#ModalEstadoPedido").modal("hide");
                console.log(data);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    });

    //          LLENAMOS LA TABLA DE LOS PEDIDOS ACTUALES           //
    function actualizaTabla() {
        $(".contenedorPedido").html('');
        var formData = new FormData();
        formData.append('meth', 'consultaPedidos');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                $(".mesas-ocu").text(data.pedidos.length + " ocupada(s)");
                if (data.pedidos.length != 0) {
                    $(data.pedidos).each(function (index, value) {
                        var tile, icon;
                        if (value.estadoPedido == "SOLICITADO") {
                            tile = "tile-info";
                            icon = '<i class="fa fa-asterisk fa-2x" style="font-size:20px;color:white;" aria-hidden="true"></i>';
                        } else
                        if (value.estadoPedido == "EN PROCESO") {
                            tile = "tile-warning";
                            icon = '<i class="fas fa-sync-alt fa-spin fa-2x fa-fw" style="font-size:20px;color:white;"></i>';
                        } else
                        if (value.estadoPedido == "LISTO PARA ENTREGAR") {
                            tile = "tile-success";
                            icon = '<i class="fa fa-check" style="font-size:20px;color:white;" aria-hidden="true"></i>';
                        } else
                        if (value.estadoPedido == "ENTREGADO") {
                            tile = "tile-default";
                            icon = '<i class="fas fa-vote-yea" aria-hidden="true" style="font-size:20px;color:black;"></i>';
                        }

                        $(".contenedorPedido").append(
                                '<div class="col-md-3">' +
                                '<a href="#" class="tile ' + tile + ' estadoPedido" style="padding: 22px;">' +
                                value.numeroMesa +
                                '<p> Pedido # ' + value.idPedido + '</p>' +
                                '<div style="position: absolute;top: -24px;right: 2px;">' + icon + '</div>' +
                                '<div style="position: absolute;top: -5px;left: 7px;"><p style="font-size:25px;color:white;">' + (index + 1) + '</p></div>' +
                                '<div style="display:none;" class="idMesa">' + value.idMesa + '</div>' +
                                '<div style="display:none;" class="numeroMesa">' + value.numeroMesa + '</div>' +
                                '<div style="display:none;" class="idPedido">' + value.idPedido + '</div>' +
                                '<div style="display:none;" class="estadoPedido">' + value.estadoPedido + '</div>' +
                                '</a>' +
                                '</div>'
                                );
                    });
                } else {
                    $(".contenedorPedido").append("<center><p style='padding:10px;color:white;'><h1 class='txtwhite'>Ningún pedido por atender</h1></p></center>");
                }
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //              DISTRIBUIMOS LAS MESAS EN SUS RESPECTIVOS NIVELES           //
    function cargarMesasNiveles() {
        var formData = new FormData(),
                i = 0;
        formData.append('meth', 'mesas');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                $(".mesas-disp").text(data.mesas.length + " disponible(s)");
                var htmlcontent = '<ul class="nav nav-tabs nav-justified">';
                var htmlcontentTabs = '<div class="panel-body tab-content">';

                $.each(data.niveles, function (i, n) {
                    if (i == 0) {
                        htmlcontent += '<li class="active"><a href="#tab' + i + '" data-toggle="tab"> <button type="button" class="btn btn-primary btn-rounded">' + n + '</button></a></li>';
                        htmlcontentTabs += '<div class="tab-pane active" id="tab' + i + '">';
                        $.each(data.mesas, function (ii, nn) {
                            if (nn.nivelMesa == n && nn.numeroMesa != '999') {
                                htmlcontentTabs += '<div class="col-md-3"><div class="hidethis idMesaContainer">' + nn.idMesa + '</div><a  class="tile tile-info tile-valign menuItemBox">' + nn.numeroMesa + '<div class="informer informer-default"><i class="fas fa-toggle-off"></i></div></a></div>';
                            }
                        });
                        htmlcontentTabs += '</div>';
                    } else {
                        htmlcontent += '<li><a href="#tab' + i + '" data-toggle="tab"><button type="button" class="btn btn-primary btn-rounded">' + n + '</button></a></li>';
                        htmlcontentTabs += '<div class="tab-pane" id="tab' + i + '">';
                        $.each(data.mesas, function (ii, nn) {
                            if (nn.nivelMesa == n && nn.numeroMesa != '999') {
                                htmlcontentTabs += '<div class="col-md-3"><div class="hidethis idMesaContainer">' + nn.idMesa + '</div><a class="tile tile-info tile-valign menuItemBox">' + nn.numeroMesa + '<div class="informer informer-default"><i class="fas fa-toggle-off"></i></div></a></div>';
                            }
                        });
                        htmlcontentTabs += '</div>';
                    }
                    i++;
                });
                htmlcontent += '</ul>';
                htmlcontentTabs += '</div>';
                $(".menuItemTabs").html(htmlcontent + htmlcontentTabs);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //                      MANDAMOS EL PEDIDO PARA IMPRIMIR                //
    $(document).on('click', '.pedido_imprimir', function () {
        var mesa_nro = $("#ModalEstadoPedido .modal-body h3:eq(0)").html();
        var pedido_nro = $("#ModalEstadoPedido .modal-header h4:eq(0)").html();
        var pedidos = $("#ModalEstadoPedido .modal-body").children("div");
        var output = "";
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        output += "<tr><td> " + mesa_nro + "  <br /></td></tr> \n\ ";
        output += "<tr><td> " + pedido_nro + " <br /></td></tr> \n\ ";
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        $(pedidos).each(function (index, value) {
            var ped = $(value).find(".nombrepedidoproducto").html();
            var cat = $(value).find(".submenupedidoproducto").html();
            var table = $(value).children("table").html();
            var table_obj = $(value).children("table");
            if (table == null) {
                output += "<tr><td> " + ped + " - " + cat + " <br /></td></tr> \n\ ";
            } else {
                output += "<tr><td> " + ped + " - " + cat + " <br /></td></tr> \n\ ";
                $(table_obj).find("tbody tr td ul li").each(function (index, value) {
                    var ing = $(value).html();
                    output += "<tr><td> " + ing + " <br /></td></tr> \n\ ";
                });
                output += "<tr><td> --------------------- <br /></td></tr> \n\ ";
            }
        });
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        $("body").append("<table id='pedido_imprimir'><tbody> " + output + " </tbody></table>");
        $('#pedido_imprimir').tableExport({
            type: 'pdf',
            escape: 'false'
        });
        console.log(output);
    });
    var descripcionpedidoproducto;

    //              CUANDO VISUALIZMOS EL MODAL DE PEDIDO Y QUEREMOS EDITAR UNA ORDEN           //
    var idpedido, idpedidoproducto, idproducto, nombrepedidoproducto, nombreMenu, nombreSubmenu, idsubmenu, idmenu, observacionpedidoproducto, cantidadpedidoproducto, idpedidoproductocombinado1, nombrepedidoproductocombinado1, submenupedidoproductocombinado1, idpedidoproductocombinado2, nombrepedidoproductocombinado2, submenupedidoproductocombinado2, idpedidoproductocombinado3, nombrepedidoproductocombinado3, submenupedidoproductocombinado3;
    $(document).on('click', '.editarPedido', function () {

        idproducto = $(this).parent().parent().find(".idproducto").html();
        idmenu = $(this).parent().parent().find(".idmenu").html();
        observacionpedidoproducto = $(this).parent().parent().find(".observacionpedidoproducto").html();
        cantidadpedidoproducto = $(this).parent().parent().find(".cantidadpedidoproducto").html();
        idpedido = $(this).parent().parent().find(".idpedido").html();
        idpedidoproducto = $(this).parent().parent().find(".idpedidoproducto").html();
        descripcionpedidoproducto = $(this).parent().parent().find(".descripcionpedidoproducto").html();

        $(".tituloEditaIngredientes").html("Ingredientes " + nombrepedidoproducto);
        displayProduct(idproducto, $('.contenidoEditaIngredientes').get(0));
        setTimeout(function () {
            $(document).find('.showProductPanelContainer').removeClass('col-md-3').addClass('col-md-9');
            $("#ModalEditaIngredientes").modal("show");
        }, 1500);

    });

    $('#ModalEditaIngredientes').on('hidden.bs.modal', function () {
        $(".contenidoEditaIngredientes").html("");
        $(".input-number").val(1);
    });

    function estableceTipoPizza(idSubmenu, nombreSubmenu, idMenu, nombreMenu, idProducto) {
        $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + "</center>");
        $(".contenidoEditaPizza").html("");

        var formData = new FormData();
        formData.append('idsubmenu', idSubmenu);
        formData.append('meth', 'getProductos');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                if (data.status == 'yes') {
                    var htmlselect = '<center><div class="btn-group radioTipopizzas" data-toggle="buttons">' +
                            '<label class="btn btn-primary">' +
                            '<input type="radio" name="options" value="" autocomplete="off">Seleccione ..' +
                            '</label>';
                    $.when(
                            $(data.productos).each(function (index, value) {

                        htmlselect += '<label class="btn btn-primary">' +
                                '<input type="radio" name="options" id="' + value.idProducto + '" value="' + value.idProducto + '" autocomplete="off">' + value.nombreProducto +
                                "<div class='nombreproducto' style='display: none;'>" + value.nombreProducto + "</div>" +
                                "<div class='precioproducto' style='display: none;'>" + value.precioProducto + "</div>" +
                                "<div class='idproducto' style='display: none;'>" + value.idProducto + "</div>" +
                                "<div class='idsubmenu' style='display: none;'>" + value.idSubmenu + "</div>" +
                                "<div class='nombresubmenu' style='display: none;'>" + nombreSubmenu + "</div>" +
                                "<div class='nombremenu' style='display: none;'>" + nombreMenu + "</div>" +
                                "<div class='idmenu' style='display: none;'>" + idMenu + "</div>" +
                                '</label>';
                    })
                            ).then(function () {
                        htmlselect += '</div>' +
                                '</center><br>' +
                                '<div id="contentPizzasPrincipal"></div>';
                        $(".contenidoEditaPizza").append(htmlselect);

                        //PARA BUSCAR EL PRODUCTO SELECCIONADO
                        $(".radioTipopizzas .btn-primary .idproducto").each(function (index, value) {
                            if ($(this).text() == idProducto) {
                                $(this).parent().addClass("active");
                                $(this).parent().find("input[type='radio']").prop("checked", true);
                                asignaTipoPizza($(this));
                            }
                        });
                    });
                }
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
        $("#ModalEditaPizza").modal("show");
    }

    var Menu, nombre, precio, id, idsubmenu, nombreSubmenu, idmenu, nombremenu;
    function asignaTipoPizza(elemento) {

        nombre = elemento.parent().find(".nombreproducto").html();
        precio = elemento.parent().find(".precioproducto").html();
        id = elemento.parent().find(".idproducto").html();
        idsubmenu = elemento.parent().find(".idsubmenu").html();
        nombreSubmenu = elemento.parent().find(".nombresubmenu").html();
        idmenu = elemento.parent().find(".idmenu").html();
        nombremenu = elemento.parent().find(".nombremenu").html();

        var formData = new FormData();
        formData.append('idsubmenu', idsubmenu);
        formData.append('meth', 'getIdperfil');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                Menu = data.menu;
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });

        $(".tituloSeleccionPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + "</center>");
        $("#contentPizzasPrincipal").html(
                '<center><div class="btn-group radioPizzas" data-toggle="buttons">' +
                '<label class="btn btn-primary">' +
                '<input type="radio" name="options" value="" autocomplete="off">Seleccione ..' +
                '</label>' +
                '<label class="btn btn-primary">' +
                '<input type="radio" name="options" id="entera" value="entera" autocomplete="off">Entera' +
                "<div class='nombre' style='display: none;'>entera</div>" +
                '</label>' +
                '<label class="btn btn-primary">' +
                '<input type="radio" name="options" id="medio" value="medio" autocomplete="off">Combinada 1/2' +
                "<div class='nombre' style='display: none;'>Combinada 1/2</div>" +
                '</label>' +
                '<label class="btn btn-primary">' +
                '<input type="radio" name="options" id="cuarto" value="cuarto" autocomplete="off">Combinada 1/4' +
                "<div class='nombre' style='display: none;'>Combinada 1/4</div>" +
                '</label>' +
                '<label class="btn btn-primary">' +
                '<input type="radio" name="options" id="personalizada" value="personalizada" autocomplete="off">Personalizada' +
                "<div class='nombre' style='display: none;'>Personalizada</div>" +
                '</label>' +
                '</div>' +
                '</center><br>' +
                "<div class='col-md-12' id='contentSeleccion'></div>"
                );


        //PARA BUSCAR EL PRODUCTO SELECCIONADO
        $(".radioPizzas .btn-primary .nombre").each(function (index, value) {
            if ($(this).text() == descripcionpedidoproducto) {
                $(this).parent().addClass("active");
                $(this).parent().find("input[type='radio']").prop("checked", true);
                asignaPizza($(this).parent().find("input[type='radio']"));
            }
        });
    }

    var pizzaTemporal = {};

    function asignaPizza(elemento) {

        pizzaTemporal = {};
        pizzaTemporal.pizza = nombre;
        pizzaTemporal.id = id;
        pizzaTemporal.precio = precio;
        pizzaTemporal.idsubmenu = idsubmenu;
        pizzaTemporal.nombresubmenu = nombreSubmenu;
        pizzaTemporal.idmenu = idmenu;
        pizzaTemporal.nombremenu = nombremenu;


        //Regreso a la normalidad
        $(".contentIngredientes").html("");
        $(".contentIngredientes").hide();
        //$(".btnEnviaSeleccion").hide();

        if (elemento.val() == "") {
            $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + "</center>");
            $(".contentIngredientes").html("");
            $(".contentIngredientes").hide();
            $("#contentSeleccion").html("");
        }
        if (elemento.val() == "entera") {

            $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + " Entera</center>");

            $.ajax({
                // Verificacion de los datos introducidos
                url: 'assets/hacerpedido/consultaPizzas.php',
                type: 'POST',
                dataType: "json",
                data: {
                    nombreProducto: nombre,
                },
                success: function (pizzas) {
                    var htmlselectPizzas = "<option value=''>Seleccione ..</option>";
                    $.when(
                            $(pizzas).each(function (index, value) {
                        if (nombreSubmenu != value.nombreSubmenu) {
                            htmlselectPizzas += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                        }
                    })
                            ).then(function () {
                        $("#contentSeleccion").html(
                                "<div class='grid'>" +
                                "<div class='row'>" +
                                "<div class='col-md-6 col-sm-6 col-xs-6 col-md-offset-3 col-sm-offset-3 col-xs-offset-3'>" +
                                "<div class='row row-space' style='border: 1px solid; border-radius: 6px; border-color: #b64645;'>" +
                                "<div class='col-md-12'>" +
                                "<br>" + "<br>" +
                                "<div class='col-md-12'>" +
                                "<center><img src='assets/img/pizzas/p_entera.png' alt='pizza entera' class='img-responsive imgEntera'>" + "</center>" +
                                "<br>" + "<br>" +
                                "</div>" +
                                "</div>" +
                                '<center>' +
                                '<div class="btn-group" data-toggle="buttons" style="width:100%">' +
                                '<label class="btn btn-primary btn-block">' +
                                '<input type="checkbox" class="inp_entera" autocomplete="off"><div id="lblEntera">' + nombreSubmenu + '</div>' +
                                ' </label>' +
                                "</div>" +
                                '</center>' +
                                "</div>" +
                                "</div>" +
                                "</div>" +
                                "</div>"

                                );

                        $("#contentSeleccion").append(
                                '<br><div class="row">' +
                                '<div class="col-md-12">' +
                                '<div class="col-md-5">' +
                                '<h4 style="color: #b64645;padding-top: 12px;" class="tituloCantidad">Cantidad producto :</h4>' +
                                '</div>' +
                                '<div class="col-md-7">' +
                                '<div class="col-md-9 col-md-offset-3">' +
                                '<div class="form-group">' +
                                '<div class="center">' +
                                '<p></p>' +
                                '<div class="input-group">' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="minus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-minus"></span>' +
                                '</button>' +
                                '</span>' +
                                '<input type="number" name="quant[1]" class="form-control input-number" value="' + cantidadpedidoproducto + '" min="1" max="100" style="color:black;font-weight: bold;text-align:center;" disabled>' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="plus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-plus"></span>' +
                                '</button>' +
                                '</span>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '<br>' +
                                '</div>' +
                                '</div>' +
                                '<div class="col-md-12">' +
                                '<div class="form-group">' +
                                '<h4 style="color: #b64645;">Observación del pedido :</h4>' +
                                '<textarea class="form-control observacionProducto" rows="3" id="comment" style="resize: none;border-color: #b64645;" placeholder="Ingrese aquí la observación del pedido actual.">' + observacionpedidoproducto + '</textarea>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '</div>'
                                );

                        funcionalidadCantidad();

                        pizzaTemporal.tipo = "entera";
                        pizzaTemporal.id = id;
                        pizzaTemporal.nombre = nombremenu;
                        pizzaTemporal.nombreSubmenu = nombreSubmenu;
                        pizzaTemporal.ingredientes = [];

                    });

                },
                error: function (error) {
                    console.log('Disculpe, existió un problema');
                    console.log(error);
                },
                complete: function (xhr, status) {
                    console.log('Petición realizada');
                }
            });

            $(".btnEnviaSeleccion").show();
        } else
        if (elemento.val() == "medio") {
            $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + " Combinada 1/2</center>");
            $.ajax({
                // Verificacion de los datos introducidos
                url: 'assets/hacerpedido/consultaPizzas.php',
                type: 'POST',
                dataType: "json",
                data: {
                    nombreProducto: nombre,
                },
                success: function (pizzas) {
                    var htmlselectPizzas = "<option value=''>Seleccione ..</option>";
                    $.when(
                            $(pizzas).each(function (index, value) {
                        if (nombreSubmenu != value.nombreSubmenu) {
                            if (submenupedidoproductocombinado1 == value.nombreSubmenu) {
                                htmlselectPizzas += "<option value='" + value.idProducto + "' selected>" + value.nombreSubmenu + "</option>";
                            } else {
                                htmlselectPizzas += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                            }
                        }
                    })
                            ).then(function () {
                        $("#contentSeleccion").html(
                                "<div class='grid'>" +
                                "<div class='row'>" +
                                "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                "<div class='row row-space' style='border: 1px solid; border-radius: 6px; border-color: #b64645;'>" +
                                '<center>' +
                                '<div class="btn-group" data-toggle="buttons" style="width:100%">' +
                                '<label class="btn btn-primary btn-block">' +
                                '<input type="checkbox" class="inp_medio1" autocomplete="off"><div id="lblMitad1">' + submenupedidoproductocombinado1 + '</div>' +
                                ' </label>' +
                                "</div>" +
                                '</center>' +
                                "<div class='col-md-12'>" +
                                "<br>" + "<br>" +
                                "<div class='col-md-12'>" +
                                "<center><img src='assets/img/pizzas/p_medio1.png' alt='pizza media' class='img-responsive imgMedio1'></center>" +
                                "</div>" +
                                "<div class='col-md-12'>" +
                                "<center><img src='assets/img/pizzas/p_medio2.png' alt='pizza media' class='img-responsive imgMedio2'></center>" +
                                "<br>" + "<br>" +
                                "</div>" +
                                "</div>" +
                                '<center>' +
                                '<div class="btn-group" data-toggle="buttons" style="width:100%">' +
                                '<label class="btn btn-primary btn-block">' +
                                '<input type="checkbox" class="inp_medio2" autocomplete="off"><div id="lblMitad2">' + nombreSubmenu + '</div>' +
                                ' </label>' +
                                "</div>" +
                                '</center>' +
                                "</div>" +
                                "</div>" +
                                "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                "<br>" +
                                "<div class='form-group'>" +
                                "<label for=''>Mitad 2</label><br/>" +
                                "<select class='form-control selectPizzaMedio' >" +
                                htmlselectPizzas +
                                "</select>" +
                                "</div>" +
                                "</div>" +
                                "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                "<br>" +
                                "<div class='form-group'>" +
                                "<label for=''>Mitad 1</label><br/>" +
                                nombreSubmenu +
                                "</div>" +
                                "</div>" +
                                "</div>" +
                                "</div>"


                                );

                        $("#contentSeleccion").append(
                                '<br><div class="row">' +
                                '<div class="col-md-12">' +
                                '<div class="col-md-5">' +
                                '<h4 style="color: #b64645;padding-top: 12px;" class="tituloCantidad">Cantidad producto :</h4>' +
                                '</div>' +
                                '<div class="col-md-7">' +
                                '<div class="col-md-9 col-md-offset-3">' +
                                '<div class="form-group">' +
                                '<div class="center">' +
                                '<p></p>' +
                                '<div class="input-group">' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="minus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-minus"></span>' +
                                '</button>' +
                                '</span>' +
                                '<input type="number" name="quant[1]" class="form-control input-number" value="' + cantidadpedidoproducto + '" min="1" max="100" style="color:black;font-weight: bold;text-align:center;" disabled>' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="plus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-plus"></span>' +
                                '</button>' +
                                '</span>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '<br>' +
                                '</div>' +
                                '</div>' +
                                '<div class="col-md-12">' +
                                '<div class="form-group">' +
                                '<h4 style="color: #b64645;">Observación del pedido :</h4>' +
                                '<textarea class="form-control observacionProducto" rows="3" id="comment" style="resize: none;border-color: #b64645;" placeholder="Ingrese aquí la observación del pedido actual.">' + observacionpedidoproducto + '</textarea>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '</div>'
                                );

                        funcionalidadCantidad();

                        pizzaTemporal.tipo = "Combinada 1/2";
                        pizzaTemporal.id = id;
                        pizzaTemporal.nombre = nombremenu;
                        pizzaTemporal.nombreSubmenu = nombreSubmenu;
                        pizzaTemporal.ingredientes = [];

                        pizzaTemporal.idMedio = "";
                        pizzaTemporal.nombreMedio = "";
                        pizzaTemporal.ingredientesMedio = [];
                    });
                },
                error: function (error) {
                    console.log('Disculpe, existió un problema');
                    console.log(error);
                },
                complete: function (xhr, status) {
                    console.log('Petición realizada');
                }
            });
        } else
        if (elemento.val() == "cuarto") {
            $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + " Combinada 1/4</center>");
            $.ajax({
                // Verificacion de los datos introducidos
                url: 'assets/hacerpedido/consultaPizzas.php',
                type: 'POST',
                data: {
                    nombreProducto: nombre,
                },
                dataType: "json",
                success: function (pizzas) {
                    var htmlselectPizzas = "<option value=''>Seleccione ..</option>";
                    $.when(
                            $(pizzas).each(function (index, value) {
                        if (nombreSubmenu != value.nombreSubmenu) {
                            if (submenupedidoproductocombinado1 == value.nombreSubmenu) {
                                htmlselectPizzas += "<option value='" + value.idProducto + "' selected>" + value.nombreSubmenu + "</option>";
                            } else {
                                htmlselectPizzas += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                            }
                        }
                    })
                            ).then(function () {

                        $("#contentSeleccion").html(
                                "<div class='grid'>" +
                                "<div class='row'>" +
                                "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                "<div class='row row-space' style='border: 1px solid; border-radius: 6px; border-color: #b64645;'>" +
                                '<center>' +
                                '<div class="btn-group" data-toggle="buttons" style="width:100%">' +
                                '<label class="btn btn-primary btn-block">' +
                                '<input type="checkbox" class="inp_cuarto1" autocomplete="off"><div id="lblCuarto1">' + submenupedidoproductocombinado1 + '</div>' +
                                ' </label>' +
                                "</div>" +
                                '</center>' +
                                "<div class='col-md-12'>" +
                                "<br>" + "<br>" +
                                "<div class='col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2' style='position:absolute;z-index:500;left: 0;right: 0;margin: 0 auto;'>" +
                                "<center><img src='assets/img/pizzas/p_cuarto1.png' alt='pizza media' class='img-responsive imgCuarto1'></center>" +
                                "</div>" +
                                "<div class='col-md-12' style='padding-top: 33px;padding-right: 15px;'>" +
                                "<center><img src='assets/img/pizzas/p_cuarto2.png' alt='pizza media' class='img-responsive imgCuarto2'></center>" +
                                "<br>" + "<br>" +
                                "</div>" +
                                "</div>" +
                                '<center>' +
                                '<div class="btn-group" data-toggle="buttons" style="width:100%">' +
                                '<label class="btn btn-primary btn-block">' +
                                '<input type="checkbox" class="inp_cuarto2" autocomplete="off"><div id="lblCuarto2">' + nombreSubmenu + '</div>' +
                                ' </label>' +
                                "</div>" +
                                '</center>' +
                                "</div>" +
                                "</div>" +
                                "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                "<br>" + "<br>" +
                                "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                "<div class='form-group'>" +
                                "<label for=''>Cuarto</label><br/>" +
                                "<select class='form-control selectPizzaCuarto' >" +
                                htmlselectPizzas +
                                "</select>" +
                                "</div>" +
                                "<div class='form-group'>" +
                                "<label for=''>Pizza</label><br/>" +
                                nombreSubmenu +
                                "</div>" +
                                "</div>" +
                                "</div>" +
                                "</div>" +
                                "</div>"

                                );

                        $("#contentSeleccion").append(
                                '<br><div class="row">' +
                                '<div class="col-md-12">' +
                                '<div class="col-md-5">' +
                                '<h4 style="color: #b64645;padding-top: 12px;" class="tituloCantidad">Cantidad producto :</h4>' +
                                '</div>' +
                                '<div class="col-md-7">' +
                                '<div class="col-md-9 col-md-offset-3">' +
                                '<div class="form-group">' +
                                '<div class="center">' +
                                '<p></p>' +
                                '<div class="input-group">' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="minus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-minus"></span>' +
                                '</button>' +
                                '</span>' +
                                '<input type="number" name="quant[1]" class="form-control input-number" value="' + cantidadpedidoproducto + '" min="1" max="100" style="color:black;font-weight: bold;text-align:center;" disabled>' +
                                '<span class="input-group-btn">' +
                                '<button type="button" class="btn btn-primary btn-number btnflat" data-type="plus" data-field="quant[1]">' +
                                '<span class="glyphicon glyphicon-plus"></span>' +
                                '</button>' +
                                '</span>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '<br>' +
                                '</div>' +
                                '</div>' +
                                '<div class="col-md-12">' +
                                '<div class="form-group">' +
                                '<h4 style="color: #b64645;">Observación del pedido :</h4>' +
                                '<textarea class="form-control observacionProducto" rows="3" id="comment" style="resize: none;border-color: #b64645;" placeholder="Ingrese aquí la observación del pedido actual.">' + observacionpedidoproducto + '</textarea>' +
                                '</div>' +
                                '</div>' +
                                '</div>' +
                                '</div>'
                                );

                        funcionalidadCantidad();

                        pizzaTemporal.tipo = "Combinada 1/4";
                        pizzaTemporal.id = id;
                        pizzaTemporal.nombre = nombremenu;
                        pizzaTemporal.nombreSubmenu = nombreSubmenu;
                        pizzaTemporal.ingredientes = [];

                        pizzaTemporal.idCuarto = "";
                        pizzaTemporal.nombreCuarto = "";
                        pizzaTemporal.ingredientesCuarto = [];

                    });
                },
                error: function (error) {
                    console.log('Disculpe, existió un problema');
                    console.log(error);
                },
                complete: function (xhr, status) {
                    console.log('Petición realizada');
                }
            });
        } else
        if (elemento.val() == "personalizada") {
            $(".tituloEditaPizza").html("<center>Pizza " + nombreSubmenu + " - " + nombre + " Personalizada</center>");
            $.ajax({
                // Verificacion de los datos introducidos
                url: 'assets/hacerpedido/consultaPizzas.php',
                type: 'POST',
                data: {
                    nombreProducto: nombre,
                },
                dataType: "json",
                success: function (pizzas) {
                    var htmlselectPizzas1 = "<option value=''>Seleccione ..</option>";
                    var htmlselectPizzas2 = "<option value=''>Seleccione ..</option>";
                    var htmlselectPizzas3 = "<option value=''>Seleccione ..</option>";
                    $.when(
                            $(pizzas).each(function (index, value) {
                        if (nombreSubmenu != value.nombreSubmenu) {
                            if (submenupedidoproductocombinado1 == value.nombreSubmenu) {
                                htmlselectPizzas1 += "<option value='" + value.idProducto + "' selected>" + value.nombreSubmenu + "</option>";
                            } else {
                                htmlselectPizzas1 += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                            }
                        }
                    })
                            ).then(function () {
                        $.when(
                                $(pizzas).each(function (index, value) {
                            if (nombreSubmenu != value.nombreSubmenu) {
                                if (submenupedidoproductocombinado2 == value.nombreSubmenu) {
                                    htmlselectPizzas2 += "<option value='" + value.idProducto + "' selected>" + value.nombreSubmenu + "</option>";
                                } else {
                                    htmlselectPizzas2 += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                                }
                            }
                        })
                                ).then(function () {
                            $.when(
                                    $(pizzas).each(function (index, value) {
                                if (nombreSubmenu != value.nombreSubmenu) {
                                    if (submenupedidoproductocombinado3 == value.nombreSubmenu) {
                                        console.log(submenupedidoproductocombinado3);
                                        htmlselectPizzas3 += "<option value='" + value.idProducto + "' selected>" + value.nombreSubmenu + "</option>";
                                    } else {
                                        htmlselectPizzas3 += "<option value='" + value.idProducto + "'>" + value.nombreSubmenu + "</option>";
                                    }
                                }
                            })
                                    ).then(function () {


                                //do
                                $("#contentSeleccion").html(
                                        "<div class='grid'>" +
                                        "<div class='row'>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                        "<div class='row row-space' style='border: 1px solid; border-radius: 6px; border-color: #b64645;'>" +
                                        '<center>' +
                                        '<div class="btn-group" data-toggle="buttons" style="width:101%">' +
                                        '<label class="btn btn-primary" style="width: 50%;">' +
                                        '<input type="checkbox" class="inp_personalizado1" autocomplete="off"><div id="lblPersonalizado1">' + nombreSubmenu + '</div>' +
                                        ' </label>' +
                                        '<label class="btn btn-primary" style="width: 50%;">' +
                                        '<input type="checkbox" class="inp_personalizado2" autocomplete="off"><div id="lblPersonalizado2">' + submenupedidoproductocombinado1 + '</div>' +
                                        ' </label>' +
                                        "</div>" +
                                        '</center>' +
                                        "<div class='col-md-12 col-sm-12 col-xs-12' style='padding: 40px 0px;'>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                        "<div class='col-md-12' style='position: absolute;top:4px;left: 8px;'>" +
                                        "<img src='assets/img/pizzas/p_personalizado1.png' alt='pizza media' class='img-responsive imgPersonalizado1'>" +
                                        "</div>" +
                                        "<img src='assets/img/pizzas/fondopersonalizado.png' class='img-responsive'>" +
                                        "</div>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6' style='padding-bottom: 10px;'>" +
                                        "<div class='col-md-12' style='position: absolute;top:4px;right: 8px;'>" +
                                        "<img src='assets/img/pizzas/p_personalizado2.png' alt='pizza media' class='img-responsive imgPersonalizado2'>" +
                                        "</div>" +
                                        "<img src='assets/img/pizzas/fondopersonalizado.png' class='img-responsive'>" +
                                        "</div>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                        "<div class='col-md-12' style='position: absolute;bottom:4px;left: 8px;'>" +
                                        "<img src='assets/img/pizzas/p_personalizado3.png' alt='pizza media' class='img-responsive imgPersonalizado3'>" +
                                        "</div>" +
                                        "<img src='assets/img/pizzas/fondopersonalizado.png' class='img-responsive'>" +
                                        "</div>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                        "<div class='col-md-12' style='position: absolute;bottom:4px;right: 8px;'>" +
                                        "<img src='assets/img/pizzas/p_personalizado4.png' alt='pizza media' class='img-responsive imgPersonalizado4'>" +
                                        "</div>" +
                                        "<img src='assets/img/pizzas/fondopersonalizado.png' class='img-responsive'>" +
                                        "</div>" +
                                        "</div>" +
                                        '<center>' +
                                        '<div class="btn-group" data-toggle="buttons" style="width:101%">' +
                                        '<label class="btn btn-primary" style="width: 50%;">' +
                                        '<input type="checkbox" class="inp_personalizado3" autocomplete="off"><div id="lblPersonalizado3">' + submenupedidoproductocombinado2 + '</div>' +
                                        ' </label>' +
                                        '<label class="btn btn-primary" style="width: 50%;">' +
                                        '<input type="checkbox" class="inp_personalizado4" autocomplete="off"><div id="lblPersonalizado4">' + submenupedidoproductocombinado3 + '</div>' +
                                        ' </label>' +
                                        "</div>" +
                                        '</center>' +
                                        "</div>" +
                                        "</div>" +
                                        "<div class='col-md-6 col-sm-6 col-xs-6'>" +
                                        "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                        "<br>" +
                                        "<div class='form-group'>" +
                                        "<label for=''>Personalizada 1</label><br/>" +
                                        nombreSubmenu +
                                        "</div>" +
                                        "</div>" +
                                        "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                        "<br>" +
                                        "<div class='form-group'>" +
                                        "<label for=''>Personalizada 2</label><br/>" +
                                        "<select class='form-control selectPizzaPersonalizado2' >" +
                                        htmlselectPizzas1 +
                                        "</select>" +
                                        "</div>" +
                                        "</div>" +
                                        "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                        "<br>" +
                                        "<div class='form-group'>" +
                                        "<label for=''>Personalizada 3</label><br/>" +
                                        "<select class='form-control selectPizzaPersonalizado3' >" +
                                        htmlselectPizzas2 +
                                        "</select>" +
                                        "</div>" +
                                        "</div>" +
                                        "<div class='col-md-12 col-sm-12 col-xs-12'>" +
                                        "<br>" +
                                        "<div class='form-group'>" +
                                        "<label for=''>Personalizada 4</label><br/>" +
                                        "<select class='form-control selectPizzaPersonalizado4' >" +
                                        htmlselectPizzas3 +
                                        "</select>" +
                                        "</div>" +
                                        "</div>" +
                                        "</div>" +
                                        "</div>"
                                        );

                                $("#contentSeleccion").append(
                                        '<br><div class="row">' +
                                        '<div class="col-md-12">' +
                                        '<div class="col-md-5">' +
                                        '<h4 style="color: #b64645;padding-top: 12px;" class="tituloCantidad">Cantidad producto :</h4>' +
                                        '</div>' +
                                        '<div class="col-md-7">' +
                                        '<div class="col-md-9 col-md-offset-3">' +
                                        '<div class="form-group">' +
                                        '<div class="center">' +
                                        '<p></p>' +
                                        '<div class="input-group">' +
                                        '<span class="input-group-btn">' +
                                        '<button type="button" class="btn btn-primary btn-number btnflat" data-type="minus" data-field="quant[1]">' +
                                        '<span class="glyphicon glyphicon-minus"></span>' +
                                        '</button>' +
                                        '</span>' +
                                        '<input type="number" name="quant[1]" class="form-control input-number" value="' + cantidadpedidoproducto + '" min="1" max="100" style="color:black;font-weight: bold;text-align:center;" disabled>' +
                                        '<span class="input-group-btn">' +
                                        '<button type="button" class="btn btn-primary btn-number btnflat" data-type="plus" data-field="quant[1]">' +
                                        '<span class="glyphicon glyphicon-plus"></span>' +
                                        '</button>' +
                                        '</span>' +
                                        '</div>' +
                                        '</div>' +
                                        '</div>' +
                                        '<br>' +
                                        '</div>' +
                                        '</div>' +
                                        '<div class="col-md-12">' +
                                        '<div class="form-group">' +
                                        '<h4 style="color: #b64645;">Observación del pedido :</h4>' +
                                        '<textarea class="form-control observacionProducto" rows="3" id="comment" style="resize: none;border-color: #b64645;" placeholder="Ingrese aquí la observación del pedido actual.">' + observacionpedidoproducto + '</textarea>' +
                                        '</div>' +
                                        '</div>' +
                                        '</div>' +
                                        '</div>'
                                        );

                                funcionalidadCantidad();


                                pizzaTemporal.tipo = "Personalizada";

                                pizzaTemporal.ingredientes = [];
                                pizzaTemporal.id = id;
                                pizzaTemporal.nombre = nombremenu;
                                pizzaTemporal.nombreSubmenu = nombreSubmenu;
                                pizzaTemporal.ingredientes = [];

                                pizzaTemporal.idPizza2 = "";
                                pizzaTemporal.nombrePizza2 = "";
                                pizzaTemporal.ingredientesPizza2 = [];
                                pizzaTemporal.idPizza3 = "";
                                pizzaTemporal.nombrePizza3 = "";
                                pizzaTemporal.ingredientesPizza3 = [];
                                pizzaTemporal.idPizza4 = "";
                                pizzaTemporal.nombrePizza4 = "";
                                pizzaTemporal.ingredientesPizza4 = [];




                            });
                        });
                    });
                },
                error: function (error) {
                    console.log('Disculpe, existió un problema');
                    console.log(error);
                },
                complete: function (xhr, status) {
                    console.log('Petición realizada');
                }
            });
        }
    }

    $(".btnEnviaSeleccion").click(function () {
        var arrayProductos = [];

        var valorChecked = $(".radioPizzas input[type=radio]:checked").val();

        if (valorChecked == "entera") {
            arrayProductos.push({
                "idProducto": pizzaTemporal.id,
                "pizza": pizzaTemporal.pizza,
                "nombreProducto": pizzaTemporal.nombreSubmenu,
                "precioProducto": pizzaTemporal.precio,
                "nombreMenu": pizzaTemporal.nombre,
                "descripcionPedido": pizzaTemporal.tipo,
                ingredientes: pizzaTemporal.ingredientes,
                "cantidad": $(".input-number").val(),
                "observacion": $(".observacionProducto").val()
            });
        } else
        if (valorChecked == "medio") {
            arrayProductos.push({
                "idProducto": pizzaTemporal.id,
                "pizza": pizzaTemporal.pizza,
                "idProductoMedio": pizzaTemporal.idMedio,
                "nombreProducto": pizzaTemporal.nombreSubmenu,
                "nombreProductoMedio": pizzaTemporal.nombreMedio,
                "precioProducto": pizzaTemporal.precio,
                "nombreMenu": pizzaTemporal.nombre,
                "descripcionPedido": pizzaTemporal.tipo,
                ingredientes: pizzaTemporal.ingredientes,
                ingredientesMedio: pizzaTemporal.ingredientesMedio,
                "cantidad": $(".input-number").val(),
                "observacion": $(".observacionProducto").val()
            });
        } else
        if (valorChecked == "cuarto") {

            arrayProductos.push({
                "idProducto": pizzaTemporal.id,
                "pizza": pizzaTemporal.pizza,
                "idProductoCuarto": pizzaTemporal.idCuarto,
                "nombreProducto": pizzaTemporal.nombreSubmenu,
                "nombreProductoCuarto": pizzaTemporal.nombreCuarto,
                "precioProducto": pizzaTemporal.precio,
                "nombreMenu": pizzaTemporal.nombre,
                "descripcionPedido": pizzaTemporal.tipo,
                ingredientes: pizzaTemporal.ingredientes,
                ingredientesCuarto: pizzaTemporal.ingredientesCuarto,
                "cantidad": $(".input-number").val(),
                "observacion": $(".observacionProducto").val()
            });
        } else
        if (valorChecked == "personalizada") {

            arrayProductos.push({
                "idProducto": pizzaTemporal.id,
                "pizza": pizzaTemporal.pizza,
                "idProductoPersonalizado1": pizzaTemporal.idPizza2,
                "idProductoPersonalizado2": pizzaTemporal.idPizza3,
                "idProductoPersonalizado3": pizzaTemporal.idPizza4,
                "nombreProducto": pizzaTemporal.nombreSubmenu,
                "nombreProductoPersonalizado1": pizzaTemporal.nombrePizza2,
                "nombreProductoPersonalizado2": pizzaTemporal.nombrePizza3,
                "nombreProductoPersonalizado3": pizzaTemporal.nombrePizza4,
                "precioProducto": pizzaTemporal.precio,
                "nombreMenu": pizzaTemporal.nombre,
                "descripcionPedido": pizzaTemporal.tipo,
                ingredientes: pizzaTemporal.ingredientes,
                ingredientesPersonalizado1: pizzaTemporal.ingredientesPizza2,
                ingredientesPersonalizado2: pizzaTemporal.ingredientesPizza3,
                ingredientesPersonalizado3: pizzaTemporal.ingredientesPizza4,
                "cantidad": $(".input-number").val(),
                "observacion": $(".observacionProducto").val()
            });
        }

        $.ajax({
            // Verificacion de los datos introducidos
            url: 'assets/editarpedido/editarpedido.php',
            type: 'POST',
            data: {
                productos: arrayProductos,
                idpedido: idpedido,
                idpedidoproducto: idpedidoproducto,
                idpedidoproductocombinado1: idpedidoproductocombinado1,
                idpedidoproductocombinado2: idpedidoproductocombinado2,
                idpedidoproductocombinado3: idpedidoproductocombinado3
            },
            success: function (respuesta) {
                if (respuesta == "true") {
                    $("#ModalEditaPizza").modal("hide");
                    asignaPedido(idpedido);
                    $.notify("Pedido actualizado correctamente.", "success");
                }
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });


    });

    $(".btnEnviaProducto").click(function () {
        var arrayProductos = [];
        var Ingredientes = [];
        $.when(
                $(".rightIngrediente .contenedorIngrediente").each(function (index) {
            Ingredientes.push({
                idIngrediente: $(this).find(".idingrediente").html(),
                nombreIngrediente: $(this).find(".nombreingrediente").html()
            });
        })
                ).then(function () {
            arrayProductos.push({
                "idProducto": idproducto,
                "nombreProducto": nombrepedidoproducto,
                "nombreMenu": nombreMenu,
                "ingredientesProducto": Ingredientes,
                "cantidad": $(".input-number").val(),
                "observacion": $(".observacionProducto").val()
            });

            $.ajax({
                // Verificacion de los datos introducidos
                url: 'assets/editarpedido/editarpedido.php',
                type: 'POST',
                data: {
                    productos: arrayProductos,
                    idpedido: idpedido,
                    idpedidoproducto: idpedidoproducto
                },
                success: function (respuesta) {
                    if (respuesta == "true") {
                        $("#ModalEditaIngredientes").modal("hide");
                        asignaPedido(idpedido);
                        $.notify("Pedido actualizado correctamente.", "success");
                    }
                },
                error: function (error) {
                    console.log('Disculpe, existió un problema');
                    console.log(error);
                },
                complete: function (xhr, status) {
                    console.log('Petición realizada');
                }
            });



        });
    });

</script>