<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li>Mesas </li>
</ul>
<!-- FIN BREADCRUMB -->
<div class="page-title">      
    <div class="col-md-12 col-sm-12">
        <div class="col-md-4">
            <div class="widget widget-primary widget-item-icon">
                <div class="widget-item-right">
                    <a href="#" style="color: white;font-size: 50px;" class="btnNuevoPedido">
                        <span class="fa fa-plus-square"></span>
                    </a>
                </div>                             
                <div class="widget-data-left">
                    <div class="widget-int num-count">Nuevo Pedido</div>
                    <div class="widget-title">Para la mesa: <span class="mesaSelected">Seleccione</span> </div>
                    <div class="widget-subtitle"><button class="btn btn-info mostratMesasBtn"><i class="fas fa-eye"></i> Mostrar Mesas</button> </div>
                </div>                                     
            </div>
        </div>
        <div class="col-md-4 col-sm-4">
            <div class="widget widget-success widget-item-icon">
                <div class="widget-item-right">
                    <a href="#" style="color: white;font-size: 50px;" >
                        <i class="fas fa-check-circle"></i>
                    </a>
                </div>                             
                <div class="widget-data-left">
                    <div class="widget-int num-count mesas-disp"></div>
                    <div class="widget-title"> </div>
                    <div class="widget-subtitle">mesas disponibles</div>
                </div>                                     
            </div>  
        </div>
        <div class="col-md-4 col-sm-4">
            <div class="widget widget-info widget-item-icon">
                <div class="widget-item-right">
                    <a href="#" style="color: white;font-size: 50px;" >
                        <i class="fas fa-exclamation-circle"></i>
                    </a>
                </div>                             
                <div class="widget-data-left">
                    <div class="widget-int num-count mesas-ocu"></div>
                    <div class="widget-title"> </div>
                    <div class="widget-subtitle">mesas ocupadas</div>
                </div>                                     
            </div> 
        </div>
    </div>

    <div class="col-md-12 col-sm-12">
        <div class="panel panel-default tabs menuItemTabs">
            
        </div> 
    </div> 
</div>
<div class="col-md-12">
    <div class="panel panel-default">  
        <div id="autoscroll" class="panel-heading" >
            <div class="col-md-6 col-sm-6">
                <h2 style="text-align: left;"><span class="fas fa-edit"></span> Informai&oacute;n de las mesas</h2>
            </div>
        </div>
        <div class="panel-body" style="background-image: url('assets/img/resumenmesas.jpg');">
            <div class="col-md-12  contenedorPedido" style="padding: 30px;">

            </div>
        </div>      
    </div>
</div>
<div id="ModalEstadoPedido" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title tituloEstadoPedido" style="color:white;"></h4>
            </div>
            <div class="modal-body contenidoEstadoPedido">
            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-primary pedido_imprimir"><i class="fa fa-print" aria-hidden="true"></i> Imprimir</button>
                <button type="button" class="btn btn-primary btnAnadirPedido"><i class="fa fa-plus" aria-hidden="true"></i> Añadir Pedido</button>
                <button type="button" class="btn btn-primary"><i class="fas fa-stop-circle" aria-hidden="true"></i> Mesa habilitada</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>
<div class="modal fade modalCancelar" id="modal_small" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content ">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="smallModalHead" style="color:white;"><center>Cancelar pedido</center></h4>
            </div>
            <div class="modal-body contenidoCancelar">
            </div>
            <div class="modal-footer label-primary">
                <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>  
                    <button type="button" class="btn btn-primary confirmaCancelaPedido" style="border: 1px solid;"><i class="fa fa-times" aria-hidden="true"></i> Cancelar pedido</button>
                </center>
            </div>
        </div>
    </div>
</div>
<div id="ModalEditaIngredientes" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center><h4 class="modal-title tituloEditaIngredientes" style="color:white;"></h4></center>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 contenidoEditaIngredientes">
                    </div>
                </div>
            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Cerrar</button>
                <button type="button" class="btn btn-primary btnEnviaProducto" style="border: 1px solid;"><i class="fas fa-edit" aria-hidden="true"></i> Editar pedido</button>
            </div>
        </div>
    </div>
</div>
<div id="ModalEditaPizza" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title tituloEditaPizza" style="color:white;"></h4>
            </div>
            <div class="modal-body contenidoEditaPizza">
            </div>
            <div class="modal-body label-primary contentIngredientes" hidden>
            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Cerrar</button>
                <button type="button" class="btn btn-primary btnEnviaSeleccion" style="border: 1px solid;"><i class="fas fa-edit" aria-hidden="true"></i> Editar pedido</button>
            </div>
        </div>
    </div>
</div>


