<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li>Pedidos </li>
    <li>Editar Mesas </li>
</ul>
<!-- FIN BREADCRUMB -->
<div class="page-content-wrap">   
    <div class="row customalert hidethis">
        <div class="col-md-12">
            <div class="widget widget-primary widget-item-icon">
                <div class="widget-item-left">
                    <span class="fa fa-exclamation"></span>
                </div>
                <div class="widget-data">
                    <div class="widget-title">Notificación</div>
                    <div class="widget-subtitle">
                        <div role="alert" class="customalert_text">
                            Mensaje de error
                        </div>
                    </div>
                </div>
                <div class="widget-controls">                                
                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                </div>                             
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="col-md-6">
                        <h2><i class="fas fa-cogs"></i> Opciones</h2>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-4 addnewbtn">                        
                        <a href="#" class="tile tile-info tile-valign "><span class="fa fa-plus-square"></span></a>                        
                    </div> 
                    <div class="col-md-4 showlistbtn hidethis">                        
                        <a href="#" class="tile tile-info tile-valign "><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></a>                        
                    </div> 
                    <div class="col-md-4 newjob hidethis savenewjob">                        
                        <a href="#" class="tile tile-success tile-valign "><span class="fa fa-save"></span><img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;width: 100%;" /></a>                        
                    </div> 
                    <div class="col-md-4 editjob hidethis deletejob">                        
                        <a href="#" class="tile tile-danger tile-valign "><span class="fa fa-times"></span><img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;width: 100%;" /></a>                        
                    </div> 
                </div>
            </div>
        </div>
    </div>

    <?php //**VENTANA DE LISTADO DE TRABAJOS ?>
    <div class="row joblist">
        <!--PROYECTOS SE MUESTRNA DE MANERA DINAMICA-->
    </div>

    <?php //**VENTANA DE EDITAR PROYECTO ?>
    <div class="row editjob hidethis ">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="col-md-6">
                        <h2><span class="fa fa-edit"></span> Editar Mesa / Niveles</h2>
                    </div>
                    <div class="col-md-6">
                        <label class="switch pull-right editjobcheckbox">
                        </label>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <div class="row pushaway16">
                            <div class="col-md-6">
                                <h4>Número de mesa:</h4>
                                <input name="editcompanyJob" id="editcompanyJob" type="text" class="form-control" value="" placeholder="Ingresa el texto" />   
                            </div>
                            <div class="col-md-6">
                                <h4>Nivel / Ubicación:</h4>
                                <input name="edittitleJob" id="edittitleJob" type="text" class="form-control" value="" placeholder="Ingresa el texto" />   
                            </div>
                        </div>
                        <div class="hidethis_force" id="editidJobContainer"></div>
                        <div class="col-md-12 pushaway16">
                            <h4>Descripción:</h4>
                            <textarea name="editdescJob" id="editdescJob" type="text" class="form-control" rows="4" placeholder="Ingresa el texto" ></textarea>   
                        </div>
                        <div class="col-md-2 savechanges_btn pushtop_16 pull-right">                        
                            <a href="#" class="tile tile-success tile-valign ">
                                <span class="fa fa-save"></span>
                                <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;width: 100%;" />
                            </a>                        
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php //**VENTANA DE AGREGAR NUEVO PROYECTO ?>
    <div class="row newjob hidethis ">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2><span class="fa fa-edit"></span> Nueva Mesa</h2>
                </div>

                <div class="panel-body">
                    <div class="col-md-12">
                        <div class="row pushaway16">
                            <div class="col-md-6">
                                <h4>Número de mesa:</h4>
                                <input name="newcompanyJob" id="newcompanyJob" type="text" class="form-control" value="" placeholder="Ingresa el texto" />   
                            </div>
                            <div class="col-md-6">
                                <h4>Nivel / Ubicación:</h4>
                                <input name="newtitleJob" id="newtitleJob" type="text" class="form-control" value="" placeholder="Ingresa el texto" />   
                            </div>
                        </div>
                        <div class="col-md-12">
                            <h4>Descripción:</h4>
                            <textarea name="newdescJob" id="newdescJob" type="text" class="form-control" rows="4" placeholder="Ingresa el texto" ></textarea>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>