<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
 session_start();
 $nameMesa = $_SESSION['nameMesa'];
?>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".newpedido").addClass("active");
    getfullMenu();

    //      Seleccionar Mesa Para nuevo pedido  //
    $(document).on("click", ".menublockBtn", function () {
        $(".menublockBtn button").removeClass('selected');
        $(this).find('button').addClass('selected');
    });

    //      Ver grande  //
    $(document).on("click", ".expandItems", function () {
        $.when(
                $(".menublockBtn").removeClass('col-md-6'),
                $(".menublockBtn").addClass('col-md-12')
                ).then(function () {
            $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").show('slow');
            $(".getWidthTabs").css("width", "150px");
            $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '150px');
            $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
        });
    });

    //      Ver medio  //
    $(document).on("click", ".compItems", function () {
        $.when(
                $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").hide('slow')
                ).then(function () {
            $(".menublockBtn").removeClass('col-md-12');
            $(".menublockBtn").addClass('col-md-6');
            $(".getWidthTabs").css("width", "100px");
            $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '100px');
            $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
        });
    });

    //      Ver Editar Ingredientes  //
    var drake;
    $(document).on("click", ".editCurrentIngs", function () {
        event.preventDefault();
        var self, idProducto = $(this).find(".editIngIdProd").html();
        self = this;

        $.when($(document).find(".menuPanelContainer,.editCurrentIngs").velocity("transition.slideUpBigOut", 400))
                .then(function () {

                    var formData = new FormData();
                    formData.append('meth', 'getIngFullTable');
                    $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                        success: function (data) {
                            var htmlThisProd = '', htmlAllIngs = '',
                                    ingsThisProd = $('.ingsProductoCurrentView').html().split(','),
                                    thisIdMenuCurrent = $('.idMenuProductoCurrentView').html();
                            $.each(data.ings, function (i, n) {
                                if (ingsThisProd.includes(n.idIngrediente)) {
                                    htmlThisProd += '<div class="col-md-12 push5 handleThisIng currentIng">' +
                                            '   <button class="col-md-12 btn btn-info">' +
                                            '       <i class="fas fa-pepper-hot"></i>  ' + n.nombreIngrediente +
                                            '       <span class="hidethis handleThisIngIdIng">' + n.idIngrediente + '</span> ' +
                                            '       <span class="hidethis handleThisIngNombreIng">' + n.nombreIngrediente + '</span> ' +
                                            '   </button>' +
                                            '</div>'
                                }
                                if (n.tipoIngrediente == thisIdMenuCurrent) {
                                    htmlAllIngs += '<div class="col-md-12 push5 handleThisIng newIng">' +
                                            '   <button class="col-md-12 btn btn-success">' +
                                            '       <i class="fas fa-pepper-hot"></i>  ' + n.nombreIngrediente +
                                            '       <span class="hidethis handleThisIngIdIng">' + n.idIngrediente + '</span> ' +
                                            '       <span class="hidethis handleThisIngNombreIng">' + n.nombreIngrediente + '</span> ' +
                                            '   </button>' +
                                            '</div>'
                                }
                            });
                            $('.itemIngsBox').html(htmlThisProd);
                            $('.fullIngBox').html(htmlAllIngs);
                            console.log(data);
                        },
                        error: function (error) {
                            $(self).find("span, img").toggle("slow");
                            console.log("Hubo un error de internet, intente de nuevo");
                            console.log(error);
                        }
                    });

                    drake = dragula([document.querySelector('.itemIngsBox'), document.querySelector('.fullIngBox')], {
                        isContainer: function (el) {
                            return false; // only elements in drake.containers will be taken into account
                        },
                        moves: function (el, source, handle, sibling) {
                            return true; // elements are always draggable by default
                        },
                        accepts: function (el, target, source, sibling) {
                            return true; // elements can be dropped in any of the `containers` by default
                        },
                        invalid: function (el, handle) {
                            return false; // don't prevent any drags from initiating by default
                        },
                        direction: 'vertical', // Y axis is considered when determining where an element would be dropped
                        copy: false, // elements are moved by default, not copied
                        copySortSource: false, // elements in copy-source containers can be reordered
                        revertOnSpill: false, // spilling will put the element back where it was dragged from, if this is true
                        removeOnSpill: false, // spilling will `.remove` the element, if this is true
                        mirrorContainer: document.body, // set the element that gets mirror elements appended
                        ignoreInputTextSelection: true // allows users to select input text, see details below
                    });
                    dragula([document.querySelector('.itemIngsBox')], {
                        removeOnSpill: true, // spilling will `.remove` the element, if this is true
                        accepts: function (el, target, source, sibling) {
                            return false; // elements can be dropped in any of the `containers` by default
                        }
                    });
                    $(document).find(".ingsMenuPanelCont").velocity("transition.slideUpBigIn", 400);
                });
    });

    //      REGRESAR AL FULL MENU Y VACIAR CONTENEDORES DE INGREDINETES      //
    $(document).on("click", ".returntToMenu", function () {
        event.preventDefault();
        var self;
        self = this;

        $.when($(document).find(".ingsMenuPanelCont").velocity("transition.slideUpBigOut", 400))
                .then(function () {
                    drake.destroy();
                    $(document).find(".menuPanelContainer,.editCurrentIngs").velocity("transition.slideUpBigIn", 400);
                });
    });

    //      Modificamos los ingredientes de la Vista Actual      //
    $(document).on("click", ".editcurrentIngsList", function () {
        event.preventDefault();
        var self, htmlTagsIngs = '', ListNewIngs = '', newIngsArray, uniqueArr, Htmlnewings = '';
        self = this;

        $.when($(document).find(".ingsMenuPanelCont,.thisProdIngs").velocity("transition.slideUpBigOut", 800))
                .then(function () {
                    $.each($('.itemIngsBox .handleThisIng.currentIng'), function (i, n) {
                        htmlTagsIngs += '<li><a><i class="fas fa-pepper-hot"></i> ' + $(n).find('.handleThisIngNombreIng').html() + '</a></li>';
                        Htmlnewings += '<span class="label label-danger push5">+ ' + $(n).find('.handleThisIngNombreIng').html() + '</span> \n\ ';
                        ListNewIngs += $(n).find('.handleThisIngIdIng').html() + ',';
                    });
                    $.each($('.itemIngsBox .handleThisIng.newIng'), function (i, n) {
                        htmlTagsIngs += '<li><a class="greenTag"><i class="fas fa-pepper-hot"></i> ' + $(n).find('.handleThisIngNombreIng').html() + '</a></li>';
                        Htmlnewings += '<span class="label label-danger push5">+ ' + $(n).find('.handleThisIngNombreIng').html() + '</span> \n\ ';
                        ListNewIngs += $(n).find('.handleThisIngIdIng').html() + ',';
                    });
                    ListNewIngs = ListNewIngs.replace(/,\s*$/, "");
                    uniqueArr = uniqueArray(ListNewIngs.split(','));
                    $('.ingNamesProductoCurrentView').html(Htmlnewings);
                    $('.thisProdIngs').html(htmlTagsIngs);
                    $('.ingsProductoCurrentView').html(uniqueArr.join(','));
                    drake.destroy();
                    $(document).find(".menuPanelContainer,.editCurrentIngs,.thisProdIngs").velocity("transition.slideUpBigIn", 400);
                });
    });

    //      AGREGAMOS A LA LISTA ESTE PEDIDO  //
    $(document).on("click", ".addThisToList", function () {
        var self = this,
                idProducto = $(self).parent().parent().find('.idProdCurrentView').html(),
                nombProducto = $(self).parent().parent().find('.nombProdCurrentView').html(),
                ingNamesProducto = $(self).parent().parent().find('.ingNamesProductoCurrentView').html(),
                ingsProducto = $(self).parent().parent().find('.ingsProductoCurrentView').html(),
                precioProducto = $(self).parent().parent().find('.precProdCurrentView').html(),
                tamProducto = $('#tamProdsSelect').val(),
                varsProducto = $('#varsProdsSelect').val(),
                comProducto = $('#comentProdCurrent').val(),
                cantProducto = $('#cantProdCurrent').val(),
                htmlList = '',
                tamName = $('#tamProdsSelect').parent().find('.bootstrap-select button .filter-option').html(),
                currentTotal = $('.totalPedidoBtn span').html(),
                tamNameSolo = tamName.split('(');
        $.when($(document).find(".showProductPanelContainer,.listPanelCont").velocity("transition.slideUpBigOut", 400)).then(function () {
            htmlList += '<a href="#" class="list-group-item">' +
                    '       <div class="list-group-status status-online"></div>' +
                    '       <img src="api/assets/img/productos/' + idProducto + '.jpg" class="pull-left" alt="' + nombProducto + '"/>' +
                    '       <span class="contacts-title">' + nombProducto + '</span> <span class="label label-info push5">x ' + cantProducto + '</span>' +
                    '       ' + ingNamesProducto + '' +
                    '       <p>' + varsProducto + ' || ' + comProducto + ' </p>' +
                    '       <div class="list-group-controls">' +
                    '           <button class="btn btn-success">' + tamName + ' x ' + cantProducto + ' <i class="fas fa-money-bill-wave"></i>  ' + (+tamProducto * +cantProducto).toFixed(2) + ' $</button>' +
                    '           <button class="btn btn-danger deleteThisItemFromFullList"><span class="fa fa-times-circle"></span></button>' +
                    '       </div>' +
                    '       <div class="hidethis pedidoIdProd">' + idProducto + '</div>' +
                    '       <div class="hidethis pedidoPrecioTotalProd">' + (+tamProducto * +cantProducto).toFixed(2) + '</div>' +
                    '       <div class="hidethis pedidoCantProd">' + cantProducto + '</div>' +
                    '       <div class="hidethis pedidoComProd">' + varsProducto + ' || ' + comProducto + '</div>' +
                    '       <div class="hidethis pedidoTamProd">' + tamNameSolo[0] + '</div>' +
                    '       <div class="hidethis pedidoIngsProd">' + ingsProducto + '</div>' +
                    '   </a>';
            console.log(htmlList);
            currentTotal = (+currentTotal + (+tamProducto * +cantProducto)).toFixed(2);
            $('.totalPedidoBtn span').html(currentTotal);
            $('.listPanelContainer').append(htmlList);
            $(document).find('.listPanelCont').appendTo('.fullMenuContainer');
            $(document).find('.listPanelCont').velocity("transition.slideUpBigIn", 400);
            listhas = 1;
        });
    });

    //      CAMBIAMOS EL PRECIO DEPENDIENDO DEL TAMAñO      //
    $(document).on('change', "#tamProdsSelect", function (e) {
        $('.currentViewShowPrice').html($(this).val() + ' $');
    });

    //              VER EL LISTADO PARA PEDIR       //
    $(document).on("click", ".ShowThisList", function () {
        $.when($(document).find(".showProductPanelContainer,.listPanelCont").velocity("transition.slideUpBigOut", 400)).then(function () {
            $(document).find('.listPanelCont').appendTo('.fullMenuContainer');
            $(document).find('.listPanelCont,.ShowThisList').velocity("transition.slideUpBigIn", 400);
        });
    });

    //              VER EL LISTADO PARA PEDIR       //
    $(document).on("click", ".deleteThisItemFromFullList", function () {
        var self = this, currentTotal = $('.totalPedidoBtn span').html(), thisPrice = $(this).parent().parent().find('.pedidoPrecioTotalProd').html();
        $(this).parent().parent().velocity("transition.slideDownBigOut", 400);
        setTimeout(function () {
            $(self).parent().parent().remove()
        }, 400);
        currentTotal = (+currentTotal - thisPrice).toFixed(2);
        $(document).find('.totalPedidoBtn').velocity("transition.slideDownOut", 400);
        setTimeout(function () {
            $('.totalPedidoBtn span').html(currentTotal);
            $(document).find('.totalPedidoBtn').velocity("transition.slideUpIn", 100);
        }, 400);
        setTimeout(function () {
            if ($('.listPanelContainer').children().length == 0) {
                listhas = 0;
                $(document).find('.listPanelCont').velocity("transition.slideUpBigOut", 400);
            }
            console.log($('.listPanelContainer a').length);
        }, 1500);
    });

    //              Cargamos el Pedido a la DB       //
    $(document).on("click", ".cargarPedidoBtn", function (e) {
        var pedidos = [], formData = new FormData();
        $.each($('.listPanelContainer a'), function (i, n) {
            var pedido = {}
            pedido.idProducto = $(n).find('.pedidoIdProd').html();
            pedido.descripcionPedidoproducto = $(n).find('.pedidoTamProd').html();
            pedido.cantidadPedidoproducto = $(n).find('.pedidoCantProd').html();
            pedido.observacionPedidoproducto = $(n).find('.pedidoComProd').html();
            pedido.precioPedidoProducto = $(n).find('.pedidoPrecioTotalProd').html();
            pedido.ingsPedidoProducto = $(n).find('.pedidoIngsProd').html();
            pedidos.push(pedido);
        });
        pageLoadingFrame("show");
        console.log(pedidos);
        formData.append('meth', 'loadNewPedido');
        formData.append('pedidos', JSON.stringify(pedidos));
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                if (data.status == 'yes') {
                    window.location.href = "/?show=home";
                }
                console.log(data);
            },
            error: function (error) {
                pageLoadingFrame("hide");
                $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                $('#message-box-danger').toggle();
                console.log(error);
            }
        });
    });

    //              CARGAMOS TODOS LOS PRODUCTOS ACTIVOS DEL MENU       //
    function getfullMenu() {
        var formData = new FormData(),
                iii = 0;
        formData.append('meth', 'loadMenu');
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                if (data.status == 'yes') {
                    var htmlcontent = '<div class="col-md-6 menuPanelContainer hidethis">' +
                            '           <div class="panel panel-default nav-tabs-vertical menuPanel">' +
                            '               <div class="panel-heading">' +
                            '                   <h3 class="panel-title"> <i class="fas fa-list-alt"></i> &nbsp;&nbsp;Seleccione los productos <span class="btn btn-info"><?php echo $nameMesa;  ?></span </h3>' +
                            '                   <h3 class="panel-title pull-right"> <i class="fas fa-arrows-alt fa-2x expandItems" data-toggle="tooltip" data-placement="top" title="Expandir elementos"></i>&nbsp;&nbsp; <i class="fas fa-compress-arrows-alt fa-2x compItems" data-toggle="tooltip" data-placement="top" title="Contraer elementos"></i></h3>' +
                            '               </div>' +
                            '           <div class="tabs">' +
                            '               <ul class="nav nav-tabs getWidthTabs">';
                    var htmlcontentTabs = '<div class="panel-body tab-content">';
                    $.each(data.categ, function (i, n) {
                        if (iii == 0) {
                            htmlcontent += '<li class="active"><a href="#tab' + iii + '" data-toggle="tab" aria-expanded="true">' + n + '</a></li>';
                            htmlcontentTabs += '<div class="tab-pane active" id="tab' + iii + '">';
                            $.each(data.menu, function (ii, nn) {
                                if (nn.nombreMenu == n) {
                                    htmlcontentTabs += '<div class="col-md-12 menublockBtn">' +
                                            '               <button class="btn btn-danger btn-block" onclick="displayProduct(' + nn.idProducto + ', $(\'.fullMenuContainer\').get(0))">' +
                                            '                   <img src="api/assets/img/productos/' + nn.idProducto + '.jpg" class="menuitemImgSmall pull-left"><span class="nombreProducto">' + nn.nombreProducto + '</span> <span class="precioProducto  pull-right"><i class="fas fa-money-bill-alt"></i> ' + nn.precioProducto + '<i class="fas fa-dollar-sign"></i> </span> ' +
                                            '               </button>' +
                                            '           </div>';
                                }
                            });
                            htmlcontentTabs += '</div>';
                        } else {
                            htmlcontent += '<li><a href="#tab' + iii + '" data-toggle="tab" aria-expanded="true">' + n + '</a></li>';
                            htmlcontentTabs += '<div class="tab-pane" id="tab' + iii + '">';
                            $.each(data.menu, function (ii, nn) {
                                if (nn.nombreMenu == n) {
                                    htmlcontentTabs += '<div class="col-md-12 menublockBtn">' +
                                            '               <button class="btn btn-danger btn-block" onclick="displayProduct(' + nn.idProducto + ', $(\'.fullMenuContainer\').get(0))">' +
                                            '                   <img src="api/assets/img/productos/' + nn.idProducto + '.jpg" class="menuitemImgSmall pull-left"><span class="nombreProducto">' + nn.nombreProducto + '</span> <span class="precioProducto  pull-right"><i class="fas fa-money-bill-alt"></i> ' + nn.precioProducto + '<i class="fas fa-dollar-sign"></i> </span> ' +
                                            '               </button>' +
                                            '           </div>';
                                }
                            });
                            htmlcontentTabs += '</div>';
                        }
                        iii++;
                    });
                    htmlcontent += '</ul>';
                    htmlcontentTabs += '</div>';
                    $(".fullMenuContainer").append(htmlcontent + htmlcontentTabs);
                    $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
                    $.when(
                            $(document).find(".menuPanelContainer").delay(500).velocity("transition.slideUpBigIn", 300)
                            ).then(function () {
                        $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").hide('slow');
                        $(".menublockBtn").removeClass('col-md-12');
                        $(".menublockBtn").addClass('col-md-6');
                        $(".getWidthTabs").css("width", "100px");
                        $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '100px');
                        $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
                    });
                }
                console.log(data);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //              OBTENEMOS LOS VALORES UNICOS DE UN ARRAY            ////
    function uniqueArray(arr) {
        var a = [];
        for (var i = 0, l = arr.length; i < l; i++)
            if (a.indexOf(arr[i]) === -1 && arr[i] !== '')
                a.push(arr[i]);
        return a;
    }
</script>