<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".newpedido").addClass("active");

    //      Seleccionar Mesa Para nuevo pedido  //
    $(document).on("click", ".menublockBtn", function () {
        $(".menublockBtn button").removeClass('selected');
        $(this).find('button').addClass('selected');
    });

    //      Ver grande  //
    $(document).on("click", ".expandItems", function () {
        $.when(
                $(".menublockBtn").removeClass('col-md-6'),
                $(".menublockBtn").addClass('col-md-12')
                ).then(function () {
            $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").show('slow');
            $(".getWidthTabs").css("width", "150px");
            $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '150px');
            $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
        });
    });

    //      Ver medio  //
    $(document).on("click", ".compItems", function () {
        $.when(
                $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").hide('slow')
                ).then(function () {
            $(".menublockBtn").removeClass('col-md-12');
            $(".menublockBtn").addClass('col-md-6');
            $(".getWidthTabs").css("width", "100px");
            $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '100px');
            $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
        });
    });

    getfullMenu();
    //              CARGAMOS TODOS LOS PRODUCTOS ACTIVOS DEL MENU       //
    function getfullMenu() {
        var formData = new FormData(),
                iii = 0;
        formData.append('meth', 'loadMenu');
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                if (data.status == 'yes') {
                    var htmlcontent = '<div class="col-md-6 menuPanelContainer hidethis">' +
                            '           <div class="panel panel-default nav-tabs-vertical menuPanel">' +
                            '               <div class="panel-heading">' +
                            '                   <h3 class="panel-title"> <i class="fas fa-list-alt"></i> &nbsp;&nbsp;Seleccione los pedidos del menu </h3>' +
                            '                   <h3 class="panel-title pull-right"> <i class="fas fa-arrows-alt fa-2x expandItems"></i>&nbsp;&nbsp; <i class="fas fa-compress-arrows-alt fa-2x compItems"></i></h3>' +
                            '               </div>' +
                            '           <div class="tabs">' +
                            '               <ul class="nav nav-tabs getWidthTabs">';
                    var htmlcontentTabs = '<div class="panel-body tab-content">';
                    $.each(data.categ, function (i, n) {
                        if (iii == 0) {
                            htmlcontent += '<li class="active"><a href="#tab' + iii + '" data-toggle="tab" aria-expanded="true">' + n + '</a></li>';
                            htmlcontentTabs += '<div class="tab-pane active" id="tab' + iii + '">';
                            $.each(data.menu, function (ii, nn) {
                                if (nn.nombreMenu == n) {
                                    htmlcontentTabs += '<div class="col-md-12 menublockBtn">' +
                                            '               <button class="btn btn-danger btn-block" onclick="displayProduct(' + nn.idProducto + ')">' +
                                            '                   <img src="api/assets/img/productos/default.jpg" class="menuitemImgSmall pull-left"><span class="nombreProducto">' + nn.nombreProducto + '</span> <span class="precioProducto  pull-right"><i class="fas fa-money-bill-alt"></i> ' + nn.precioProducto + '<i class="fas fa-dollar-sign"></i> </span> ' +
                                            '               </button>' +
                                            '           </div>';
                                }
                            });
                            htmlcontentTabs += '</div>';
                        } else {
                            htmlcontent += '<li><a href="#tab' + iii + '" data-toggle="tab" aria-expanded="true">' + n + '</a></li>';
                            htmlcontentTabs += '<div class="tab-pane" id="tab' + iii + '">';
                            $.each(data.menu, function (ii, nn) {
                                if (nn.nombreMenu == n) {
                                    htmlcontentTabs += '<div class="col-md-12 menublockBtn">' +
                                            '               <button class="btn btn-danger btn-block" onclick="displayProduct(' + nn.idProducto + ')">' +
                                            '                   <img src="api/assets/img/productos/default.jpg" class="menuitemImgSmall pull-left"><span class="nombreProducto">' + nn.nombreProducto + '</span> <span class="precioProducto  pull-right"><i class="fas fa-money-bill-alt"></i> ' + nn.precioProducto + '<i class="fas fa-dollar-sign"></i> </span> ' +
                                            '               </button>' +
                                            '           </div>';
                                }
                            });
                            htmlcontentTabs += '</div>';
                        }
                        iii++;
                    });
                    htmlcontent += '</ul>';
                    htmlcontentTabs += '</div>';
                    $(".fullMenuContainer").append(htmlcontent + htmlcontentTabs);
                    $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
                    $.when(
                            $(document).find(".menuPanelContainer").delay(500).velocity("transition.slideUpBigIn", 300)
                            ).then(function () {
                        $(".menublockBtn .menuitemImgSmall,.menublockBtn .precioProducto").hide('slow');
                        $(".menublockBtn").removeClass('col-md-12');
                        $(".menublockBtn").addClass('col-md-6');
                        $(".getWidthTabs").css("width", "100px");
                        $(".menuPanel .tabs .panel-body.tab-content").css("margin-left", '100px');
                        $(".menuPanel .tabs").css("min-height", $('.getWidthTabs').height());
                    });
                } else {

                }
                console.log(data);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    //              DESPLEGAMOS LAS CARACTERISTICAS DEL PRODUCTO SELECCIONADO           //
    function displayProduct(idProduct) {
        var formData = new FormData();
        formData.append('id', idProduct);
        formData.append('meth', 'loadProdutSpecs');
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                console.log(data);
                var htmlcontent = '<div class="col-md-3 showProductPanelContainer hidethis">' +
                        '           <div class="panel panel-default showProductPanel">' +
                        '             <div class="panel-body profile itemMenuBg">' +
                        '                   <div class="profile-image">' +
                        '                       <img src="api/assets/img/productos/' + data.producto.idProducto + '.jpg"/>' +
                        '                   </div>' +
                        '                   <div class="profile-data">' +
                        '                       <div class="profile-data-name">' + data.producto.nombreProducto + '</div>' +
                        '                       <div class="profile-data-title" style="color: #FFF;">' + data.producto.nombreMenu + '</div>' +
                        '                   </div>' +
                        '               </div>' +
                        '               <div class="panel-body redbg">' +
                        '                   <div class="row">' +
                        '                       <ul class="list-tags">';
                $.each(data.ings, function (ii, nn) {
                    htmlcontent += '<li><a><i class="fas fa-pepper-hot"></i> ' + nn.nombreIngrediente + '</a></li>';
                });
                htmlcontent += '        </ul>' +
                        '                   <ul class="list-tags">' +
                        '                       <li class="pull-right"><button class="btn btn-info"><i class="fas fa-pencil-alt"></i> Modificar</button></li>' +
                        '                   </ul>' +
                        '               </div>' +
                        '           </div>' +
                        '           <div class="panel-body list-group border-bottom">   ' +
                        '               <a  class="list-group-item active"> ' + data.producto.descProducto + '</a>' +
                        '               <a  class="list-group-item  fontx1-5"><span class="fas fa-money-bill-wave"></span> <span class="pull-right"> ' + data.producto.precioProducto + ' $</span></a>' +
                        '           </div>' +
                        '           <div class="panel-body">' +
                        '               <div class="form-group">' +
                        '                   <select class="form-control select" data-style="btn-primary">' +
                        '                       <option>Tamaño</option>' +
                        '                       <option>Personal</option>' +
                        '                       <option>Mediana</option>' +
                        '                       <option>Familiar</option>' +
                        '                   </select>' +
                        '               </div>' +
                        '           </div>' +
                        '           <div class="panel-body"> ' +
                        '               <div class="form-group">   ' +
                        '                   <select class="form-control select" data-style="btn-info">';
                var vars = data.producto.varsProducto.split(',');
                $.each(vars, function (ii, nn) {
                    htmlcontent += '<option>' + nn + '</option>';
                });
                htmlcontent += '</select>' +
                        '            </div>   ' +
                        '        </div>' +
                        '        <div class="panel-body">    ' +
                        '            <div class="col-md-12">' +
                        '                <h4 class="pull-left">Comentarios:</h4>' +
                        '                <textarea type="text" class="form-control" rows="3" placeholder="Ingresa el texto"></textarea>   ' +
                        '            </div>  ' +
                        '        </div>' +
                        '        <div class="panel-body">   ' +
                        '            <button class="btn btn-success"><i class="fas fa-plus"></i> AGREGAR</button>' +
                        '        </div>' +
                        '    </div>   ' +
                        '</div>';
                $.when(
                        $(document).find(".showProductPanelContainer").velocity("transition.slideUpBigOut", 400)
                        ).then(function () {
                    $(".showProductPanelContainer").remove();
                    $(".fullMenuContainer").append(htmlcontent);
                    $(document).find(".showProductPanelContainer").delay(500).velocity("transition.slideUpBigIn", 400);
                    $('select').selectpicker('refresh');
                });
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }
</script>