<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
 session_start();
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li id="changeCrumbs">Nuevo Pedido </li>
</ul>
<!-- FIN BREADCRUMB -->
<div class="page-content-wrap">    
    <div class="col-md-12 fullMenuContainer">
        <div class="col-md-6 ingsMenuPanelCont hidethis">
            <div class="panel panel-default">
                <div class="panel panel-heading">
                    <h3 class="panel-title"> <i class="fas fa-edit"></i> &nbsp;&nbsp; Editar Los Ingredientes</h3>
                    <button class="btn btn-danger returntToMenu pull-right"><i class="fas fa-backward"></i> Regresar</button>
                </div>
                <div class="panel panel-body">
                    <div class="col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"> <i class="fas fa-check"></i> &nbsp;&nbsp; Actuales</h3>
                                <button class="btn btn-success editcurrentIngsList pull-right"><i class="fas fa-save"></i></button>
                            </div>
                            <div class="panel-body">
                                <div class="itemIngsBox col-md-12">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"> <i class="fas fa-list"></i> &nbsp;&nbsp; Disponibles</h3>
                            </div>
                            <div class="panel-body">
                                <div class="fullIngBox col-md-12">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
    <div class=" col-md-3 hidethis listPanelCont">
        <div class="panel panel-default listPanel">
            <div class="panel-heading">
                <h2 class="panel-title"><i class="fas fa-check"></i> Valide su pedido</h2>
                <button class="btn btn-info pull-right"><?php echo $_SESSION["nameMesa"] ?></button>
            </div>
            <div class="panel-body list-group list-group-contacts listPanelContainer">    

            </div>
            <div class="panel-footer">
                <button class="btn btn-info totalPedidoBtn pull-left"> Total: <i class="fas fa-money-check-alt"></i> <span>0</span> $</button>
                <button class="btn btn-success cargarPedidoBtn pull-right"><i class="fas fa-upload"></i> Cargar Pedido </button>
            </div>
        </div>
    </div>
</div>

<!--MODAL ERROR -->
<div class="message-box message-box-danger animated fadeIn" id="message-box-danger">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span> error</div>
            <div class="mb-content">
                <p class="errormessage_mb"></p>
            </div>
            <div class="mb-footer">
            </div>
        </div>
    </div>
</div>