<?php

/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */


//  DEBUG EN PANTALLA   //
//error_reporting(E_ALL);
//ini_set('display_errors', 1);

/*  HABILITAMOS EL ACCESO PUBLICO PARA REALIZAR LLAMADAS AJAX DESDE DOMINIOS PUBLICOS   // */
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Auth-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS');

header('Content-type: application/javascript; charset=utf-8');

//   ES IMPORTANTE RESCATAR TODO EL OUTPUT  //
/*
 * LUEGO PODEMOS PROMPTEARLO EN PANTALLA CON
 * $output = ob_get_contents(); ob_end_clean();
 */
ob_start();

//   INCLUDES   //
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'assets/plugins/PHPMailer/src/Exception.php';
require 'assets/plugins/PHPMailer/src/PHPMailer.php';
require 'assets/plugins/PHPMailer/src/SMTP.php';
require_once 'assets/scripts/funcs.php';

//   Creamos el enlace con la DB    //
require("../assets/scripts/database.php");

// INICIAMOS //
date_default_timezone_set('America/Guayaquil');
$json = array();
if ($_POST) {
    $method = broom('reg', $_POST['meth']);

    //          USUARIO INICIA SESION           //
    if ($method == 'login') {


        $username = broom('reg', $_POST["username"]);
        $password = $_POST["password"];

        //        $username = filter_var($_POST['username'], FILTER_VALIDATE_EMAIL);
        //        $password = hash('sha512', $_POST['password']);
        //        
        ////            CONSULTAMOS EL USUARIO EN LA BASE DE DATOS A VER SI EXISTE              ////
        $query = " SELECT * FROM usuario us "
                . " INNER JOIN perfil p ON (us.idPerfil = p.idPerfil ) "
                . " INNER JOIN establecimiento e ON (us.idEstablecimiento = e.idEstablecimiento ) "
                . " WHERE nombreUsuario like '$username' ";
        $result = $conn->query($query);
        if (!$result) {
            $json['scriptResp'] = "userqueryFail";
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        $rows = $result->num_rows;
        $row = $result->fetch_array(MYSQLI_ASSOC);

        ////          RETORNAMOS UN JSON AL AJAX PARA ALIMENTAR EL JAVASCRIPT          ////
        $json['userIntel'] = $row;

        if (($rows != 0) && (strcmp($row["nombreUsuario"], $username) == 0) && ($row['passwordUsuario'] === $password)) {

            //   VERIFICAMOS SI TIENE IMAGEN CARGADA || CARGAMOS IMAGEN PREDETERMINADA        //
            $isavatar = "assets/img/users/" . $row["idUsuario"] . ".jpg";
            if (file_exists($isavatar)) {
                $json['userIntel']['userImg'] = "api/" . $isavatar;
            } else {
                $isavatar2 = "assets/img/users/" . $row["idUsuario"] . ".png";
                if (file_exists($isavatar2)) {
                    $json['userIntel']['userImg'] = "api/" . $isavatar2;
                } else {
                    $json['userIntel']['userImg'] = "api/assets/img/users/default.jpg";
                }
            }

            ////             ENVIAMOS DATOS POR $_SESSION;          /////
            session_start();
            $_SESSION["usuario"] = $json['userIntel'];

            $val_update = "UPDATE usuario SET lastLogin = '" . date('Y-m-d H:i:s') . "' WHERE idUsuario = '" . $row["idUsuario"] . "';";
            $val_result = $conn->query($val_update) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $val_update . "'}");

            $json['userIntel'] = $_SESSION["usuario"];
            $json['scriptResp'] = "match";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "noMatch";
            $json['passw'] = $_POST['password'];
            $json['passwo'] = $password;
            $json['password'] = $row['passUsuario'];
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          ASIGNAMOS LAS MESAS AL NUEVO EPDIDO             //
    if ($method == 'asignaMesa') {
        $idMesa = broom('num', $_POST['idmesa']);
        $numeroMesa = broom('text', $_POST['numeromesa']);
        session_start();
        if (isset($_POST["idpedido"])) {
            $idPedido = broom('num', $_POST['idpedido']);
            $_SESSION["idpedido"] = $idPedido;
            $_SESSION["idmesa"] = $idMesa;
            $_SESSION["nameMesa"] = $numeroMesa;
            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            $json['ses'] = $_SESSION;
            echo json_encode($json);
            return;
        } else {
            $_SESSION["idpedido"] = '';
            $_SESSION["idmesa"] = $idMesa;
            $_SESSION["nameMesa"] = $numeroMesa;
            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            $json['ses'] = $_SESSION;
            $json['post'] = $_POST;
            echo json_encode($json);
            return;
        }
    }

    //          CONSULTAMOS LOS PEDIDOS EXISTENTES            //
    if ($method == 'consultaPedidos') {

        session_start();
        $idEstablecimiento = $_SESSION['usuario']['idEstablecimiento'];

        $query = "SELECT * FROM pedido pe "
                . "INNER JOIN mesa m on(m.idMesa=pe.idMesa) "
                . "INNER JOIN pedidoproducto pp ON(pe.idPedido = pp.idPedido) "
                . "INNER JOIN productos p on(p.idProducto = pp.idProducto) "
                . "INNER JOIN menu me on (p.idMenu = me.idMenu) "
                . "GROUP BY(pe.idPedido) "
                . "HAVING m.estadoMesa = 'OCUPADA' AND pe.estadopagoPedido != 'PAGADO' AND m.idEstablecimiento = '$idEstablecimiento' "
                . "ORDER BY pe.idPedido ASC";

        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $pedidos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $pedidos[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        $json['pedidos'] = $pedidos;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          VERIFICAMOS LAS MESAS DISPONIBLES           //
    if ($method == 'mesas') {

        session_start();
        $idEstablecimiento = $_SESSION['usuario']['idEstablecimiento'];

        //          LLAMAMOS TODAS LAS MESAS DISPONIBLES PARA ESE ESTABLECIMIENTO           //
        $query = "SELECT * FROM mesa WHERE idEstablecimiento = '$idEstablecimiento' AND estadoMesa = 'HABILITADA' ORDER BY CAST(numeroMesa as SIGNED INTEGER) ASC";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $row = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $row['database'][] = $result->fetch_array(MYSQLI_ASSOC);
            $temp = end($row['database']);
            $row['keys'][] = $temp['nivelMesa'];
        }
        $json['mesas'] = $row['database'];
        $json['niveles'] = array_unique($row['keys']);

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          MOSTRAMOS LOS PRODUCTOS DLE PEDIDO CLICKEADO           //
    if ($method == 'consultaProductos') {

        $idpedido = $_POST["idpedido"];

        $query = "SELECT * FROM pedidoproducto pp "
                . "INNER JOIN productos p ON (p.idProducto = pp.idProducto) "
                . "INNER JOIN menu m ON (p.idMenu = m.idMenu) "
                . "WHERE pp.idPedido= '$idpedido'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $productos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $productos[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        $htmlPedido = "";

        foreach ($productos as $producto) {
            if ($producto["estadoPedidoproducto"] == "SOLICITADO") {
                $estado = "info";
                $icon = '<i class="fa fa-asterisk fa-2x" style="font-size:25px;color:white;" aria-hidden="true"></i>';
                $btns = "<button class=\"btn btn-primary push5 cancelarPedido\" style=\"border: 1px solid;\"><i class='fa fa-times' aria-hidden='true'></i> Cancelar pedido</button>";
            }
            if ($producto["estadoPedidoproducto"] == "EN PROCESO") {
                $estado = "warning";
                $icon = '<i class="fas fa-sync-alt fa-spin fa-2x fa-fw" style="font-size:25px;color:white;"></i>';
                $btns = "";
            }
            if ($producto["estadoPedidoproducto"] == "LISTO PARA ENTREGAR") {
                $estado = "success";
                $icon = '<i class="fa fa-check" style="font-size:25px;color:white;" aria-hidden="true"></i>';
                $btns = "<button class=\"btn btn-primary push5 pedidoEntregado\" style=\"border: 1px solid;\"><i class='fas fa-vote-yea' aria-hidden='true'></i> Entregar</button>";
            }
            if ($producto["estadoPedidoproducto"] == "ENTREGADO") {
                $estado = "default";
                $icon = '<i class="fas fa-vote-yea" aria-hidden="true" style="font-size:25px;color:black;"></i>';
                $btns = "";
            }

            $htmlPedido .= '  
            <div class="list-group-item btn-' . $estado . ' pedidoSingleModal">
                <p style="font-size:25px;">' . $producto["nombreProducto"] . '</p>
                <p style="font-size:15px;font-weight:bold;">' . $producto["descripcionPedidoproducto"] . ' </p>
                <p style="position:absolute;top:12px;right:10px;">' . $icon . '</p>
                <div style="text-align: -webkit-right;">
                    <h3>Cantidad : <small style="font-size: 20px;color: black;font-weight: bold;">' . $producto["cantidadPedidoproducto"] . '</small></h3>
                    <h3>Observaciones : <small style="font-size: 20px;color: black;font-weight: bold;">' . $producto["observacionPedidoproducto"] . '</small></h3>
                </div>
                <div class="list-group-controls" style="text-align:center;">
                    ' . $btns . '
                </div>';

            $htmlPedido .= '<div style="display:none;" class="idproducto">' . $producto["idProducto"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="idmenu">' . $producto["idMenu"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="idpedido">' . $producto["idPedido"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="idpedidoproducto">' . $producto["idPedidoproducto"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="nombrepedidoproducto">' . $producto["nombreProducto"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="menupedidoproducto">' . $producto["nombreMenu"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="descripcionpedidoproducto">' . $producto["descripcionPedidoproducto"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="observacionpedidoproducto">' . $producto["observacionPedidoproducto"] . '</div>';
            $htmlPedido .= '<div style="display:none;" class="cantidadpedidoproducto">' . $producto["cantidadPedidoproducto"] . '</div>';
            $htmlPedido .= '</div>';
        }
        echo $htmlPedido;

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          CANCELAMOS EL PEDIDO SELECCIONADO           //
    if ($method == 'cancelaPedido') {

        $idpedidoproducto = $_POST["idpedidoproducto"];
        $descripcionpedidoproducto = $_POST["descripcionpedidoproducto"];
        $menupedidoproducto = $_POST["menupedidoproducto"];
        $numeromesa = $_POST["numeromesa"];
        $idpedido = $_POST["idpedido"];

        $query = "DELETE FROM pedidoproducto WHERE idPedidoproducto = '$idpedidoproducto'";
        $res = $conn->query($query);
        if (!$res)
            die($conn->error);

        $query = "SELECT * from pedidoproducto WHERE idPedido = '$idpedido'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;

        if ($rows == 0) {

            //ELIMINACION DEL PEDIDO PRODUCTO
            $query = "DELETE FROM pedido WHERE idPedido = '$idpedido'";
            $res = $conn->query($query);

            if (!$res) {
                echo $res = 'Error al ingresar. ' . $conn->error;
            }

            //HABILITACION DE LA MESA
            $query = "UPDATE `mesa` SET `estadoMesa`= 'HABILITADA' WHERE numeroMesa = '$numeromesa'";
            $res = $conn->query($query);

            if (!$res) {
                echo $res = 'Error al ingresar. ' . $conn->error;
            }
        }

        echo $rows;

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          Consultamos los ingredinetes de un Pedido           //
    if ($method == 'consultaIngredientesE') {
        $idproducto = $_POST["idproducto"];
        $query = "SELECT * FROM ingrediente i "
                . " JOIN productoingrediente ip ON (i.idIngrediente = ip.idIngrediente) "
                . " WHERE ip.idProducto like '$idproducto' "
                . " ORDER BY nombreIngrediente ASC";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $ingredientes = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $ingredientes[] = $result->fetch_array(MYSQLI_ASSOC);
        }
        if ($rows != 0) {
            $json['ing'] = $ingredientes;
            $output = ob_get_contents();
            ob_end_clean();
            $json['status'] = 'yes';
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['result'] = '';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          Consultamos los ingredinetes Generales para esa categoria           //
    if ($method == 'consultaIngredientesG') {

        $tipoIngrediente = $_POST["tipoIngrediente"];
        if ($tipoIngrediente == "Crepes y Postres") {
            $query = "SELECT * FROM ingrediente where tipoIngrediente = '$tipoIngrediente' order by nombreIngrediente ASC";
        } else {
            $query = "SELECT * FROM ingrediente where tipoIngrediente = 'General' or tipoIngrediente = '$tipoIngrediente' order by nombreIngrediente ASC";
        }
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $ingredientes = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $ingredientes[] = $result->fetch_array(MYSQLI_ASSOC);
        }
        if ($rows != 0) {
            $json['ings'] = $ingredientes;
            $output = ob_get_contents();
            ob_end_clean();
            $json['status'] = 'yes';
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['result'] = '';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  CARGAMOS LOS PEDIDOS DEL MENU        //
    if ($method == 'loadMenu') {

        $query = "SELECT * FROM productos pro "
                . "INNER JOIN menu me ON (pro.idMenu = me.idMenu) "
                . "WHERE pro.estadoProducto = 'ACTIVO' "
                . "AND me.estadoMenu = 'ACTIVO'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $menu = array();
        $categs = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $menu[] = $result->fetch_array(MYSQLI_ASSOC);
            $last = end($menu);
            $categs[] = $last['nombreMenu'];
        }

        if ($rows != 0) {
            $json['menu'] = $menu;
            $json['categ'] = array_unique($categs);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        }
        return;
    }

    //                  CARGAMOS LOS DATOS DEL PRODUCTO        //
    if ($method == 'loadProdutSpecs') {

        $idProducto = $_POST['id'];
        $query = "SELECT * FROM productos pro "
                . "INNER JOIN menu me ON (pro.idMenu = me.idMenu) "
                . "WHERE pro.idProducto = '$idProducto' ";
        $result = $conn->query($query);
        if (!$result)
            die(json_encode($query));
        $product = $result->fetch_array(MYSQLI_ASSOC);

        $ings = $product['ingsProducto'];
        $query2 = "SELECT * FROM ingrediente ing WHERE ing.idIngrediente IN ($ings) ";
        $result2 = $conn->query($query2);
        if (!$result2)
            die(json_encode($query2));
        $rows = $result2->num_rows;
        $allIngs = array();
        for ($i = 0; $i < $rows; $i++) {
            $result2->data_seek($i);
            $allIngs[] = $result2->fetch_array(MYSQLI_ASSOC);
        }

        if ($rows != 0) {
            $json['producto'] = $product;
            $json['ings'] = $allIngs;
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        }
        return;
    }

    //                  NUEVA IMAGEN DE USUARIO       //
    if ($method == 'imagenNueva') {
        session_start();
        $data = $_POST["imagenNueva"];
        $target_dir = "assets/img/users/";
        file_put_contents($target_dir . $_SESSION["usuario"]["idUsuario"] . '.jpg', base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $data)));
        $_SESSION["usuario"]['userImg'] = 'api/' . $target_dir . $_SESSION["usuario"]["idUsuario"] . '.jpg';
        echo true;
        return;
    }

    //                  NUEVA PASS POR EL USUARIO     //
    if ($method == 'submitnewpass') {
        session_start();
        $user = $_SESSION["usuario"]["nombreUsuario"];
        $query = "SELECT passwordUsuario FROM usuario WHERE nombreUsuario = '" . $user . "'";
        $result = $conn->query($query);
        if (!$result)
            die(json_encode($query));
        $row_compare = $result->fetch_array(MYSQLI_ASSOC);
        $compare = $row_compare[0];
        if ($_POST["oldpass"] == $compare) {
            $update_pass = mysqli_query($conn, "UPDATE usuario SET passwordUsuario = '" . $_POST['newpass'] . "' WHERE nombreUsuario = '" . $user . "'");
            $msg_pass .= " Contraseña cambiada con éxito. ";
            $box = "primary";
        } else {
            $msg_pass .= " No pudimos validar su contraseña anterior, por favor ingresela nuevamente. ";
            $box = "danger";
        }

        $_SESSION['msg'] = $msg_pass;
        $_SESSION['box'] = $box;
        echo true;
        return;
    }

    //                  OBTENEMOS LAS MESAS     //
    if ($method == 'getMesasNiveles') {
        $query = "SELECT * FROM mesa WHERE idEstablecimiento = '1'";
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            if ($row['numeroMesa'] == '999') {
                continue;
            }
            if ($row['estadoMesa'] == 'HABILITADA') {
                $checked = 'checked="checked"';
            } else {
                $checked = '';
            }
            echo ' 
                <div class="col-md-3 hidethis mesaItemBlock">   
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><span>' . $row['numeroMesa'] . '</span></h3>   
                            <ul class="panel-controls">
                                <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                            </ul>       
                            <label class="switch pull-right">
                                <input type="checkbox" class="switch disabledswitch" name="1_check"  value="1" ' . $checked . ' />
                                <span></span>
                            </label>                            
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="col-md-6 control-label">Descripcion:</label>
                                <div class="col-md-6">
                                    <span class="label label-primary label-form titleJob_container">&nbsp;' . $row['textoMesa'] . '</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6 control-label">Nivel / Ubicación:</label>
                                <div class="col-md-6">
                                    <span class="label label-primary label-form titleJob_container">&nbsp;' . $row['nivelMesa'] . '</span>
                                </div>
                            </div>
                            <div class="hidethis_force idMesaCont">' . $row['idMesa'] . '</div>
                            <div class="hidethis_force textoMesaCont">' . $row['textoMesa'] . '</div>
                            <div class="hidethis_force nivelMesaCont">' . $row['nivelMesa'] . '</div>
                            <div class="hidethis_force numeroMesaCont">' . $row['numeroMesa'] . '</div>
                            <div class="hidethis_force statusMesa">' . $row['estadoMesa'] . '</div>
                        </div>
                        <div class="panel-footer text-muted">
                            <button class="pull-right btn btn-success editjobbtn"  type="submit" data-toggle="tooltip" data-placement="right" title="Editar Mesa">
                                <span class="beforeLoad" ><span class="fa fa-edit"></span> Editar Mesa </span>
                                <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                            </button>
                        </div>
                    </div>
                </div>
           ';
        }
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  EDITAMOS LA MESA             //
    if ($method == 'editMesa') {
        $val_select = "UPDATE mesa SET "
                . "numeroMesa = '" . $_POST['numeroMesa'] . "', "
                . "nivelMesa = '" . $_POST['nivelMesa'] . "', "
                . "textoMesa = '" . $_POST['textoMesa'] . "' "
                . " WHERE idMesa = '" . $_POST['idMesa'] . "'";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  AGREGAMOS NUEVA MESA             //
    if ($method == 'addnewMesa') {

        $val_select = "INSERT INTO mesa(idEstablecimiento,estadoMesa,numeroMesa,nivelMesa,textoMesa) "
                . "VALUES ('1','HABILITADA','" . $_POST['numeroMesa'] . "',"
                . "'" . $_POST['nivelMesa'] . "',"
                . "'" . $_POST['textoMesa'] . "')";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  ELIMINAMOS LA MESA             //
    if ($method == 'deleteMesa') {

        $val_select = "DELETE FROM mesa WHERE idMesa = '" . $_POST['deleteid'] . "'";
        $val_result = $conn->query($val_select); //or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  CAMBIAMOS EL ESTATUS LA MESA             //
    if ($method == 'changestatusMesa') {
        if ($_POST['statusJob'] == '1') {
            $estadoMesa = "HABILITADA";
        }
        if ($_POST['statusJob'] == '0') {
            $estadoMesa = "OCUPADA";
        }
        $val_select = "UPDATE mesa SET estadoMesa = '" . $estadoMesa . "' WHERE idMesa = '" . $_POST['idMesa'] . "'";
        $val_result = $conn->query($val_select) or die($conn->error);

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  OBTENEMOS LOS PRODUCTOS     //
    if ($method == 'getProductosMenu') {
        $query = "SELECT * FROM productos";
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            if ($row['estadoProducto'] == 'ACTIVO') {
                $checked = 'on';
                $awe = 'fa-check';
            } else {
                $checked = 'off';
                $awe = 'fa-times';
            }
            echo ' 
            <div class="hidethis boxProductItem col-md-4">
                <div class="panel panel-default">                            
                    <div class="panel-body panel-body-image">
                        <img src="api/assets/img/productos/' . $row['idProducto'] . '.jpg" alt="Slide1" style="height: 300px;"/>
                        <a href="#" class="panel-body-inform panel-body-inform-' . $checked . '">
                            <span class="fa ' . $awe . '"></span>
                        </a>
                    </div>
                    <div class="panel-body">
                        <h3>' . $row['nombreProducto'] . ' &mdash; ' . $row['descProducto'] . '</h3>
                        <div class="hidethis_force idProducto">' . $row['idProducto'] . '</div>
                        <div class="hidethis_force idMenu">' . $row['idMenu'] . '</div>
                        <div class="hidethis_force nombreProducto">' . $row['nombreProducto'] . '</div>
                        <div class="hidethis_force descProducto">' . $row['descProducto'] . '</div>
                        <div class="hidethis_force precioProducto">' . $row['precioProducto'] . '</div>
                        <div class="hidethis_force skuProducto">' . $row['skuProducto'] . '</div>
                        <div class="hidethis_force varsProducto">' . $row['varsProducto'] . '</div>
                        <div class="hidethis_force ingsProducto">' . $row['ingsProducto'] . '</div>
                        <div class="hidethis_force tamProducto">' . $row['tamProducto'] . '</div>
                        <div class="hidethis_force estadoProducto">' . $row['estadoProducto'] . '</div>
                    </div>
                    <div class="panel-footer text-muted">
                        <button class="pull-right btn btn-success editarProductoBtn"  type="submit" data-toggle="tooltip" data-placement="right" title="Editar Portafolio">
                            <span class="beforeLoad"> Editar Producto</span>
                            <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                        </button>
                    </div>
                </div>
            </div>
           ';
        }
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  REEMPLAZAMOS LA IMAGEN DE LOS PEDIDOS     //
    if ($method == 'newimgcustom') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "assets/img/";
        $target_file = $target_dir . basename($_FILES["imgcustom"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgcustom"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgcustom"]["size"] > 500000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . "tableitem.jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgcustom"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  OBTENEMOS LA LISTA DE TODOS LSO INGREDINETES     //
    if ($method == 'getIngFullTable') {

        $query = "SELECT * FROM ingrediente WHERE estadoIngrediente = '1'";
        $result = $conn->query($query) or die($conn->error);
        $json['echo'] = '<select class="form-control select ingFullListSelect" data-live-search="true" data-style="btn-primary">';
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $json['echo'] .= ' <option value="' . $row['idIngrediente'] . '">' . $row['nombreIngrediente'] . '</option>';
            $json['ings'][] = $row;
        }
        $json['echo'] .= '</select>';
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  OBTENEMOS LA LISTA DE TODOS LSO INGREDINETES SIN FILTRO     //
    if ($method == 'getIngFullTableNew') {

        $query = "SELECT * FROM ingrediente WHERE estadoIngrediente = '1'";
        $result = $conn->query($query) or die($conn->error);
        $json['echo'] = '<select class="form-control select ingFullListSelectNew" data-live-search="true" data-style="btn-primary">';
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $json['echo'] .= ' <option value="' . $row['idIngrediente'] . '">' . $row['nombreIngrediente'] . '</option>';
            $json['ings'][] = $row;
        }
        $json['echo'] .= '</select>';
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  OBTENEMOS LA LISTA DE TODOS LOS MENU     //
    if ($method == 'getMenuFullTable') {

        $query = "SELECT * FROM menu";
        $result = $conn->query($query) or die($conn->error);
        $json['echo'] = '<select class="form-control select menuFullCont" id="menuFullCont" data-live-search="true" data-style="btn-primary">';
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            if ($row['idMenu'] == $_POST['idMenu']) {
                $json['echo'] .= ' <option value="' . $row['idMenu'] . '">' . $row['nombreMenu'] . '</option>';
                $json['men'][] = $row;
            }
        }
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            if ($row['idMenu'] != $_POST['idMenu']) {
                $json['echo'] .= ' <option value="' . $row['idMenu'] . '">' . $row['nombreMenu'] . '</option>';
                $json['men'][] = $row;
            }
        }
        $json['echo'] .= '</select>';
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  OBTENEMOS LA LISTA DE TODOS LOS MENU PARA CREAR EL PRODUCTO     //
    if ($method == 'getMenuFullTableNew') {

        $query = "SELECT * FROM menu";
        $result = $conn->query($query) or die($conn->error);
        $json['echo'] = '<select class="form-control select menuFullContNew" id="menuFullContNew" data-live-search="true" data-style="btn-primary">';
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $json['echo'] .= ' <option value="' . $row['idMenu'] . '">' . $row['nombreMenu'] . '</option>';
            $json['men'][] = $row;
        }
        $json['echo'] .= '</select>';
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  EDITAMOS EL PRODUCTO             //
    if ($method == 'editProducto') {

        $query = "SELECT * FROM ingrediente WHERE estadoIngrediente = '1'";
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $ingNames = explode(',', $_POST['ingsProducto']);
            if (in_array($row['nombreIngrediente'], $ingNames)) {
                $json['ingIds'][] = $row['idIngrediente'];
            }
        }

        $val_select = "UPDATE productos SET "
                . "idMenu = '" . $_POST['idMenu'] . "', "
                . "nombreProducto = '" . $_POST['nombreProducto'] . "', "
                . "descProducto = '" . $_POST['descProducto'] . "', "
                . "precioProducto = '" . $_POST['precioProducto'] . "', "
                . "skuProducto = '" . $_POST['skuProducto'] . "', "
                . "varsProducto = '" . $_POST['varsProducto'] . "', "
                . "ingsProducto = '" . implode(',', $json['ingIds']) . "' "
                . " WHERE idProducto = '" . $_POST['idProducto'] . "'";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['query'] = $val_select;
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  EDITAMOS LA IMAGEN DLE PRODUCTO            //
    if ($method == 'newimgheaderPort') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "assets/img/productos/";
        $target_file = $target_dir . basename($_FILES["imgheaderPort"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgheaderPort"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgheaderPort"]["size"] > 500000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . $_POST['idProducto'] . ".jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgheaderPort"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  CAMBIAMOS EL ESTATUS AL PRODUCTO             //
    if ($method == 'changestatusProducto') {
        if ($_POST['statusJob'] == '1') {
            $estadoMesa = "ACTIVO";
        }
        if ($_POST['statusJob'] == '0') {
            $estadoMesa = "INACTIVO";
        }
        $val_select = "UPDATE productos SET estadoProducto = '" . $estadoMesa . "' WHERE idProducto = '" . $_POST['idProducto'] . "'";
        $val_result = $conn->query($val_select) or die($conn->error);

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  ELIMINAMOS EL PRODUCTO             //
    if ($method == 'deleteProd') {

        $val_select = "DELETE FROM productos WHERE idProducto = '" . $_POST['deleteid'] . "'";
        $val_result = $conn->query($val_select); //or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  AGREGAMOS NUEVO PRODUCTO            //
    if ($method == 'addnewProd') {

        $query = "SELECT * FROM ingrediente WHERE estadoIngrediente = '1'";
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $ingNames = explode(',', $_POST['ingsProducto']);
            if (in_array($row['nombreIngrediente'], $ingNames)) {
                $json['ingIds'][] = $row['idIngrediente'];
            }
        }


        $val_select = "INSERT INTO productos(idMenu,nombreProducto,descProducto,precioProducto,estadoProducto,skuProducto,imgProducto,varsProducto,ingsProducto,tamProducto) "
                . "VALUES ('" . $_POST['idMenu'] . "',"
                . "'" . $_POST['nombreProducto'] . "',"
                . "'" . $_POST['descProducto'] . "',"
                . "'" . $_POST['precioProducto'] . "',"
                . "'ACTIVO',"
                . "'" . $_POST['skuProducto'] . "',"
                . "'01',"
                . "'" . $_POST['varsProducto'] . "',"
                . "'" . implode(',', $json['ingIds']) . "',"
                . "'{\"Normal\":\"0\"}')";
        $val_result = $conn->query($val_select);

        // CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "assets/img/productos/";
        $target_file = $target_dir . basename($_FILES["imgheaderPortNew"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgheaderPortNew"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgheaderPortNew"]["size"] > 500000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . $conn->insert_id . ".jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgheaderPortNew"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['debug'] = 'imgSaved';
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  REEMPLAZAMOS LA IMAGEN DEL LOGO     //
    if ($method == 'newLogo') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "../assets/img/";
        $target_file = $target_dir . basename($_FILES["imgcustom"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgcustom"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgcustom"]["size"] > 500000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "png") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . "logo_rec.png";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgcustom"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  REEMPLAZAMOS PRIMER SLIDE    //
    if ($method == 'newSlide1') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "../assets/img/backgrounds/";
        $target_file = $target_dir . basename($_FILES["imgcustom"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgcustom"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgcustom"]["size"] > 50000000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . "1.jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgcustom"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  REEMPLAZAMOS PRIMER SLIDE    //
    if ($method == 'newSlide2') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "../assets/img/backgrounds/";
        $target_file = $target_dir . basename($_FILES["imgcustom"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgcustom"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgcustom"]["size"] > 50000000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . "2.jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgcustom"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  REEMPLAZAMOS PRIMER SLIDE    //
    if ($method == 'newSlide3') {

        //** CARGAMOS LA IMAGEN DE BANNER
        $target_dir = "../assets/img/backgrounds/";
        $target_file = $target_dir . basename($_FILES["imgcustom"]["name"]);
        $uploadOk = 1;
        $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
        // Check if image file is a actual image or fake image
        $check = getimagesize($_FILES["imgcustom"]["tmp_name"]);
        if ($check == false) {
            $json['debug'] = 'notImg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Check file size
        if ($_FILES["imgcustom"]["size"] > 50000000) {
            $json['debug'] = 'tooBig';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        // Allow certain file formats
        if ($imageFileType != "jpg") {
            $json['debug'] = 'notJpg';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $target_file = $target_dir . "3.jpg";
        $newbannername = $filename;
        if (move_uploaded_file($_FILES["imgcustom"]["tmp_name"], $target_file)) {
            chmod($target_file, 0666);
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['debug'] = 'notSaved';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  OBTENEMOS LOS MENU   //
    if ($method == 'getMenuList') {
        $query = "SELECT * FROM menu ";
        $result = $conn->query($query) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            if ($row['estadoMenu'] == 'ACTIVO') {
                $checked = 'checked="checked"';
                $icon = 'fa-check';
                $status = 'success';
            } else {
                $checked = '';
                $icon = 'fa-times';
                $status = 'danger';
            }
            echo ' 
                <div class="col-md-3 hidethis menuItemBlock">
                    <div class="widget widget-' . $status . ' widget-item-icon">
                        <div class="widget-item-left">
                            <span class="fa ' . $icon . '"></span>
                        </div>
                        <div class="widget-data">
                            <div class="widget-int num-count">Categoría:</div>
                            <div class="widget-title">' . $row['nombreMenu'] . '</div>
                            <div class="hidethis_force idMenuCont">' . $row['idMenu'] . '</div>
                            <div class="hidethis_force nombreMenuCont">' . $row['nombreMenu'] . '</div>
                            <div class="hidethis_force statusMenu">' . $row['estadoMenu'] . '</div>
                            <div class="widget-subtitle">
                                <button class="btn btn-info editjobbtn"  type="submit" data-toggle="tooltip" data-placement="right" title="Editar">
                                    <span class="beforeLoad" ><span class="fa fa-edit"></span> Editar </span>
                                    <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                                </button>
                            </div>
                        </div>                          
                    </div>
                </div>
           ';
        }
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  EDITAMOS EL MENU          //
    if ($method == 'editMenu') {
        $val_select = "UPDATE menu SET "
                . "nombreMenu = '" . $_POST['nombreMenu'] . "' "
                . " WHERE idMenu = '" . $_POST['idMenu'] . "'";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $json['query'] = $val_select;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  AGREGAMOS NUEVA MESA             //
    if ($method == 'addnewMenu') {

        $val_select = "INSERT INTO menu(nombreMenu,estadoMenu) "
                . "VALUES ('" . $_POST['nombreMenu'] . "',"
                . "'ACTIVO')";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  ELIMINAMOS LA MESA             //
    if ($method == 'deleteMenu') {

        $val_select = "DELETE FROM menu WHERE idMenu = '" . $_POST['deleteid'] . "'";
        $val_result = $conn->query($val_select); //or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  CAMBIAMOS EL ESTATUS LA MESA             //
    if ($method == 'changestatusMenu') {
        if ($_POST['statusJob'] == '1') {
            $estadoMenu = "ACTIVO";
        }
        if ($_POST['statusJob'] == '0') {
            $estadoMenu = "INACTIVO";
        }
        $val_select = "UPDATE menu SET estadoMenu = '" . $estadoMenu . "' WHERE idMenu = '" . $_POST['idMenu'] . "'";
        $val_result = $conn->query($val_select) or die($conn->error);

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  ACTUALIZAMOS LOS TAMAñOS           //
    if ($method == 'updateTams') {

        $tams = $_POST['tams'];
        $prodId = $_POST['idProducto'];
        $val_select = "UPDATE productos SET tamProducto = '" . $tams . "' WHERE idProducto = '" . $prodId . "'";
        $val_result = $conn->query($val_select) or die($conn->error);

        if ($val_result) {
            $json['status'] = 'yes';
            $json['q'] = $val_select;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  CARGAMOS NUEVO PEDIDO EN SISTEMA           //
    if ($method == 'loadNewPedido') {

        session_start();
        $pedidosList = json_decode(stripslashes($_POST['pedidos']));
        if ($_SESSION['idmesa'] == '0') {
            $insertPedido = "INSERT INTO pedido(idMesa,idUsuario,estadoPedido,estadopagoPedido) "
                    . "VALUES ('0',"
                    . "'" . $_SESSION['usuario']['idUsuario'] . "',"
                    . "'DOMICILIO',"
                    . "'SIN PAGAR')";
        } else {
            $insertPedido = "INSERT INTO pedido(idMesa,idUsuario,estadoPedido,estadopagoPedido) "
                    . "VALUES ('" . $_SESSION['idmesa'] . "',"
                    . "'" . $_SESSION['usuario']['idUsuario'] . "',"
                    . "'SOLICITADO',"
                    . "'SIN PAGAR')";
        }
        $val_result = $conn->query($insertPedido); // or die($link->error)

        if ($val_result) {
            $lastIdPedido = $conn->insert_id;
            $catnPEdidos = sizeof($pedidosList);
            $catnPEdidos = $catnPEdidos - 1;
            for ($x = 0; $x <= $catnPEdidos; $x++) {
                $pedidosList[$x] = (array) $pedidosList[$x];
            }

            foreach ($pedidosList as $thisPedido) {
                $insertPedidoProds = "INSERT INTO `pedidoproducto`(`idPedido`,`idProducto`,`descripcionPedidoproducto`,`cantidadPedidoproducto`,`observacionPedidoproducto`,`precioPedidoProducto`,`ingsPedidoProducto`,`estadoPedidoproducto`) "
                        . "VALUES ('" . $lastIdPedido . "',"
                        . "'" . $thisPedido['idProducto'] . "',"
                        . "'" . $thisPedido['descripcionPedidoproducto'] . "',"
                        . "'" . $thisPedido['cantidadPedidoproducto'] . "',"
                        . "'" . $thisPedido['observacionPedidoproducto'] . "',"
                        . "'" . $thisPedido['precioPedidoProducto'] . "',"
                        . "'" . $thisPedido['ingsPedidoProducto'] . "',"
                        . "'SOLICITADO'); ";
                $insertPedidos_result = $conn->query($insertPedidoProds) or die($link->error);
            }
            if ($insertPedidos_result) {
                $val_select = "UPDATE mesa SET estadoMesa = 'OCUPADA' WHERE idMesa = '" . $_SESSION['idmesa'] . "'";
                $val_result = $conn->query($val_select) or die($conn->error);

                if ($val_result) {
                    $json['status'] = 'yes';
                    $output = ob_get_contents();
                    ob_end_clean();
                    $json['output'] = $output;
                    echo json_encode($json);
                } else {
                    $json['status'] = 'no';
                    $output = ob_get_contents();
                    ob_end_clean();
                    $json['query'] = $val_select;
                    $json['output'] = $output;
                    echo json_encode($json);
                }
            } else {
                $json['status'] = 'no';
                $output = ob_get_contents();
                ob_end_clean();
                $json['query'] = $insertPedidoProds;
                $json['error'] = $conn->error;
                $json['output'] = $output;
                echo json_encode($json);
            }
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $insertPedido;
            $json['output'] = $output;
            echo json_encode($json);
            die;
        }
    }

    //                  MOSTRAMOS LOS PEDIDOS PARA LA COCINA         //
    if ($method == 'consultaProductosCocina') {

        $idpedido = $_POST["idpedido"];

        $query = "SELECT * FROM pedidoproducto pp "
                . "INNER JOIN productos p on(p.idProducto = pp.idProducto) "
                . "INNER JOIN menu m on (p.idMenu = m.idMenu) "
                . "WHERE pp.idPedido= '$idpedido' AND pp.estadoPedidoproducto != 'ENTREGADO'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $productos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $productos[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        $htmlPedido = "";
        $contador = 1;
        $index = $_POST["index"];

        foreach ($productos as $producto) {
            $estado = "";
            $icon = "";
            if ($producto["estadoPedidoproducto"] == "SOLICITADO") {
                $estado = "info";
                $icon = '<i class="fa fa-asterisk fa-2x" style="font-size:25px;color:white;" aria-hidden="true"></i>';
            } elseif ($producto["estadoPedidoproducto"] == "EN PROCESO") {
                $estado = "warning";
                $icon = '<i class="fas fa-sync-alt fa-spin fa-2x fa-fw" style="font-size:25px;color:white;"></i>';
            } elseif ($producto["estadoPedidoproducto"] == "LISTO PARA ENTREGAR") {
                $estado = "success";
                $icon = '<i class="fa fa-check" style="font-size:25px;color:white;" aria-hidden="true"></i>';
            } elseif ($producto["estadoPedidoproducto"] == "ENTREGADO") {
                $estado = "default";
                $icon = '<i class="fas fa-vote-yea" aria-hidden="true" style="font-size:25px;color:black;"></i>';
            }


            $ings = $producto["ingsPedidoProducto"];
            $origIngs = explode(',', $producto["ingsProducto"]);
            $query2 = "SELECT * FROM ingrediente ing WHERE ing.idIngrediente IN ($ings) ";
            $result2 = $conn->query($query2);
            if (!$result2)
                die(json_encode($query2));
            $rows = $result2->num_rows;
            $allIngs = '<ul class="list-tags">';
            for ($i = 0; $i < $rows; $i++) {
                $result2->data_seek($i);
                $thisIng = $result2->fetch_array(MYSQLI_ASSOC);
                if (in_array($thisIng['idIngrediente'], $origIngs)) {
                    $allIngs .= '<li><a><i class="fas fa-pepper-hot"></i> ' . $thisIng['nombreIngrediente'] . '</a></li>';
                } else {
                    $allIngs .= '<li><a class="greenTag"><i class="fas fa-pepper-hot"></i> ' . $thisIng['nombreIngrediente'] . '</a></li>';
                }
            }
            $allIngs .= '</ul>';


            $htmlPedido .= '<div class="tile tile-' . $estado . ' col-md-10 col-md-offset-1 subitem' . $contador . '" style="text;display: block;white-space:inherit;border: 1px solid white;min-height: 50px;" tabindex="-1">
                    <div style="display:none;" class="inputMesa"><input type="checkbox" id="chk_pedido" name="chk_pedido" autocomplete="off" value="1"></div>
                     ' . '<div style="position: absolute;top: -20px;right: 5px;">' . $icon . '</div>' . '
                    <div class="idpedido" hidden>' . $producto["idPedido"] . '</div>
                    <div class="idpedidoproducto" hidden>' . $producto["idPedidoproducto"] . '</div>
                <div class="label-form col-md-12 " style="font-weight: bold;color:black;">
                <p style="text-align: center;font-size: 25px;line-height: 30px;">' . $producto["nombreProducto"] . '</p><br>
                <p style="text-align: center;font-size: 20px;">' . $allIngs . '</p>';

            $htmlPedido .= '</div></div>';
            $contador++;
        }

        echo $htmlPedido;

        $json['result'] = $htmlPedido;
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        echo json_encode($json);
        return;
    }

    //                  CONSULTAR PEDIDO A EDITAR       //
    if ($method == 'getThisOrder') {

        $idpedido = $_POST["idPedido"];

        $query = "SELECT * FROM pedidoproducto pp "
                . "INNER JOIN productos p ON (p.idProducto = pp.idProducto) "
                . "INNER JOIN pedido ped ON (pp.idPedido = ped.idPedido) "
                . "INNER JOIN mesa mes ON (ped.idMesa = mes.idMesa) "
                . "INNER JOIN menu m ON (p.idMenu = m.idMenu) "
                . "WHERE pp.idPedido= '$idpedido'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $productos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $thisLine = $result->fetch_array(MYSQLI_ASSOC);
            $ings = $thisLine['ingsPedidoProducto'];
            $query2 = "SELECT * FROM ingrediente ing WHERE ing.idIngrediente IN ($ings) ";
            $result2 = $conn->query($query2);
            if (!$result2)
                die(json_encode($query2));
            $rowss = $result2->num_rows;
            $allIngs = array();
            for ($ii = 0; $ii < $rowss; $ii++) {
                $result2->data_seek($ii);
                $allIngs[] = $result2->fetch_array(MYSQLI_ASSOC);
            }
            $thisLine['allIngs'] = $allIngs;
            $productos[] = $thisLine;
        }

        $output = ob_get_contents();
        ob_end_clean();
        $json['list'] = $productos;
        $json['output'] = $output;
        $json['quer'] = $query;
        $json['status'] = 'yes';
        echo json_encode($json);
        return;
    }

    //                  OBTENER TODOS LSO INGREDIENTES DE UNA LISTA      //
    if ($method == 'getIngsList') {
        $ings = $product['ingsPedidoProducto'];
        $query2 = "SELECT * FROM ingrediente ing WHERE ing.idIngrediente IN ($ings) ";
        $result2 = $conn->query($query2);
        if (!$result2)
            die(json_encode($query2));
        $rows = $result2->num_rows;
        $allIngs = array();
        for ($i = 0; $i < $rows; $i++) {
            $result2->data_seek($i);
            $allIngs[] = $result2->fetch_array(MYSQLI_ASSOC);
        }

        $json['ings'] = $allIngs;
        $json['quer'] = $query2;
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  ACTUALIZAMOS NUEVO PEDIDO EN SISTEMA           //
    if ($method == 'loadUpdatePedido') {

        session_start();
        $idPedido = $_POST['idPedido'];
        $pedidosList = json_decode(stripslashes($_POST['pedidos']));
        $insertPedido = "DELETE FROM pedidoproducto WHERE idPedido = '" . $idPedido . "'  ";
        $val_result = $conn->query($insertPedido); // or die($link->error)

        if ($val_result) {
            $lastIdPedido = $idPedido;
            $catnPEdidos = sizeof($pedidosList);
            $catnPEdidos = $catnPEdidos - 1;
            for ($x = 0; $x <= $catnPEdidos; $x++) {
                $pedidosList[$x] = (array) $pedidosList[$x];
            }

            foreach ($pedidosList as $thisPedido) {
                $insertPedidoProds = "INSERT INTO `pedidoproducto`(`idPedido`,`idProducto`,`descripcionPedidoproducto`,`cantidadPedidoproducto`,`observacionPedidoproducto`,`precioPedidoProducto`,`ingsPedidoProducto`,`estadoPedidoproducto`) "
                        . "VALUES ('" . $lastIdPedido . "',"
                        . "'" . $thisPedido['idProducto'] . "',"
                        . "'" . $thisPedido['descripcionPedidoproducto'] . "',"
                        . "'" . $thisPedido['cantidadPedidoproducto'] . "',"
                        . "'" . $thisPedido['observacionPedidoproducto'] . "',"
                        . "'" . $thisPedido['precioPedidoProducto'] . "',"
                        . "'" . $thisPedido['ingsPedidoProducto'] . "',"
                        . "'SOLICITADO'); ";
                $insertPedidos_result = $conn->query($insertPedidoProds) or die($link->error);
            }
            if ($insertPedidos_result) {
                $json['status'] = 'yes';
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
            } else {
                $json['status'] = 'no';
                $output = ob_get_contents();
                ob_end_clean();
                $json['query'] = $insertPedidoProds;
                $json['error'] = $conn->error;
                $json['output'] = $output;
                echo json_encode($json);
            }
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $insertPedido;
            $json['output'] = $output;
            echo json_encode($json);
            die;
        }
    }

    //                  AGREGAR  NUEVO INGREDINETE           //
    if ($method == 'addnewing') {
        $select = "SELECT codigoIngrediente FROM ingrediente WHERE codigoIngrediente = '" . $_POST['codigoIngrediente'] . "';";
        $result = $conn->query($select) or die($conn->error);
        $row_cnt = $result->num_rows;

        if ($row_cnt > 0) {
            $json['status'] = "error";
            $json['msg'] = " Ya existe el ingrediente en sistema, por favor seleccione un codigo diferente.";
            echo json_encode($json);
        } else {
            $query = "INSERT INTO ingrediente (nombreIngrediente,cantidad1,codigoIngrediente,barcodeIngrediente,tipoIngrediente,detalleIngrediente,bodegaIngrediente,minIngrediente,precioIngrediente,compraIngrediente,editadoIngredinete,estadoIngrediente) "
                    . " VALUES ('" . $_POST['nombreIngrediente'] . "','" . $_POST['cantidad'] . "','" . $_POST['codigoIngrediente'] . "','" . $_POST['barcodeIngrediente'] . "','" . $_POST['tipoIngrediente'] . "','" . $_POST['detalleIngrediente'] . "','" . $_POST['bodegaIngrediente'] . "','" . $_POST['minIngrediente'] . "','" . $_POST['precioIngrediente'] . "','" . $_POST['compraIngrediente'] . "','" . date('Y-m-d') . "','" . $_POST['estadoIngrediente'] . "')";
            //        echo $query;
            $val_result = $conn->query($query) or die($conn->error);

            if ($val_result) {
                $json['status'] = "ok";
                $json['msg'] = " Nuevo ingrediente agregado en sistema ";
                echo json_encode($json);
            } else {
                $json['status'] = "error";
                $json['msg'] = " Error al crear el ingrediente, consulte con su departamento de soporte. ";
                echo json_encode($json);
            }
        }
        return;
    }

    //                     OBTENEMOS LOS PRODUCTOS RELACIONADOS AL INGREDIENTE                   //
    if ($method == 'getRelsProd') {

        $idIng = $_POST["idIng"];
        $html = '';
        $ingsRows = [];
        $select = "SELECT * FROM productos WHERE estadoProducto = 'ACTIVO';";
        $result = $conn->query($select) or die($conn->error);
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $ingList = explode(',', $row['ingsProducto']);
            $ingsRows[] = $ingList;
            if (in_array($idIng, $ingList)) {
                $selectRel = "SELECT * FROM relaciones WHERE idIngrediente = '" . $idIng . "' AND idProducto = '" . $row['idProducto'] . "' LIMIT 1;";
                $resultRel = $conn->query($selectRel) or die($conn->error);
                $row_cntRel = $resultRel->num_rows;
                $rowRel = $resultRel->fetch_array(MYSQLI_ASSOC);
                if ($row_cntRel > 0) {
                    $html .= '  <div class="widget widget-info widget-item-icon">' .
                            '       <div class="widget-item-left editThisRel">' .
                            '            <span class="fa fa-save" data-toggle="tooltip" data-placement="top" title="Actualizar"></span>' .
                            '        </div>' .
                            '        <div class="widget-data">' .
                            '            <div class="hidden idIngRel">' . $idIng . '</div>' .
                            '            <div class="hidden idProdRel">' . $row['idProducto'] . '</div>' .
                            '            <div class="widget-int num-count">- ' . $rowRel['valRel'] . '</div>' .
                            '            <div class="widget-title tamIndex">' . $row['nombreProducto'] . '</div>' .
                            '            <div class="widget-subtitle col-md-3"><input type="text" class="form-control relNewValInput" value="" placeholder="Actualizar" /></div>' .
                            '      </div>  ' .
                            '      <div class="widget-controls deleteThisTam">' .
                            '           <a class="widget-control-right"><span class="fa fa-times"></span></a>' .
                            '      </div>     ' .
                            '   </div>
                         ';
                } else {
                    $html .= '  <div class="widget widget-info widget-item-icon">' .
                            '       <div class="widget-item-left editThisRel">' .
                            '            <span class="fa fa-save" data-toggle="tooltip" data-placement="top" title="Actualizar"></span>' .
                            '        </div>' .
                            '        <div class="widget-data">' .
                            '            <div class="hidden idIngRel">' . $idIng . '</div>' .
                            '            <div class="hidden idProdRel">' . $row['idProducto'] . '</div>' .
                            '            <div class="widget-int num-count">- 1</div>' .
                            '            <div class="widget-title tamIndex">' . $row['nombreProducto'] . '</div>' .
                            '            <div class="widget-subtitle col-md-3"><input type="text" class="form-control relNewValInput" value="" placeholder="Actualizar" /></div>' .
                            '      </div>  ' .
                            '      <div class="widget-controls deleteThisTam">' .
                            '           <a class="widget-control-right"><span class="fa fa-times"></span></a>' .
                            '      </div>     ' .
                            '   </div>
                         ';
                }
            }
        }
        if ($html == '') {
            $html = '<h3>Este Ingrediente no esta relacionado a ningun Producto</h3>';
        }
        $json['idIng'] = $idIng;
        $json['ingS'] = $ingsRows;
        $json['status'] = 'yes';
        $json['html'] = $html;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  CONSULTAMOS EL TURNO ACTUAL   //
    if ($method == 'updateRel') {

        $idIngr = $_POST['idIngrediente'];
        $prodId = $_POST['idProducto'];
        $newVal = $_POST['relNewVal'];
        $val_select = "DELETE FROM relaciones WHERE idProducto = '" . $prodId . "' AND idIngrediente = '" . $idIngr . "'";
        $val_result = $conn->query($val_select) or die($conn->error);
        $val_Ins = "INSERT INTO relaciones(valRel,idProducto,idIngrediente) VALUES ('" . $newVal . "','" . $prodId . "','" . $idIngr . "')";
        $ins_result = $conn->query($val_Ins) or die($conn->error);

        if ($ins_result) {
            $json['status'] = 'yes';
            $json['q'] = $val_Ins;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
    }

    //                  CONSULTAMOS EL TURNO   DE CAJA             //
    if ($method == 'getTurno') {

        $query2 = "SELECT * FROM turnos tur "
                . "LEFT JOIN usuario us ON (tur.idUsuario = us.idUsuario) "
                . "ORDER BY idTurno DESC LIMIT 1";
        $result2 = $conn->query($query2);
        $rows = $result2->num_rows;
        if ($rows > 0) {
            $row = $result2->fetch_array(MYSQLI_ASSOC);
            $json['lastTurno'] = $row;
            $json['status'] = 'yes';
        } else {
            $json['status'] = 'no';
        }
        $json['quer'] = $query2;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //                  ABRIMOS UN NUEVO TURNO DE CAJA     //
    if ($method == 'abrirTurno') {
        session_start();

        $val_select = "INSERT INTO turnos(idUsuario,fechaTurno,tipoTurno,saldoTurno,msgTurno) "
                . "VALUES ('" . $_SESSION['usuario']['idUsuario'] . "',"
                . "'" . date('Y-m-d H:i:s') . "',"
                . "'apertura',"
                . "'" . $_POST['montoInicial'] . "',"
                . "'" . $_POST['comentario'] . "')";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
        return;
    }

    //                  CERRAMOS UN NUEVO TURNO DE CAJA     //
    if ($method == 'cerrarTurno') {
        $val_select = "UPDATE turnos SET "
                . "tipoTurno = 'cierre', "
                . "fechaModif = '" . date('Y-m-d H:i:s') . "', "
                . "finalTurno = '" . $_POST['montoFinal'] . "' "
                . "WHERE idTurno = '" . $_POST['idTurno'] . "' ";
        $val_result = $conn->query($val_select); // or die($link->error)

        if ($val_result) {
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
        } else {
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['query'] = $val_select;
            $json['output'] = $output;
            echo json_encode($json);
        }
        return;
    }

    //                  ACTUALIZAMOS LA INTERFAZ     //
    if ($method == 'sidebarUpdate') {

        $val_select = "UPDATE usuario SET sidebar = '" . $_POST['changeStatus'] . "' WHERE idUsuario = '" . $_POST['idUsuario'] . "'";
        $val_result = $conn->query($val_select) or die($conn->error);
    
        if ($val_result) {
            session_start();
            $_SESSION["usuario"]['sidebar'] = $_POST['changeStatus'];
            $msg_logo .= ' Se ha atualizado la configuraci&oacute;n de la interfaz exitosamente. ' . 
            '<br><button class="pull-left btn btn-success" name="newtheme" type="submit" id="refreshThisPage" data-toggle="tooltip" data-placement="top" title="" data-original-title="Actualizar"><span class="fa fa-refresh"></span> Actualizar</button> ';
            echo $msg_logo;
            $json['status'] = 'yes';
        } else {
            echo " No pudimos actualizar la interfaz. Intente de nuevo ";
            $json['status'] = 'no';
        }
        
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
    }
    
    
    //                  ACTUALIZAMOS LA PANTALLACOMPLETA      //
    if ($method == 'fullwidthUpdate') {
    
        $val_select = "UPDATE usuario SET fullwidth = '" . $_POST['changeStatus'] . "' WHERE idUsuario = '" . $_POST['idUsuario'] . "'";
        $val_result = $conn->query($val_select) or die($conn->error);
    
        if ($val_result) {
            session_start();
            $_SESSION["usuario"]['fullwidth'] = $_POST['changeStatus'];
            $msg_logo .= ' Se ha atualizado la configuraci&oacute;n de la interfaz exitosamente.' . 
            '<br><button class="pull-left btn btn-success" name="newtheme" type="submit" id="refreshThisPage" data-toggle="tooltip" data-placement="top" title="" data-original-title="Actualizar"><span class="fa fa-refresh"></span> Actualizar</button> ';
            echo $msg_logo;
            $json['status'] = 'yes';
        } else {
            echo " No pudimos actualizar la interfaz. Intente de nuevo ";
            $json['status'] = 'no';
        }
        
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
    }
}

if ($_GET) {
    $method = broom('reg', $_GET['meth']);

    /////////////////////////////////////////////////////////
    //       GENERAMOS LOS REPORTES DE LA PLATAFORMA       //
    /////////////////////////////////////////////////////////
    if ($method == 'report') {
        $type = broom('num', $_GET["print"]);

        ////////////////////    REPORTE DE CORTE X      ////////////////////
        if ($type == '1') {

            $query = "SELECT * FROM factura "
                    . "WHERE statusFactura = 'ACTIVE' "
                    . "AND idTurno = '" . $_GET["idTurno"] . "'";

            $result = $conn->query($query);
            if (!$result)
                die($query);
            $num_fields = mysqli_num_fields($result);

            $fp = fopen('php://output', 'w');
            if ($fp && $result) {
                $query2 = "SELECT * FROM turnos tur "
                        . "LEFT JOIN usuario us ON (tur.idUsuario = us.idUsuario) "
                        . "ORDER BY idTurno DESC LIMIT 1";
                $result2 = $conn->query($query2);
                $rows = $result2->num_rows;
                if ($rows > 0) {
                    $rowTurno = $result2->fetch_array(MYSQLI_ASSOC);
                }
                $title = [];
                $title[] = ' Reporte X                 ' . date('Y-m-d H:i:s');
                fputcsv($fp, $title, ';');
                $title = [];
                $title[] = ' Turno Cajero:               ' . $rowTurno['nombresUsuario'] . ' ' . $rowTurno['apellidosUsuario'];
                fputcsv($fp, $title, ';');
                $title = [];
                $title[] = ' Saldo Inicial:                   ' . $rowTurno['saldoTurno'] . ' $';
                fputcsv($fp, $title, ';');
                $title = [];
                $title[] = ' ';
                fputcsv($fp, $title, ';');
                $headers = array('Factura', 'Pedido', 'Cliente', 'Turno', 'Fecha', 'Hora', 'Subtotal', 'Descuento Otorgado', 'IVA', 'Total', 'Formas de Pago', 'Voucher TDC', 'Pagos Diferenciados', 'Vuelto entregado', 'Pagado con Efectivo', 'Pagado con TDC', 'Pago Diferenciado', 'Tipo de Entrega');
                fputcsv($fp, $headers, ';');
                $sumSubtotal = 0;
                $sumIva = 0;
                $sumTotal = 0;
                while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
                    $sumSubtotal = number_format($sumSubtotal + $row['subtotalFactura'], 2, '.', '');
                    $sumIva = number_format($sumIva + $row['ivaFactura'], 2, '.', '');
                    $sumTotal = number_format($sumTotal + $row['totalFactura'], 2, '.', '');
                    unset($row['idEstablecimiento']);
                    unset($row['statusFactura']);
                    fputcsv($fp, $row, ';');
                }
                $totales = [];
                $totales[] = ' ';
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' Subtotal:';
                $totales[] = $sumSubtotal;
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' IVA:';
                $totales[] = $sumIva;
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' Total: ';
                $totales[] = $sumTotal;
                fputcsv($fp, $totales, ';');

                header('Content-Type: text/csv; charset=utf-8');
                header("Content-Disposition: attachment; filename=corteX" . date('Ymd-His') . ".csv");
                return;
            }
        }
        
        ////////////////////    CORTE Z      ////////////////////
        if ($type == '2') {

            $query = "SELECT * FROM factura "
                    . "WHERE statusFactura = 'ACTIVE' "
                    . "AND fechaFactura = '" . date('Y-m-d') . "'";

            $result = $conn->query($query);
            if (!$result)
                die($query);
            $num_fields = mysqli_num_fields($result);

            $fp = fopen('php://output', 'w');
            if ($fp && $result) {
                $title = [];
                $title[] = ' Reporte Z                 ' . date('Y-m-d H:i:s');
                fputcsv($fp, $title, ';');
                $title = [];
                $title[] = ' ';
                fputcsv($fp, $title, ';');
                $headers = array('Factura', 'Pedido', 'Cliente', 'Turno', 'Fecha', 'Hora', 'Subtotal', 'Descuento Otorgado', 'IVA', 'Total', 'Formas de Pago', 'Voucher TDC', 'Pagos Diferenciados', 'Vuelto entregado', 'Pagado con Efectivo', 'Pagado con TDC', 'Pago Diferenciado', 'Tipo de Entrega');
                fputcsv($fp, $headers, ';');
                $sumSubtotal = 0;
                $sumIva = 0;
                $sumTotal = 0;
                while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
                    $sumSubtotal = number_format($sumSubtotal + $row['subtotalFactura'], 2, '.', '');
                    $sumIva = number_format($sumIva + $row['ivaFactura'], 2, '.', '');
                    $sumTotal = number_format($sumTotal + $row['totalFactura'], 2, '.', '');
                    unset($row['idEstablecimiento']);
                    unset($row['statusFactura']);
                    fputcsv($fp, $row, ';');
                }
                $totales = [];
                $totales[] = ' ';
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' Subtotal:';
                $totales[] = $sumSubtotal;
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' IVA:';
                $totales[] = $sumIva;
                fputcsv($fp, $totales, ';');
                $totales = [];
                $totales[] = ' Total: ';
                $totales[] = $sumTotal;
                fputcsv($fp, $totales, ';');

                header('Content-Type: text/csv; charset=utf-8');
                header("Content-Disposition: attachment; filename=corteZ" . date('Ymd-His') . ".csv");
                return;
            }
        }
    }
}

//   Si no se llamó ningún método de la API     //
var_dump($_POST);
var_dump($_GET);
var_dump($_FILES);
$output = ob_get_contents();
$json['msg'] = "Silent script";
$json['output'] = $output;
ob_end_clean();
echo json_encode($json);
return;
?>