<?php

/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */


//  DEBUG EN PANTALLA   //
error_reporting(E_ALL);
ini_set('display_errors', 1);

//  HABILITAMOS EL ACCESO PUBLICO PARA REALIZAR LLAMADAS AJAX DESDE DOMINIOS PUBLICOS   //
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Auth-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS');

header('Content-type: application/javascript; charset=utf-8');

//   ES IMPORTANTE RESCATAR TODO EL OUTPUT  //
/*
 * LUEGO PODEMOS PROMPTEARLO EN PANTALLA CON
 * $output = ob_get_contents(); ob_end_clean();
 */
ob_start();

//   INCLUDES   //
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'assets/plugins/PHPMailer/src/Exception.php';
require 'assets/plugins/PHPMailer/src/PHPMailer.php';
require 'assets/plugins/PHPMailer/src/SMTP.php';
require_once 'assets/scripts/funcs.php';

//   Creamos el enlace con la DB    //
require("../assets/scripts/database.php");

// INICIAMOS //
date_default_timezone_set('America/Guayaquil');
$json = array();
if ($_POST) {
    $method = broom('reg', $_POST['meth']);

    //          USUARIO INICIA SESION           //
    if ($method == 'login') {


        $username = broom('reg', $_POST["username"]);
        $password = $_POST["password"];

//        $username = filter_var($_POST['username'], FILTER_VALIDATE_EMAIL);
//        $password = hash('sha512', $_POST['password']);
//        
        ////            CONSULTAMOS EL USUARIO EN LA BASE DE DATOS A VER SI EXISTE              ////
        $query = " SELECT * FROM usuario us "
                . " INNER JOIN perfil p ON (us.idPerfil = p.idPerfil ) "
                . " INNER JOIN establecimiento e ON (us.idEstablecimiento = e.idEstablecimiento ) "
                . " WHERE nombreUsuario like '$username' ";
        $result = $conn->query($query);
        if (!$result) {
            $json['scriptResp'] = "userqueryFail";
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        $rows = $result->num_rows;
        $row = $result->fetch_array(MYSQLI_ASSOC);

        ////          RETORNAMOS UN JSON AL AJAX PARA ALIMENTAR EL JAVASCRIPT          ////
        $json['userIntel'] = $row;

        if (($rows != 0) && (strcmp($row["nombreUsuario"], $username) == 0) && ($row['passwordUsuario'] === $password)) {

            //   VERIFICAMOS SI TIENE IMAGEN CARGADA || CARGAMOS IMAGEN PREDETERMINADA        //
            $isavatar = "assets/img/users/" . $row["idUsuario"] . ".jpg";
            if (file_exists($isavatar)) {
                $json['userIntel']['userImg'] = "api/" . $isavatar;
            } else {
                $isavatar2 = "assets/img/users/" . $row["idUsuario"] . ".png";
                if (file_exists($isavatar2)) {
                    $json['userIntel']['userImg'] = "api/" . $isavatar2;
                } else {
                    $json['userIntel']['userImg'] = "api/assets/img/users/default.jpg";
                }
            }

            ////             ENVIAMOS DATOS POR $_SESSION;          /////
            session_start();
            $_SESSION["usuario"] = $json['userIntel'];

            //              DATOS PARA CONSTRUIR LOS MODULOS            //
            $_SESSION["usuario"]["nombreEstablecimiento"] = $json['userIntel']["nombreEstablecimiento"];
            $_SESSION["usuario"]["ciudadEstablecimiento"] = $json['userIntel']["ciudadEstablecimiento"];
            $_SESSION["usuario"]["telefonoEstablecimiento"] = $json['userIntel']["telefonoEstablecimiento"];
            $_SESSION["usuario"]["sectorEstablecimiento"] = $json['userIntel']["sectorEstablecimiento"];

            $val_update = "UPDATE usuario SET lastLogin = '" . date('Y-m-d H:i:s') . "' WHERE idUsuario = '" . $row["idUsuario"] . "';";
            $val_result = $conn->query($val_update) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $val_update . "'}");

            $json['userIntel'] = $_SESSION["usuario"];
            $json['scriptResp'] = "match";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "noMatch";
            $json['passw'] = $_POST['password'];
            $json['passwo'] = $password;
            $json['password'] = $row['passUsuario'];
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          ASIGNAMOS LAS MESAS AL NUEVO EPDIDO             //
    if ($method == 'asignaMesa') {

        $idMesa = $_POST["idmesa"];
        $numeroMesa = $_POST["numeromesa"];
        $idPedido;

        if (isset($_POST["idpedido"])) {
            $idPedido = $_POST["idpedido"];
        }
        session_start();
        $_SESSION["idmesa"] = $idMesa;
        $_SESSION["numeromesa"] = $numeroMesa;
        if (isset($idPedido)) {
            $_SESSION["idpedido"] = $idPedido;

            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          CONSULTAMOS LOS PEDIDOS EXISTENTES            //
    if ($method == 'consultaPedidos') {

        session_start();
        $idEstablecimiento = $_SESSION['usuario']['idEstablecimiento'];

        $query = "SELECT * FROM pedido pe "
                . "INNER JOIN mesa m on(m.idMesa=pe.idMesa) "
                . "INNER JOIN pedidoproducto pp ON(pe.idPedido = pp.idPedido) "
                . "INNER JOIN producto p on(p.idProducto = pp.idProducto) "
                . "INNER JOIN submenu sm on(p.idSubMenu = sm.idSubMenu) "
                . "INNER JOIN menu me on (sm.idMenu = me.idMenu) "
                . "GROUP BY(pe.idPedido) "
                . "HAVING m.estadoMesa = 'OCUPADA' AND pe.estadopagoPedido != 'PAGADO' AND m.idEstablecimiento = '$idEstablecimiento' "
                . "ORDER BY pe.idPedido ASC";

        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $pedidos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $pedidos[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        $json['pedidos'] = $pedidos;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          VERIFICAMOS LAS MESAS DISPONIBLES           //
    if ($method == 'mesas') {

        session_start();
        $idEstablecimiento = $_SESSION['usuario']['idEstablecimiento'];

        //          LLAMAMOS TODAS LAS MESAS DISPONIBLES PARA ESE ESTABLECIMIENTO           //
        $query = "SELECT * FROM mesa WHERE idEstablecimiento = '$idEstablecimiento' AND estadoMesa = 'HABILITADA' ORDER BY CAST(numeroMesa as SIGNED INTEGER) ASC";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $row = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $row['database'][] = $result->fetch_array(MYSQLI_ASSOC);
            $temp = end($row['database']);
            $row['keys'][] = $temp['nivelMesa'];
        }
        $json['mesas'] = $row['database'];
        $json['niveles'] = array_unique($row['keys']);

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
        return;
    }

    //          MOSTRAMOS LOS PRODUCTOS DLE PEDIDO CLICKEADO           //
    if ($method == 'consultaProductos') {

        $idpedido = $_POST["idpedido"];

        $query = "SELECT * FROM pedidoproducto pp "
                . "JOIN producto p ON (p.idProducto = pp.idProducto) "
                . "JOIN submenu sm ON(p.idSubMenu = sm.idSubMenu) "
                . "JOIN menu m ON (sm.idMenu = m.idMenu) "
                . "WHERE pp.idPedido= '$idpedido'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $productos = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $productos[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        $htmlPedido = "";

        foreach ($productos as $producto) {
            $htmldiv = '<div style="display:none;" class="idproducto">' . $producto["idProducto"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="idsubmenu">' . $producto["idSubmenu"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="idmenu">' . $producto["idMenu"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="idpedido">' . $producto["idPedido"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="idpedidoproducto">' . $producto["idPedidoproducto"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="nombrepedidoproducto">' . $producto["nombreProducto"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="submenupedidoproducto">' . $producto["nombreSubmenu"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="menupedidoproducto">' . $producto["nombreMenu"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="descripcionpedidoproducto">' . $producto["descripcionPedidoproducto"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="observacionpedidoproducto">' . $producto["observacionPedidoproducto"] . '</div>';
            $htmldiv .= '<div style="display:none;" class="cantidadpedidoproducto">' . $producto["cantidadPedidoproducto"] . '</div>';


            $estado = "";
            $icon = "";
            $cancelarpedido = "";
            $editarpedido = "";
            $entregarpedido = "";

            if ($producto["estadoPedidoproducto"] == "SOLICITADO") {
                $estado = "info";
                $icon = '<i class="fa fa-asterisk fa-2x" style="font-size:25px;color:white;" aria-hidden="true"></i>';
                $cancelarpedido = "<button class=\"btn btn-primary cancelarPedido\" style=\"border: 1px solid;\"><i class='fa fa-times' aria-hidden='true'></i> Cancelar pedido</button>";
                if ($producto["nombreMenu"] != "Bebidas") {
                    $editarpedido = "<button class=\"btn btn-primary editarPedido\" style=\"border: 1px solid;\"><i class='fas fa-edit' aria-hidden='true'></i> Editar pedido</button>";
                }
                $entregarpedido = "";
            } elseif ($producto["estadoPedidoproducto"] == "EN PROCESO") {
                $estado = "warning";
                $icon = '<i class="fas fa-sync-alt fa-spin fa-2x fa-fw" style="font-size:25px;color:white;"></i>';
                $cancelarpedido = "";
                $editarpedido = "";
                $entregarpedido = "";
            } elseif ($producto["estadoPedidoproducto"] == "LISTO PARA ENTREGAR") {
                $estado = "success";
                $icon = '<i class="fa fa-check" style="font-size:25px;color:white;" aria-hidden="true"></i>';
                $cancelarpedido = "";
                $editarpedido = "";
                $entregarpedido = "<button class=\"btn btn-primary pedidoEntregado\" style=\"border: 1px solid;\"><i class='fa fa-thumbs-o-up' aria-hidden='true'></i> Pedido entregado</button>";
            } elseif ($producto["estadoPedidoproducto"] == "ENTREGADO") {
                $estado = "default";
                $icon = '<i class="fa fa-thumbs-o-up" aria-hidden="true" style="font-size:25px;color:black;"></i>';
                $cancelarpedido = "";
                $editarpedido = "";
                $entregarpedido = "";
            }




            if ($producto["nombreMenu"] == "Pizzas") {
                $htmlPedido .= '<div class="list-group-item btn-' . $estado . '" style="font-weight:bold;border: 2px solid #7a7a7a; color:#434a54;">' .
                        "<p style='font-size:25px;'>" . $producto["nombreProducto"] . "</p>" .
                        "<p style='font-size:15px;font-weight:bold;'>" . $producto["descripcionPedidoproducto"] . "</p>" .
                        "<p style='position:absolute;top:12px;right:10px;'>" . $icon . "</p>";

                //ASIGNAMIENTO A TABLA DEL PEDIDO PRODUCTO Y DEL PEDIDO PRODUCTO COMBINADO
                $htmlPedido .= '<table class="table table-bordered">' .
                        '<thead>' .
                        '<tr>' .
                        '<th style="background: rgba(255, 255, 255,0.4);color: black;">Pizza</th>' .
                        '<th style="background: rgba(255, 255, 255,0.4);color: black;">Ingredientes</th>' .
                        '</tr>' .
                        '</thead>' .
                        '<tbody>';


                $idPedidoProducto = $producto["idPedidoproducto"];
                $htmlPedido .= '<tr><td style="background: rgba(255, 255, 255,0.2);color: black;">' . $producto["nombreSubmenu"] . '</td>';
                $q = "SELECT * FROM pedprod_ing ppi join ingrediente i on(ppi.idIngrediente = i.idIngrediente) WHERE ppi.idPedidoproducto = '$idPedidoProducto'";

                $result = $conn->query($q);
                if (!$result)
                    die($conn->error);

                $rows = $result->num_rows;
                $ingredientesProducto = array();

                for ($i = 0; $i < $rows; $i++) {
                    $result->data_seek($i);
                    $ingredientesProducto[] = $result->fetch_array(MYSQLI_ASSOC);
                }

                if ($rows != 0) {
                    $htmlPedido .= '<td style="background: rgba(255, 255, 255,0.2);color: black;">' .
                            '<ul style="list-style-type: none;">';

                    foreach ($ingredientesProducto as $ingrediente) {
                        $cantidad = $ingrediente["cantidadPedProd_ing"];
                        if ($ingrediente["opPedprod_ing"] == "agrega") {
                            $htmlPedido .= '<li> (+' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                        } else
                        if ($ingrediente["opPedprod_ing"] == "quita") {
                            $htmlPedido .= '<li> (-' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                        }
                    }
                    $htmlPedido .= '</ul>' .
                            '</td>';
                } else {
                    $htmlPedido .= '<td style="background: rgba(255, 255, 255,0.2);color: black;"><center>Sin ingredientes personalizados</center></td>';
                }


                if ($producto["descripcionPedidoproducto"] == "Combinada 1/2" || $producto["descripcionPedidoproducto"] == "Combinada 1/4" || $producto["descripcionPedidoproducto"] == "Personalizada") {

                    $detalle = "";

                    if ($producto["descripcionPedidoproducto"] == "Combinada 1/2") {
                        $detalle = "(1/2)";
                    } else
                    if ($producto["descripcionPedidoproducto"] == "Combinada 1/4") {
                        $detalle = "(1/4)";
                    } else
                    if ($producto["descripcionPedidoproducto"] == "Personalizada") {
                        $detalle = "(Pers.)";
                    }

                    //PARA CONSULTAR LOS PEDIDOS PRODUCTOS COMBINADOS DE LA PIZZA
                    $q = "SELECT * FROM pedidoproductocombinado ppc join producto p on(p.idProducto = ppc.idProducto) join submenu sm on(p.idSubMenu = sm.idSubMenu) join menu m on (sm.idMenu = m.idMenu) WHERE ppc.idPedidoproducto = '$idPedidoProducto'";
                    $result = $conn->query($q);
                    if (!$result)
                        die($conn->error);

                    $rows = $result->num_rows;
                    $productosCombinados = array();

                    for ($i = 0; $i < $rows; $i++) {
                        $result->data_seek($i);
                        $productosCombinados[] = $result->fetch_array(MYSQLI_ASSOC);
                    }

                    if ($rows != 0) {
                        $contador = 1;
                        foreach ($productosCombinados as $productocombinado) {

                            $htmlPedido .= '<tr><td style="background: rgba(255, 255, 255,0.2);color: black;">' . $productocombinado["nombreSubmenu"] . " " . $detalle . '</td>';


                            $idPedidoproductocombinado = $productocombinado["idPedidoproductocombinado"];

                            $htmldiv .= '<div style="display:none;" class="idpedidoproductocombinado' . $contador . '">' . $idPedidoproductocombinado . '</div>';
                            $htmldiv .= '<div style="display:none;" class="nombrepedidoproductocombinado' . $contador . '">' . $productocombinado["nombreProducto"] . '</div>';
                            $htmldiv .= '<div style="display:none;" class="submenupedidoproductocombinado' . $contador . '">' . $productocombinado["nombreSubmenu"] . '</div>';

                            $contador++;

                            $q = "SELECT * FROM pedprodcomb_ing ppci join ingrediente i on(ppci.idIngrediente = i.idIngrediente) WHERE ppci.idPedidoproductocombinado = '$idPedidoproductocombinado'";

                            $result = $conn->query($q);
                            if (!$result)
                                die($conn->error);

                            $rows = $result->num_rows;
                            $ingredientesProductoCombinado = array();

                            for ($i = 0; $i < $rows; $i++) {
                                $result->data_seek($i);
                                $ingredientesProductoCombinado[] = $result->fetch_array(MYSQLI_ASSOC);
                            }

                            if ($rows != 0) {

                                $htmlPedido .= '<td style="background: rgba(255, 255, 255,0.2);color: black;"><ul style="list-style-type: none;">';

                                foreach ($ingredientesProductoCombinado as $ingrediente) {
                                    $cantidad = $ingrediente["cantidadPedProdcomb_ing"];
                                    if ($ingrediente["opPedprodcomb_ing"] == "agrega") {
                                        $htmlPedido .= '<li> (+' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                                    } else
                                    if ($ingrediente["opPedprodcomb_ing"] == "quita") {
                                        $htmlPedido .= '<li> (-' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                                    }
                                }
                                $htmlPedido .= '</ul></td>';
                                '<td>' . $productocombinado["nombreProducto"] . '</td></tr>';
                            } else {
                                $htmlPedido .= '<td style="background: rgba(255, 255, 255,0.2);color: black;"><center>Sin ingredientes personalizados</center></td>';
                            }
                        }
                    }
                }
            } elseif ($producto["nombreMenu"] == "Ensaladas y Bocaditos" || $producto["nombreMenu"] == "Pastas" || $producto["nombreMenu"] == "Carnes" || $producto["nombreMenu"] == "Crepes y Postres") {

                $htmlPedido .= '<div class="list-group-item btn-' . $estado . '" style="border: 2px solid #7a7a7a;color:#434a54;">' .
                        "<p style='font-size:25px;font-weight:bold;'>" . $producto["nombreProducto"] . "</p>" .
                        "<p style='position:absolute;top:12px;right:10px;'>" . $icon . "</p>";

                $idPedidoProducto = $producto["idPedidoproducto"];

                $q = "SELECT * FROM pedprod_ing ppi join ingrediente i on(ppi.idIngrediente = i.idIngrediente) WHERE ppi.idPedidoproducto = '$idPedidoProducto'";

                $result = $conn->query($q);
                if (!$result)
                    die($conn->error);

                $rows = $result->num_rows;
                $ingredientesProducto = array();

                for ($i = 0; $i < $rows; $i++) {
                    $result->data_seek($i);
                    $ingredientesProducto[] = $result->fetch_array(MYSQLI_ASSOC);
                }

                if ($rows != 0) {

                    //ASIGNAMIENTO A TABLA DEL PEDIDO PRODUCTO Y DEL PEDIDO PRODUCTO COMBINADO
                    $htmlPedido .= '<table class="table table-bordered" style="font-weight:bold;">' .
                            '<thead>' .
                            '<tr>' .
                            '<th style="background: rgba(255, 255, 255,0.4);color: black;">Producto</th>' .
                            '<th style="background: rgba(255, 255, 255,0.4);color: black;">Ingredientes</th>' .
                            '</tr>' .
                            '</thead>' .
                            '<tbody>';

                    $htmlPedido .= '<tr><td style="background: rgba(255, 255, 255,0.2);color: black;">' . $producto["nombreProducto"] . '</td>';

                    $htmlPedido .= '<td style="background: rgba(255, 255, 255,0.2);color: black;">' .
                            '<ul style="list-style-type: none;">';

                    foreach ($ingredientesProducto as $ingrediente) {
                        $cantidad = $ingrediente["cantidadPedProd_ing"];
                        if ($ingrediente["opPedprod_ing"] == "agrega") {
                            $htmlPedido .= '<li> (+' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                        } else
                        if ($ingrediente["opPedprod_ing"] == "quita") {
                            $htmlPedido .= '<li> (-' . $cantidad . ') ' . $ingrediente["nombreIngrediente"] . '</li>';
                        }
                    }
                    $htmlPedido .= '</ul>' .
                            '</td>';
                }
            } elseif ($producto["nombreMenu"] == "Bebidas") {

                $htmlPedido .= '<div class="list-group-item btn-' . $estado . '" style="border: 2px solid #7a7a7a;color:#434a54;">' .
                        "<p style='font-size:25px;font-weight:bold;'>" . $producto["nombreProducto"] . "</p>" .
                        "<p style='position:absolute;top:12px;right:10px;'>" . $icon . "</p>";
            }

            $htmlPedido .= '</tbody>' . '</table>';

            $htmlPedido .= "<div style=\"text-align: -webkit-right;\">
        <h3>Cantidad : <small style=\"font-size: 20px;color: black;font-weight: bold;\">" . $producto["cantidadPedidoproducto"] . "</small></h3>";

            if ($producto["observacionPedidoproducto"]) {
                $htmlPedido .= "<h3>Observaciones : <small style=\"font-size: 20px;color: black;font-weight: bold;\">" . $producto["observacionPedidoproducto"] . "</small></h3>";
            }

            $htmlPedido .= "</div>";

            $htmlPedido .= "<div class=\"list-group-controls\" style='text-align:center;'>" .
                    $cancelarpedido .
                    $editarpedido .
                    $entregarpedido .
                    "</div>" .
                    $htmldiv;
            $htmlPedido .= "</div>";
        }
        echo $htmlPedido;

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          CANCELAMOS EL PEDIDO SELECCIONADO           //
    if ($method == 'cancelaPedido') {

        $idpedidoproducto = $_POST["idpedidoproducto"];
        $descripcionpedidoproducto = $_POST["descripcionpedidoproducto"];
        $menupedidoproducto = $_POST["menupedidoproducto"];
        $numeromesa = $_POST["numeromesa"];
        $idpedido = $_POST["idpedido"];

        if ($menupedidoproducto != "Bebidas") {
            if ($descripcionpedidoproducto == "Combinada 1/2" || $descripcionpedidoproducto == "Combinada 1/4") {
                $idpedidoproductocombinado1 = $_POST["idpedidoproductocombinado1"];

                //eliminacion de ingredientes de pedido producto combinado 1
                $query = "DELETE FROM pedprodcomb_ing WHERE idPedidoproductocombinado = '$idpedidoproductocombinado1'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                //eliminacion de pedido producto combinado 1
                $query = "DELETE FROM pedidoproductocombinado WHERE idPedidoproductocombinado = '$idpedidoproductocombinado1'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }

                //ELIMINACION DEL PEDIDO PRODUCTO
                //eliminacion de ingredientes de pedido producto combinado 1
                $query = "DELETE FROM pedprod_ing WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                $query = "DELETE FROM pedidoproducto WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }
            }
            if ($descripcionpedidoproducto == "Personalizada") {

                $idpedidoproductocombinado1 = $_POST["idpedidoproductocombinado1"];
                $idpedidoproductocombinado2 = $_POST["idpedidoproductocombinado2"];
                $idpedidoproductocombinado3 = $_POST["idpedidoproductocombinado3"];

                //eliminacion de ingredientes de pedido producto combinado 1
                $query = "DELETE FROM pedprodcomb_ing WHERE idPedidoproductocombinado = '$idpedidoproductocombinado1'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                //eliminacion de pedido producto combinado 1
                $query = "DELETE FROM pedidoproductocombinado WHERE idPedidoproductocombinado = '$idpedidoproductocombinado1'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }

                //eliminacion de ingredientes de pedido producto combinado 2
                $query = "DELETE FROM pedprodcomb_ing WHERE idPedidoproductocombinado = '$idpedidoproductocombinado2'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                //eliminacion de pedido producto combinado 2
                $query = "DELETE FROM pedidoproductocombinado WHERE idPedidoproductocombinado = '$idpedidoproductocombinado2'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }

                //eliminacion de ingredientes de pedido producto combinado 3
                $query = "DELETE FROM pedprodcomb_ing WHERE idPedidoproductocombinado = '$idpedidoproductocombinado3'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                //eliminacion de pedido producto combinado 3
                $query = "DELETE FROM pedidoproductocombinado WHERE idPedidoproductocombinado = '$idpedidoproductocombinado3'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }


                //ELIMINACION DEL PEDIDO PRODUCTO
                //eliminacion de ingredientes de pedido producto combinado 1
                $query = "DELETE FROM pedprod_ing WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                $query = "DELETE FROM pedidoproducto WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }
            }
            if ($descripcionpedidoproducto == "Unitario" || $descripcionpedidoproducto == "entera") {

                //ELIMINACION DEL PEDIDO PRODUCTO
                //eliminacion de ingredientes de pedido producto combinado 1
                $query = "DELETE FROM pedprod_ing WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al eliminar. ' . $conn->error;
                }

                $query = "DELETE FROM pedidoproducto WHERE idPedidoproducto = '$idpedidoproducto'";
                $res = $conn->query($query);

                if (!$res) {
                    echo $res = 'Error al ingresar. ' . $conn->error;
                }
            }
        } else {

            //ELIMINACION DEL PEDIDO PRODUCTO

            $query = "DELETE FROM pedidoproducto WHERE idPedidoproducto = '$idpedidoproducto'";
            $res = $conn->query($query);

            if (!$res) {
                echo $res = 'Error al ingresar. ' . $conn->error;
            }
        }


        $query = "SELECT * from mesa m JOIN pedido p on(m.idMesa = p.idMesa) JOIN pedidoproducto pp on(pp.idPedido = p.idPedido) WHERE p.idPedido = '$idpedido'";

        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;

        if ($rows == 0) {

            //ELIMINACION DEL PEDIDO PRODUCTO
            $query = "DELETE FROM pedido WHERE idPedido = '$idpedido'";
            $res = $conn->query($query);

            if (!$res) {
                echo $res = 'Error al ingresar. ' . $conn->error;
            }

            //HABILITACION DE LA MESA
            $query = "UPDATE `mesa` SET `estadoMesa`= 'HABILITADA' WHERE numeroMesa = '$numeromesa'";
            $res = $conn->query($query);

            if (!$res) {
                echo $res = 'Error al ingresar. ' . $conn->error;
            }
        }

        echo $rows;

        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          Consultamos los ingredinetes de un Pedido           //
    if ($method == 'consultaIngredientesE') {
        $idproducto = $_POST["idproducto"];
        $query = "SELECT * FROM ingrediente i "
                . " JOIN productoingrediente ip ON (i.idIngrediente = ip.idIngrediente) "
                . " WHERE ip.idProducto like '$idproducto' "
                . " ORDER BY nombreIngrediente ASC";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $ingredientes = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $ingredientes[] = $result->fetch_array(MYSQLI_ASSOC);
        }
        if ($rows != 0) {
            $json['ing'] = $ingredientes;
            $output = ob_get_contents();
            ob_end_clean();
            $json['status'] = 'yes';
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['result'] = '';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          Consultamos los ingredinetes Generales para esa categoria           //
    if ($method == 'consultaIngredientesG') {

        $tipoIngrediente = $_POST["tipoIngrediente"];
        if ($tipoIngrediente == "Crepes y Postres") {
            $query = "SELECT * FROM ingrediente where tipoIngrediente = '$tipoIngrediente' order by nombreIngrediente ASC";
        } else {
            $query = "SELECT * FROM ingrediente where tipoIngrediente = 'General' or tipoIngrediente = '$tipoIngrediente' order by nombreIngrediente ASC";
        }
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $rows = $result->num_rows;
        $ingredientes = array();
        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $ingredientes[] = $result->fetch_array(MYSQLI_ASSOC);
        }
        if ($rows != 0) {
            $json['ings'] = $ingredientes;
            $output = ob_get_contents();
            ob_end_clean();
            $json['status'] = 'yes';
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['result'] = '';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          OBTENEMOS LOS PRODUCTOS          //
    if ($method == 'getProductos') {

        $idsubmenu = $_POST["idsubmenu"];

        $query = "SELECT * FROM producto where idSubmenu like '$idsubmenu'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);

        $rows = $result->num_rows;
        $contentMenu = array();

        for ($i = 0; $i < $rows; $i++) {
            $result->data_seek($i);
            $contentMenu[] = $result->fetch_array(MYSQLI_ASSOC);
        }

        if ($rows != 0) {
            $json['productos'] = $contentMenu;
            $json['status'] = 'yes';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['result'] = 'No se ha encontrado contenido de tal menú';
            $json['status'] = 'no';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //                  OBTENEMOS EL SUBMENU DE LA PIZZA            //
    if ($method == 'getIdperfil') {

        $idsubmenu = $_POST["idsubmenu"];
        $query = "SELECT * FROM submenu sm join menu m on (m.idMenu=sm.idMenu) where sm.idSubmenu like '$idsubmenu'";
        $result = $conn->query($query);
        if (!$result)
            die($conn->error);
        $result->data_seek(0);
        $menu = $result->fetch_array(MYSQLI_ASSOC);
        $json['menu'] = $menu;
        $json['status'] = 'yes';
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }
}

if ($_GET) {
    $method = broom('reg', $_GET['meth']);
}

//   Si no se llamó ningún método de la API     //
var_dump($_POST);
var_dump($_GET);
var_dump($_FILES);
$output = ob_get_contents();
$json['msg'] = "Silent script";
$json['output'] = $output;
ob_end_clean();
echo json_encode($json);
return;
?>