<?php
/*        
 *          ***********************************************************
 * 	        *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *	        @date           2019-03-22
 *          @author         Bayman Burton <bayman@burtonservers.com>
 *          @copyright      2015-2019 Burton Tech
 *          @license        https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *	        Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */


//////////////////  DEBUG EN PANTALLA   ////////////////

error_reporting(E_ALL);
ini_set('display_errors', 1); 


//////////////////  HABILITAMOS EL ACCESO PUBLICO PARA REALIZAR LLAMADAS AJAX DESDE DOMINIOS PUBLICOS   //////////////////
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Auth-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS');

header('Content-type: application/javascript; charset=utf-8');

//////////////////   ES IMPORTANTE RESCATAR TODO EL OUTPUT  //////////////////
/* LUEGO PODEMOS PROMPTEARLO EN PANTALLA CON
 * $output = ob_get_contents(); ob_end_clean();
 */
ob_start();

//////////////////   INCLUDES   //////////////////
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'assets/plugins/PHPMailer/src/Exception.php';
require 'assets/plugins/PHPMailer/src/PHPMailer.php';
require 'assets/plugins/PHPMailer/src/SMTP.php';
require_once 'assets/scripts/funcs.php';

//////////////////   Creamos el enlace con la DB    //////////////////
require("assets/scripts/conn.php");

//////////////////                  INICIAMOS               //////////////////
date_default_timezone_set('America/Guayaquil');

$select = "TRUNCATE TABLE usuarios;";
$result = $dblink->query($select) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $select . "', 'error' : '" . $dblink->error . "'}");

$select2 = "TRUNCATE TABLE detalleUsuarios; ";
$result2 = $dblink->query($select2) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $select2 . "', 'error' : '" . $dblink->error . "'}");

$select3 = "TRUNCATE TABLE visitas;";
$result3 = $dblink->query($select3) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $select3 . "', 'error' : '" . $dblink->error . "'}");

$select4 = "TRUNCATE TABLE followUsuarios;";
$result4 = $dblink->query($select4) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $select4 . "', 'error' : '" . $dblink->error . "'}");

$select5 = "TRUNCATE TABLE notify;";
$result5 = $dblink->query($select5) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $select5 . "', 'error' : '" . $dblink->error . "'}");

if ($result && $result2 && $result3 && $result4 && $result5) {
    echo "Sistema Purificado";
    return;
} else {
    echo "Error de Query";
    return;
}

?>