<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script>
//        $(".customalert_text").html("awdawdawdawd");
//        $(".customalert").animate({width: 'toggle'}, 600);

    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".newpedido").addClass("active");

    $(document).ready(function () {
        updateMenu();
    });

    $(document).on("click", ".editjobbtn", function (event) {
        event.preventDefault();
        var self, idJob, typeJob, iconJob, catJob, titleJob, statusJob, commpanyJob, fromJob, toJob, descJob;
        self = this;
        idMenu = $(this).parent().parent().find(".idMenuCont").html();
        nombreMenu = $(this).parent().parent().find(".nombreMenuCont").html();
        statusMenu = $(this).parent().parent().find(".statusMenu").html();
        $.when(
                $(self).find(".beforeLoad, .loading_img").toggle("slow"))
                .then(function () {
                    if (statusMenu == 'ACTIVO') {
                        $(".editjobcheckbox").html('<input type="checkbox" class="switch" name=""  value="1" checked="checked" /><span></span>');
                    } else {
                        $(".editjobcheckbox").html('<input type="checkbox" class="switch" name=""  value="0" /><span></span>');
                    }
                    $("#editcompanyJob").val(nombreMenu);
                    $("#editidJobContainer").html(idMenu);
                    setTimeout(function () {
                        $.when(
                                $(".joblist,.newjob").slideUp("slow")
                                ).then(function () {
                            $(".editjob,.showlistbtn").slideDown("slow");
                            $(self).find(".beforeLoad, .loading_img").toggle("slow");
                        });
                    }, 1000);
                });
    });

    $(document).on("click", ".savechanges_btn", function (event) {
        event.preventDefault();
        var self = this;
        $(self).find("span, img").toggle("slow");
        setTimeout(function () {
            var formData = new FormData(),
                    nombreMenu = $("#editcompanyJob").val();
            if (nombreMenu != '') {
                formData.append('meth', 'editMenu');
                formData.append('idMenu', $("#editidJobContainer").html());
                formData.append('nombreMenu', nombreMenu);
                $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                    success: function (data) {
                        if (data.status == 'yes') {
                            $(".customalert_text").html("Menu editado exitosamente");
                            $(".customalert").animate({width: 'toggle'}, 600);
                            $(self).find("span, img").toggle("slow");
                            $.when(
                                    $(".editjob,.showlistbtn,.newjob").slideUp("slow")
                                    ).then(function () {
                                $(".joblist").slideDown("slow");
                            });
                            updateMenu();
                        } else {
                            $(".customalert_text").html("No pudimos editar el menu, intente de nuevo");
                            $(".customalert").animate({width: 'toggle'}, 600);
                            $(self).find("span, img").toggle("slow");
                            console.log(data);
                        }
                    },
                    error: function (error) {
                        console.log("Hubo un error de internet, intente de nuevo");
                        console.log(error);
                    }
                });
            } else {
                $(self).find("span, img").toggle("slow");
                $(".customalert_text").html("No puedes dejar los campos en blanco");
                $(".customalert").animate({width: 'toggle'}, 600);
            }
        }, 1000);
    });

    var plsStop = 0;
    $(document).on("click", ".editjobcheckbox", function (event) {
        if (plsStop == 0) {
            plsStop = 1;
        } else {
            plsStop = 0;
            return;
        }
        //        event.preventDefault();
        var self = this;
        var status = '';
        setTimeout(function () {
            if ($(self).find('input').is(':checked')) {
                status = '1';
            } else {
                status = '0';
            }
            var formData = new FormData();
            formData.append('meth', 'changestatusMenu');
            formData.append('statusJob', status);
            formData.append('idMenu', $('#editidJobContainer').html());
            $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                success: function (data) {
                    if (data.status == 'yes') {
                        $(".customalert_text").html("Menu actualizada exitosamente");
                        $(".customalert").animate({width: 'toggle'}, 600);
                        updateMenu();
                    } else {
                        $(".customalert_text").html("No pudimos actualizar el menu, intente de nuevo");
                        $(".customalert").animate({width: 'toggle'}, 600);
                        console.log(data);
                    }
                },
                error: function (error) {
                    $(self).find("span, img").toggle("slow");
                    console.log("Hubo un error de internet, intente de nuevo");
                    console.log(error);
                }
            });
        }, 2000);
    });

    $(document).on("click", ".deletejob", function (event) {
        event.preventDefault();
        var id = $("#editidJobContainer").html();
        var self = this;
        noty({
            text: 'Seguro que quieres eliminar el Menu?',
            layout: 'topRight',
            buttons: [
                {addClass: 'btn btn-success btn-clean', text: 'Si', onClick: function ($noty) {
                        $(self).find("span, img").toggle("slow");
                        setTimeout(function () {
                            var formData = new FormData();
                            formData.append('meth', 'deleteMenu');
                            formData.append('deleteid', id);

                            $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                                success: function (data) {
                                    if (data.status == 'yes') {
                                        $(".customalert_text").html("Menu eliminado exitosamente");
                                        $(".customalert").animate({width: 'toggle'}, 600);
                                        $(self).find("span, img").toggle("slow");
                                        $.when(
                                                $(".editjob,.showlistbtn,.newjob").slideUp("slow")
                                                ).then(function () {
                                            $(".joblist").slideDown("slow");
                                        });
                                        updateMenu();
                                    } else {
                                        $(self).find("span, img").toggle("slow");
                                        $(".customalert_text").html("No pudimos eliminar el menu, intente de nuevo");
                                        $(".customalert").animate({width: 'toggle'}, 600);
                                        console.log(data);
                                    }
                                },
                                error: function (error) {
                                    $(self).find("span, img").toggle("slow");
                                    console.log("Hubo un error de internet, intente de nuevo");
                                    console.log(error);
                                }
                            });
                        }, 1000);
                    }
                },
                {addClass: 'btn btn-danger btn-clean', text: 'Cancelar', onClick: function ($noty) {
                        $noty.close();
                    }
                }
            ]
        }).setTimeout(4000);
    });

    $(document).on("click", ".savenewjob", function (event) {
        event.preventDefault();
        var self = this;
        $(self).find(" span, img").toggle("slow");
        setTimeout(function () {
            var formData = new FormData(),
                    nombreMenu = $("#newcompanyJob").val();

            if (nombreMenu != '') {
                formData.append('meth', 'addnewMenu');
                formData.append('nombreMenu', nombreMenu);
                $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                    success: function (data) {
                        if (data.status == 'yes') {
                            $(".customalert_text").html("Menu agregado exitosamente");
                            $(".customalert").animate({width: 'toggle'}, 600);
                            $(self).find("span, img").toggle("slow");
                            $.when(
                                    $(".editjob,.showlistbtn,.newjob").slideUp("slow")
                                    ).then(function () {
                                $(".joblist").slideDown("slow");
                            });
                            updateMenu();
                        } else {
                            $(self).find("span, img").toggle("slow");
                            $(".customalert_text").html("No pudimos agregar el menu, intente de nuevo");
                            $(".customalert").animate({width: 'toggle'}, 600);
                            console.log(data);
                        }
                    },
                    error: function (error) {
                        $(self).find("span, img").toggle("slow");
                        console.log("Hubo un error de internet, intente de nuevo");
                        console.log(error);
                    }
                });
            } else {
                $(self).find("span, img").toggle("slow");
                $(".customalert_text").html("No puedes dejar los campos en blanco");
                $(".customalert").animate({width: 'toggle'}, 600);
            }
        }, 1000);
    });

    $(document).on("click", ".disabledswitch", function (event) {
        event.preventDefault();
    });

    $(document).on("click", ".addnewbtn", function (event) {
        event.preventDefault();
        $.when(
                $(".joblist,.editjob").slideUp("slow")
                ).then(function () {
            $(".newjob,.showlistbtn").slideDown("slow");
        });
    });

    $(document).on("click", ".showlistbtn", function (event) {
        event.preventDefault();
        $.when(
                $(".editjob,.showlistbtn,.newjob").slideUp("slow")
                ).then(function () {
            $(".joblist").slideDown("slow");
        });
    });

    function updateMenu() {
        var formData = new FormData();
        formData.append('meth', 'getMenuList');
        $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
            success: function (data) {
                $('.joblist').html(data.output);
                $(document).find(".menuItemBlock").delay(500).velocity("transition.slideUpBigIn", {stagger: 100});
                console.log(data);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

</script>