<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */

// DEBUG EN PANTALLA //
//error_reporting(E_ALL);
//ini_set('display_errors', 1);

/* DESPLEGAMOS TODA LA CONFIG   // */
require ("assets/scripts/config.php");
?>
<!DOCTYPE html>
<html lang="es">
    <head>        
        <title>DROOM - Sistema inteligente de control de Restaurantes</title>            
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/img/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="assets/node_modules/dragula/dist/dragula.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="assets/css/reset.css">
        <link rel="stylesheet" href="assets/css/supersized.css">
        <link rel="stylesheet" type="text/css" id="theme" href="assets/css/theme-red.css"/>
        <link rel="stylesheet" type="text/css" href="assets/css/custom.css"/>
    </head>
    <?php
    if ($page == 'login') {
        echo '<body class="login">';
        require ("assets/views/login.php");
    } else {
        echo '<body class="' . $fullwidth . ' ">' . $videoTag . '<div class="page-container  ' . $sidebar . '">';
        require ("assets/views/sidebar.php");
        ?>
        <div class="page-content" style="height: 100%;">
            <?php require ("assets/views/statusbar.php"); ?>          
            <!--PANEL A MOSTRAR-->                      
            <?php require ("modules/" . $module . "/view.php"); ?>                           
        </div>
    </div>

    <?php
    if ($module == "dashboard") {
        require ("assets/dashboard/rightbar.php");
    }
}

require ("assets/scripts/pagescripts.php");
?>
</body>
</html>