<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".caja").addClass("active");
    $(document).ready(function () {
        asignaPedidosCocina();
        asignaPedidosPorCancelar();
        pedidoscancelados();
        consultarTurno();
    });

    $(document).on('click', '.Pedido', function () {
        var self = this;
        pageLoadingFrame("show");
        var isClosed = $('.isCajaCerrada').html();
        setTimeout(function () {
            if (isClosed == 'si') {
                pageLoadingFrame("hide");
                $(".customalert_text").html("Debe aperturar la caja");
                $(".customalert").animate({width: 'toggle'}, 600);
                return;
            } else {
                var idmesa = $(self).find(".idmesa").html();
                var idpedido = $(self).find(".idpedido").html();
                var numeromesa = $(self).find(".numeromesa").html();
                var formData = new FormData();
                formData.append('idmesa', idmesa);
                formData.append('numeromesa', numeromesa);
                formData.append('idpedido', idpedido);
                formData.append('meth', 'asignaMesa');
                $.ajax({
                    url: 'api/api.php',
                    type: 'POST',
                    dataType: "json",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (data) {
                        window.location.replace("/?show=caja/factura");
                    },
                    error: function (error) {
                        console.log("Hubo un error de internet, intente de nuevo");
                        console.log(error);
                    }
                });
            }
        }, 1000);

    });

    function asignaPedidosCocina() {
        $.ajax({
            // Verificacion de los datos introducidos
            url: 'assets/caja/pedidoscocina.php',
            type: 'POST',
            dataType: "json",
            data: {
                cocina: "true",
            },
            success: function (html) {
                $("#pedidosCocina").html(html.pedidos);
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    function asignaPedidosPorCancelar() {
        $.ajax({
            // Verificacion de los datos introducidos
            url: 'assets/caja/pedidosporcancelar.php',
            type: 'POST',
            success: function (html) {
                $("#pedidosPorCancelar").html(html);
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    function pedidoscancelados() {
        $.ajax({
            // Verificacion de los datos introducidos
            url: 'assets/caja/pedidoscancelados.php',
            type: 'POST',
            success: function (html) {
                $("#pedidoscancelados").html(html);
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////ACTIVAMOS EL EVENTO DEL BUSCADOR DE FACTURAS
    $("#search_pedidos").keyup(function (e) {
        var code = e.which;
        if (code == 13)
            e.preventDefault();
        if (code == 32 || code == 13 || code == 188 || code == 186) {
            var inputvalue = $("#search_pedidos").val();
            inputvalue = inputvalue.split(': ');
            if (inputvalue[3] == null) {
                $('#modal_consultar_factura .modal-dialog .modal-content .modal-header .modal-title').html('<i class="fa fa-exclamation-circle"></i> Alerta</h4>');
                $('#modal_consultar_factura .modal-dialog .modal-content .modal-body').html('<p></p>');
                $('#modal_consultar_factura .modal-dialog .modal-content .modal-body p').html('No se ha seleccionado ninguna factura para mostrar');
                $('#modal_consultar_factura').modal('toggle');
            } else {
                var idfactura = inputvalue[1].split(' - ');
                window.location.href = "/?show=caja&verfactura=" + idfactura[0];
            }
        }
    });

    ////////////////////////////////////////////////////////////////////////////FUNCION PARA MOSTRAR EL PEDIDO INGRESADA
    function consultarpeddo(idpedido) {
        $.ajax({
            url: 'assets/factura/consultaProductos.php',
            type: 'POST',
            data: {
                idpedido: idpedido,
            },
            success: function (html) {
                $(".tablaconsultarfactura").html(html);
                $(".consultafacturatabla tr:even").css("background-color", "rgba(169, 169, 169, 0.45)");
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////FUNCION PARA MOSTRAR LA FACTURA INGRESADA
    function consultarfactura(idfactura) {
        $.ajax({
            url: 'assets/caja/consultafactura.php',
            type: 'POST',
            data: {
                idfactura: idfactura,
            },
            success: function (html) {
                $("#verfactura_datos").html(html);
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////////MANDAMOS LA FACTURA A PDF
    function exporttopdftable() {
        //    $('.tablaDescripcion table').tableExport({type:'pdf',escape:'false'});
        var output = "";
        output += "<tr><td> =========================================== <br /></td></tr> \n\ ";
        output += "<tr><td> PRODUCTO        | CANT | V.UNIT. | V.TOTAL <br/></td></tr> \n\ ";
        output += "<tr><td> =========================================== <br /></td></tr> \n\ ";
        $(".consultafacturatabla tr").each(function () {
            if ($(this).find('td:eq(0)').length > 0) {
                output += " <tr><td> ";
                output += $(this).find('td:eq(0) strong').html();
                output += " | ";
                output += $(this).find('td:eq(1)').html();
                output += " | ";
                output += $(this).find('td:eq(2)').html();
                output += " | ";
                output += $(this).find('td:eq(3) span').html();
                output += " <br /> \n\ </td></tr>";
            }
        });
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        output += "<tr><td> SUBTOTAL: " + $(".verfactura_subtotal").html() + " <br /></td></tr> \n\ ";
        output += "<tr><td> IVA: " + $(".verfactura_iva").html() + " <br /></td></tr> \n\ ";
        output += "<tr><td> TOTAL: " + $(".verfactura_total").html() + " <br /></td></tr> \n\ ";
//    output += "<tr><td> MESA : " + numeromesa + "<br /></td></tr> \n\ ";
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        output += "<tr><td> ====== GRACIAS POR SU VISITA ====== <br /></td></tr> \n\ ";
        var date = new Date();
        days = parseInt(2);
        var day = date.getDate();
        var month = date.getMonth();
        month = month + 1;
        var year = date.getFullYear();
        if (day < 10) {
            day = "0" + day;
        }
        if (month < 10) {
            month = "0" + month;
        }
        $.ajax({
            url: 'assets/factura/getMesaPedido.php',
            dataType: "json",
            success: function (msg) {
                var name = $(".verfactura_nombrecliente").html();
                var ruc = $(".verfactura_ruc").html();
                var namesplit = name.split('>');
                var rucsplit = ruc.split('>');
                $("#facturaimpresa tbody").append("<tr><td> Local: PIZZERIA DIRULO VILLAFLORA | Ruc: 1734230049001 Tel&eacute;fono: ########## </td></tr>");
                $("#facturaimpresa tbody").append("<tr><td> Fecha: " + $(".verfactura_fecha").html() + " </td></tr>");
                $("#facturaimpresa tbody").append("<tr><td> Factura #: " + $(".verfactura_numero").html() + " </td></tr>");
                $("#facturaimpresa tbody").append("<tr><td> Cliente:" + namesplit[2] + "</td></tr>");
                $("#facturaimpresa tbody").append("<tr><td> Ruc:" + rucsplit[2] + "</td></tr>");
                $("#facturaimpresa tbody").append("" + output + "")
                $('#facturaimpresa').css("display", "block");
                $('#facturaimpresa').tableExport({type: 'pdf', escape: 'false'});
                $('#facturaimpresa tbody').html("");
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////////imprimir pedido
    $(document).on('click', '.pedido_imprimir', function (e) {
        if (!e)
            var e = window.event;
        e.cancelBubble = true;
        if (e.stopPropagation)
            e.stopPropagation();
        e.preventDefault();
        var mesa_nro = $(this).parent().parent().find(".numeromesa").html();
        if (mesa_nro == "999") {
            mesa_nro = "Domicilio";
        }
        var pedido_nro = $(this).parent().parent().find(".idpedido").html();
        var output = "";
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        output += "<tr><td> " + mesa_nro + "  <br /></td></tr> \n\ ";
        output += "<tr><td> Pedido # " + pedido_nro + " <br /></td></tr> \n\ ";
        output += "<tr><td> ======================== <br /></td></tr> \n\ ";
        $.ajax({
            // Verificacion de los datos introducidos
            url: 'assets/caja/pedidoscocina.php',
            type: 'POST',
            dataType: "json",
            data: {
                cocina: "print",
                pedido: pedido_nro,
            },
            success: function (html) {
                output += " " + html.pedidos + " ";
                console.log("PEDIDO: " + output);
                output += "<tr><td> ======================== <br /></td></tr> \n\ ";
                $("body").append("<table id='pedido_imprimir'><tbody> " + output + " </tbody></table>");
                $('#pedido_imprimir').tableExport({type: 'pdf', escape: 'false'});
                $('#pedido_imprimir').remove();
                console.log(output);
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    });

    ////////////////////////////////////////////////////////////////////////////AUTOCOMPLETE DE PEDIDOS FACTURADOS
    $(function () {

        var data_1 = [<?php
$select_facturas = "SELECT idFactura,idPedido,cedulaCliente 
                    FROM factura 
                    INNER JOIN cliente ON cliente.idCliente = factura.idCliente
                    WHERE statusFactura = 'ACTIVE'
                    ORDER BY idFactura";
$result_facturas = mysqli_query($conn, $select_facturas);
while ($row_facturas = mysqli_fetch_array($result_facturas, MYSQLI_BOTH)) {
    echo '"Factura#: ' . $row_facturas["idFactura"] . ' - Pedido#: ' . $row_facturas["idPedido"] . ' - Cliente#: ' . $row_facturas["cedulaCliente"] . '",';
}
?>];

        $("#search_pedidos").autocomplete({
            source: data_1,
            open: function (event, ui) {

                var autocomplete = $(".ui-autocomplete:visible");
                var oldTop = autocomplete.offset().top;
                var newTop = oldTop - $("#prod_ac").height() + 25;
                autocomplete.css("top", newTop);

            }
        });
    });

    ///////////////////////////////////////////////////////////////////////////AL ANULAR LA FACTURA
    $(document).on('click', '#anular_factura', function () {
        var idFactura = '<?php echo $_GET["verfactura"] ?>'
        $.ajax({
            url: 'assets/caja/anularfactura.php',
            type: 'POST',
            data: {
                idFactura: idFactura,
            },
            success: function (html) {
                window.location.href = "/?show=caja&verfactura=" + html;
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    });

    ///////////////////////////////////////////////////////////////////////////AL REACTIVAR LA FACTURA
    $(document).on('click', '#reactivar_factura', function () {
        var idFactura = '<?php echo $_GET["verfactura"] ?>'
        $.ajax({
            url: 'assets/caja/reactivarfactura.php',
            type: 'POST',
            data: {
                idFactura: idFactura,
            },
            success: function (html) {
                window.location.href = "/?show=caja&verfactura=" + html;
            },
            error: function (error) {
                console.log('Disculpe, existió un problema');
                console.log(error);
            },
            complete: function (xhr, status) {
                console.log('Petición realizada');
            }
        });
    });

    //              VALIDAMOS  EL NUEVO PEDIDO QUE SE VA A CARGAR Y SI LA MESA YA FUE SELECCIONADA      //
    $(".btnNuevoPedido").click(function () {
        var formData = new FormData();
        formData.append('idmesa', '0');
        formData.append('numeromesa', 'Para llevar');
        formData.append('meth', 'asignaMesa');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                window.location.replace("/?show=pedido");
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    });

    /////////////////////////////////////           CONSULTAMOS EL TURNO DISPONIBLE                     ///////////////
    function consultarTurno() {
        var formData = new FormData();
        formData.append('meth', 'getTurno');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            dataType: "json",
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (data) {
                if (data.status == 'yes') {
                    if (data.lastTurno.tipoTurno == 'apertura') {
                        $('.turnoBox').html('<a href="#" class="list-group-item">'
                                + '<span class="fa fa-circle text-info"></span><span class="turnoName">'
                                + data.lastTurno.nombresUsuario
                                + ' '
                                + data.lastTurno.apellidosUsuario
                                + ' '
                                + data.lastTurno.msgTurno
                                + '</span>'
                                + '<span class="idTurnoCont hidethis">' + data.lastTurno.idTurno + '</span>'
                                + '<span class="montoInicialCont hidethis">' + data.lastTurno.saldoTurno + '</span>'
                                + '</a>'
                                );
                        $('.turnoBox').append('<a href="#" class="list-group-item">'
                                + '<button class="btn btn-primary cerrarTurno"><i class="fas fa-hand-holding-usd"></i> Cerrar Turno</button></a>');
                        $('.turnoBox').append('<a href="api/api.php?meth=report&print=1&idTurno='+data.lastTurno.idTurno+'" class="list-group-item">'
                                + '<button class="btn btn-primary corteX"><i class="fas fa-hand-holding-usd"></i> Emitir corte X</button></a>');
                    } else {
                        $('.turnoBox').html('<a href="#" class="list-group-item">'
                                + '<span class="fa fa-circle text-danger"></span><span class="turnoName"> Caja Cerrada'
                                + '<span class="isCajaCerrada hidethis">si</span>'
                                + '</span><button class="btn btn-primary pull-right abrirTurno"><i class="fas fa-hand-holding-usd"></i> Abrir Turno</button></a>'
                                );
                        $('.turnoBox').append('<a href="api/api.php?meth=report&print=2" class="list-group-item">'
                                + '<button class="btn btn-primary corteZ"><i class="fas fa-hand-holding-usd"></i> Emitir corte Z</button></a>');
                    }
                }
                console.log(data);
            },
            error: function (error) {
                console.log("Hubo un error de internet, intente de nuevo");
                console.log(error);
            }
        });
    }

    ///////////                                                 AL ABRIR UN TURNO                           /////
    $(document).on('click', '.abrirTurno', function () {
        $('#modalPrevCaja .modal-header h4').text('Abrir Turno de Caja');
        $('#modalPrevCaja .modal-body').html('<div class="col-md-12">'
                + ' <h4 style="color:black;text-align: left;">Ingrese PIN:</h4>'
                + ' <div class="input-group">'
                + '     <input id="pinSeguridad" type="password" class="form-control">'
                + '     <div class="input-group-addon"><i class="fas fa-unlock-alt"></i></div>'
                + ' </div>'
                + ' <hr />'
                + ' <h4 style="color:black;text-align: left;">Usuario: <button class="btn btn-info"><?php echo $_SESSION['usuario']['nombresUsuario'] . ' ' . $_SESSION['usuario']['apellidosUsuario'] ?></button></h4>'
                + ' <hr />'
                + ' <h4 style="color:black;text-align: left;">Monto inicial:</h4>'
                + ' <div class="input-group">'
                + '     <input id="montoInicial" type="text" class="form-control" placeholder="Ingrese el monto">'
                + '     <div class="input-group-addon"><i class="fas fa-money-bill-wave"></i></div>'
                + ' </div>'
                + ' <hr />'
                + ' <h4 style="color:black;text-align: left;">Comentario:</h4>'
                + ' <textarea id="comentCaja" class="form-control" placeholder="su comentario"></textarea>'
                + '</div>');
        $('.cargarApertura').remove();
        $('#modalPrevCaja .modal-footer').append('<button type="button" class="btn btn-success pull-right cargarApertura"><i class="fa fa-check" aria-hidden="true"></i> Cargar</button>');
        $('#modalPrevCaja').modal('toggle');
        return;
    });

    ///////////                                                 AL ABRIR UN TURNO                           /////
    $(document).on('click', '.cerrarTurno', function () {
        $('#modalPrevCaja .modal-header h4').text('Cerrar Turno de Caja');
        $('#modalPrevCaja .modal-body').html('<div class="col-md-12">'
                + ' <h4 style="color:black;text-align: left;">Ingrese PIN:</h4>'
                + ' <div class="input-group">'
                + '     <input id="pinSeguridadCierre" type="password" class="form-control">'
                + '     <div class="input-group-addon"><i class="fas fa-unlock-alt"></i></div>'
                + ' </div>'
                + ' <hr />'
                + ' <h4 style="color:black;text-align: left;">Usuario: <button class="btn btn-info"><?php echo $_SESSION['usuario']['nombresUsuario'] . ' ' . $_SESSION['usuario']['apellidosUsuario'] ?></button></h4>'
                + ' <hr />'
                + ' <h4 style="color:black;text-align: left;">Monto final:</h4>'
                + ' <div class="input-group">'
                + '     <input id="montoFinal" type="text" class="form-control" placeholder="Ingrese el monto">'
                + '     <div class="input-group-addon"><i class="fas fa-money-bill-wave"></i></div>'
                + ' </div>'
                + '</div>');
        $('.cargarApertura').remove();
        $('#modalPrevCaja .modal-footer').append('<button type="button" class="btn btn-info pull-right cargarCierre"><i class="far fa-window-close"></i> Cierre de caja</button>');
        $('#modalPrevCaja').modal('toggle');
        return;
    });

    /////////////                                   CARGAR APERTURA DE CAJA                     /////////////////////
    $(document).on('click', '.cargarApertura', function () {
        pageLoadingFrame("show");
        var formData = new FormData(), montoInicial = $('#montoInicial').val(), comentario = $('#comentCaja').val(), pin = $('#pinSeguridad').val();
        setTimeout(function () {
            if (pin == '8520') {
                if (montoInicial == '' || comentario == '') {
                    pageLoadingFrame("hide");
                    $(".customalert_text").html("No puede dejar campos en blanco");
                    $(".customalert").animate({width: 'toggle'}, 600);
                } else {
                    formData.append('meth', 'abrirTurno');
                    formData.append('montoInicial', montoInicial);
                    formData.append('comentario', comentario);
                    $.ajax({
                        url: 'api/api.php',
                        type: 'POST',
                        dataType: "json",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (data) {
                            window.location.reload();
                        },
                        error: function (error) {
                            console.log("Hubo un error de internet, intente de nuevo");
                            console.log(error);
                        }
                    });
                }
            } else {
                pageLoadingFrame("hide");
                $(".customalert_text").html("El pin no coincide");
                $(".customalert").animate({width: 'toggle'}, 600);
            }
        }, 1000);
    });

    /////////////                                   CARGAR CIERRE DE CAJA                     /////////////////////
    $(document).on('click', '.cargarCierre', function () {
        pageLoadingFrame("show");
        var
                formData = new FormData(),
                montoInicial = $('.montoInicialCont').html(),
                montoFinal = $('#montoFinal').val(),
                idTurno = $('.idTurnoCont').html(),
                pin = $('#pinSeguridadCierre').val();
        setTimeout(function () {
            if (pin == '8520') {
                if (montoFinal == '') {
                    pageLoadingFrame("hide");
                    $(".customalert_text").html("No puede dejar los campos en blanco");
                    $(".customalert").animate({width: 'toggle'}, 600);
                } else {
                    if (+montoInicial > +montoFinal) {
                        pageLoadingFrame("hide");
                        $(".customalert_text").html("No se puede cerrar la caja con un monto menor a la apertura");
                        $(".customalert").animate({width: 'toggle'}, 600);
                    } else {
                        formData.append('meth', 'cerrarTurno');
                        formData.append('montoFinal', montoFinal);
                        formData.append('idTurno', idTurno);
                        $.ajax({
                            url: 'api/api.php',
                            type: 'POST',
                            dataType: "json",
                            cache: false,
                            contentType: false,
                            processData: false,
                            data: formData,
                            success: function (data) {
                                window.location.reload();
                            },
                            error: function (error) {
                                console.log("Hubo un error de internet, intente de nuevo");
                                console.log(error);
                            }
                        });
                    }
                }
            } else {
                pageLoadingFrame("hide");
                $(".customalert_text").html("El pin no coincide");
                $(".customalert").animate({width: 'toggle'}, 600);
            }
        }, 1000);
    });
</script>
<?php
if (isset($_GET["verfactura"])) {
    if ($_GET["verfactura"] == "last") {
        $select_pedido = "SELECT * FROM factura ORDER BY idFactura DESC LIMIT 1";
        $result_pedido = mysqli_query($conn, $select_pedido);
        $row_pedido = mysqli_fetch_array($result_pedido);
        echo "
        <script>
            window.location.href = '/?show=caja&verfactura=" . $row_pedido["idFactura"] . "';
        </script>";
        return;
    } else {
        $select_pedido = "SELECT * FROM factura WHERE idFactura = '" . $_GET["verfactura"] . "' LIMIT 1";
        $result_pedido = mysqli_query($conn, $select_pedido);
        $row_pedido = mysqli_fetch_array($result_pedido);
    }
    echo "
        <script>
        $('#modal_consultar_factura .modal-dialog .modal-content .modal-header .modal-title').html('<i class=\"fas fa-edit\"></i> Consultar Factura</h4>');
            $('#modal_consultar_factura .modal-dialog .modal-content .modal-body').html(\"\");
            $('#modal_consultar_factura .modal-dialog .modal-content .modal-body')
                    .append(\"\\n\\
                            <div id='verfactura_datos'>\\n\\
                            </div>\\n\\
                                \");
            var idfactura = '" . $row_pedido["idFactura"] . "';
            consultarfactura(idfactura);
            $('#modal_consultar_factura .modal-dialog .modal-content .modal-body')
                    .append('<table class=\"table consultafacturatabla\" style=\"border:1px solid #d8d8d8;\">\\n\\
                    <tbody class=\"tablaconsultarfactura\">\\n\\
                    </tbody>\\n\\
                </table>');
            var idpedido = '" . $row_pedido["idPedido"] . "';
            consultarpeddo(idpedido);
            ";
    if ($row_pedido["statusFactura"] == "ACTIVE") {
        echo "$('#modal_consultar_factura .modal-dialog .modal-content .modal-body')
                    .append(\"<div class=row'>\\n\\
                        <button onclick='exporttopdftable()' id='imprimir_factura' type='button' class='btn btn-primary btn-lg pull-right' style='margin-top: 16px;margin-right: 16px;'><i class='fa fa-print' aria-hidden='true'></i> Imprimir</button>\\n\\
                        <button id='anular_factura' type='button' class='btn btn-primary btn-lg pull-right' style='margin-top: 16px;margin-right: 16px;'><i class='fa fa-times' aria-hidden='true'></i> Anular Factura</button>\\n\\
                </div>\");
            $('#modal_consultar_factura').modal('toggle');
        </script>
        ";
    } else {
        echo "$('#modal_consultar_factura .modal-dialog .modal-content .modal-body')
                    .append(\"<div class=row'>\\n\\
                        <button id='imprimir_factura' disabled='disabled' type='button' class='btn btn-primary btn-lg pull-right' style='margin-top: 16px;margin-right: 16px;'><i class='fa fa-print' aria-hidden='true'></i> Imprimir</button>\\n\\
                        <button id='reactivar_factura' type='button' class='btn btn-success btn-lg pull-right' style='margin-top: 16px;margin-right: 16px;'><i class='fa fa-check' aria-hidden='true'></i> Reactivar Factura</button>\\n\\
                </div>\");
            $('#modal_consultar_factura').modal('toggle');
        </script>
        ";
    }
}
?>