<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <!-- <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li> -->
    <li>Inicio</li>
    <li>Nuevo Usuario</li>
</ul>
<!-- FIN BREADCRUMB -->
<div class="page-title">                    
    <h2><span class="fa fa-birthday-cake"></span> Bienvenido al sistema</h2>
</div>
<div class="page-content-wrap">
    <div class="col-md-9">
        <div class="panel panel-default">  
            <div class="panel-body panel-body-image">
                <img src="assets/img/logo_rec.png" class="welcomeLogo" alt="Logo">
                <img src="assets/img/welcomebannertall.jpg"  class="welcomeBanner"  alt="Landing Page banner">
            </div>
        </div>
    </div>
    <div class="col-md-3 xn-panel-dragging">
        <div class="widget widget-danger widget-padding-sm">
            <div class="widget-big-int plugin-clock">00:00</div>                            
            <div class="widget-subtitle plugin-date">Cargando...</div>
            <div class="widget-controls">                                
                <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="left" title="Remover"><span class="fa fa-times"></span></a>
            </div>                            
            <div class="widget-buttons widget-c3">
                <div class="col">
                    <a href="#"><span class="fas fa-clock"></span></a>
                </div>
                <div class="col">
                    <a href="#"><span class="fa fa-bell"></span></a>
                </div>
                <div class="col">
                    <a href="#"><span class="fa fa-calendar"></span></a>
                </div>
            </div>                            
        </div>                          
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title-box">
                    <h3>Resumen de mesas</h3>
                    <span>Sucursal principal</span>
                </div>
                <ul class="panel-controls" style="margin-top: 2px;">
                    <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-cog"></span></a>                                        
                        <ul class="dropdown-menu">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span> Collapse</a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span> Remove</a></li>
                        </ul>                                        
                    </li>                                        
                </ul>
            </div>
            <div class="panel-body padding-0">
                <div class="chart-holder" id="dashboard-donut-1" style="height: 200px;"></div>
            </div>
        </div>
    </div>
    <div class="col-md-3 xn-panel-dragging">

        <!-- START WIDGET SLIDER -->
        <div class="widget widget-info widget-carousel">
            <div class="owl-carousel" id="owl-stats">
                <div>                                    
                    <div class="widget-title">Clientes atendidos</div>                                                                        
                    <div class="widget-subtitle">esta semana</div>
                    <div class="widget-int">325</div>
                </div>
                <div>                                    
                    <div class="widget-title">Clientes Nuevos</div>
                    <div class="widget-subtitle">&uacute;ltimos 7 d&iacute;as</div>
                    <div class="widget-int">239</div>
                </div>
                <div>                                    
                    <div class="widget-title">Recurrentes</div>
                    <div class="widget-subtitle">Clientes que visitan de nuevo</div>
                    <div class="widget-int">86</div>
                </div>
            </div>                            
            <div class="widget-controls">                                
                <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
            </div>                             
        </div>         
        <!-- END WIDGET SLIDER -->

    </div>
    <div class="col-md-3 xn-panel-dragging panelVentasBox">                      
        <a href="#" class="tile tile-info tile-valign sidebar-toggle ">$ <span class="clientesFelices">547</span> $
            <div class="informer informer-default dir-tr"><span class="fa fa-align-right"></span></div>
            <div class="informer informer-default dir-bl">Ventas del día</div>
        </a>                                                    
    </div>
</div>