<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<div class="row customalert hidethis">
    <div class="col-md-12">
        <div class="widget widget-primary widget-item-icon">
            <div class="widget-item-left">
                <span class="fa fa-exclamation"></span>
            </div>
            <div class="widget-data">
                <div class="widget-title">Notificación</div>
                <div class="widget-subtitle">
                    <div role="alert" class="customalert_text">
                        Mensaje de error
                    </div>
                </div>
            </div>
            <div class="widget-controls">                                
                <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
            </div>                             
        </div>
    </div>
</div>
<div class="page-container login">
    <div class="overlayLogin hidethis"></div>
    <div class="login-center hidethis loginBox">
        <img src="assets/img/logo_rec.png" />
        <form method="post" id="loginForm">
            <input type="email" name="username" class="email" placeholder="Email" >
            <input type="password" name="password" class="password" placeholder="Contraseña" >
            <button type="submit" ><i class="fas fa-sign-in-alt"></i> Iniciar Sesión </button>
            <div class="error" style="color: red;background: rgba(255, 0, 0, 0.25);"><span>+</span></div>
            <div class="ctaDiv ctaDiv1">¿No tienes cuenta? <a href="#" id="registerBoxBtn"><strong>¡Regístrate ahora!</strong></a></div>
            <div class="ctaDiv ctaDiv2">&copy; 2019 DROOM por <a href="https://burtonservers.com" >Burton Technology.</a></div>
            <div class=" ctaDiv ctaDiv3">
                <a href="https://burtonservers.com" id="termsBox">Términos y condiciones</a> | <a href="https://burtonservers.com" id="contactBox">Contacto</a>
            </div>
        </form>
    </div>
    <div class="login-center hidethis registerBox">
        <img src="assets/img/logo_rec.png" />
        <form method="post" id="registerForm">
            <input type="text" name="names" class="names" placeholder="Nombre completo" >
            <input type="text" name="phone" class="phone" placeholder="N&uacute;mero de tel&eacute;fono" >
            <input type="email" name="email" class="email" placeholder="Correo electr&oacute;nico" >
            <input type="password" name="regpassword" class="regpassword" placeholder="Contraseña" >
            <input type="password" name="repassword" class="repassword" placeholder="Confirmar Contraseña" >
            <div class="error" style="color: red;background: rgba(255, 0, 0, 0.25);"><span>+</span></div>
            <button type="submit" ><i class="fas fa-user-plus"></i> Registrar </button>
            <div class="ctaDiv ctaDiv1">¿Ya eres cliente? <a href="#" id="loginBoxBtn"><strong>¡Inicia sesi&oacute;n!</strong></a></div>
            <div class="ctaDiv ctaDiv2">&copy; 2019 DROOM por <a href="https://burtonservers.com" >Burton Technology.</a></div>
            <div class="ctaDiv ctaDiv3">
                <a href="https://burtonservers.com" id="termsBox">Términos y condiciones</a> | <a href="https://burtonservers.com" id="contactBox">Contacto</a>
            </div>
        </form>
    </div>
</div> 