<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<script>
    //       ACTIVAMOS EL MENU LATERAL       //
    $(".menuItem").removeClass("active");
    $(".inventario").addClass("active");

    //////////////////////////////////////////////////ACTUALIZAMOS EL LISTADO DE INGREDIENTES
    $(document).ready(function () {
        getIngredientes();
        var formData = new FormData();
        formData.append('meth', 'getMenuFullTable');
        $.ajax({
            url: 'api/api.php',
            type: 'POST',
            data: formData,
            dataType: "json",
            success: function (data) {
                $(data.men).each(function (index, element) {
                    $('#tiposelect_edit').append("<option value='"+element.idMenu+"'>"+element.nombreMenu+"</option>")
                    $('#tiposelect_new').append("<option value='"+element.idMenu+"'>"+element.nombreMenu+"</option>")
                });
                $('select').selectpicker('refresh');
            },
            error: function (error) {
                console.log(error);
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });

    //////////////////////////////// CUANDO PRESIONAMOS CLIC EN EL BOTON DE AGREGAR NUEVO INGREDIENTE
    $(document).on('click', '.addnew_ing_btn', function (e) {
        e.preventDefault();
        var self;
        self = this;
        $.when($(".ingredientes_lista,.editing_panel,historico_lista").slideUp("slow")).then(function () {
            $(".agregarnuevo_panel").slideDown("slow");
        });
    });

    //////////////////////////////// ACCION AL HACER CLIC EN GUARDAR NEUVO INGREDIENTE
    $(document).on('click', '.savenew_btn', function (e) {
        e.preventDefault();
        var self = this, formData = new FormData(), est;
        pageLoadingFrame("show");
        setTimeout(function () {
            if (
                    $('#guardarIngrediente').valid() &&
                    $('#tiposelect_new').val() != '0'
                    )
            {
                est = $('#estselect_new').val();
                formData.append('meth', 'addnewing');
                formData.append('nombreIngrediente', $('#nombre_new').val());
                formData.append('cantidad', $('#cantidad_new').val());
                formData.append('codigoIngrediente', $('#codigo_new').val());
                formData.append('barcodeIngrediente', $('#barcode_new').val());
                formData.append('tipoIngrediente', $('#tiposelect_new option:selected').val());
                formData.append('ccIngrediente', $('#cuneta_new').val());
                formData.append('detalleIngrediente', $('#detalle_new').val());
                formData.append('bodegaIngrediente', $('#bodega_new').val());
                formData.append('minIngrediente', $('#minimo_new').val());
                formData.append('precioIngrediente', $('#precioventa_new').val());
                formData.append('compraIngrediente', $('#preciocompra_new').val());
                if ($("#estado_checkbox").prop('checked') == true) {
                    formData.append('estadoIngrediente', '1');
                } else {
                    formData.append('estadoIngrediente', '0');
                }
                $.ajax({
                    url: 'api/api.php',
                    type: 'POST',
                    data: formData,
                    dataType: "json",
                    success: function (data) {
                        if (data.status == 'ok') {
                            pageLoadingFrame("hide");
                            $('.succesmessage_mb').html(data.msg);
                            $('#message-box-success').toggle();
                            $('input[type="text"] , select').val('');
                            console.log(data);
                            $.when(
                                    $(".agregarnuevo_panel,.editing_panel").slideUp("slow"),
                                    getIngredientes()
                                    ).then(function () {
                                $(".ingredientes_lista").slideDown("slow");
                            });
                        }
                        if (data.status == 'error') {
                            pageLoadingFrame("hide");
                            $('.errormessage_mb').html(data.msg);
                            $('#message-box-danger').toggle();
                            console.log(data);
                        }
                    },
                    error: function (error) {
                        pageLoadingFrame("hide");
                        $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                        $('#message-box-danger').toggle();
                        console.log(error);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            } else {
                pageLoadingFrame("hide");
                $('.errormessage_mb').html('Debe ingresar la informaci&oacute;n en todos los campos');
                $('#message-box-danger').toggle();
            }
        }, 1000);
    });

    //////////////////////////////// ACCION AL HACER CLIC EN ACTUALIZAR INGREDIENTE
    $(document).on('click', '.saveedit_btn', function (e) {
        e.preventDefault();
        var self = this, formData = new FormData(), est;
        pageLoadingFrame("show");
        setTimeout(function () {
            if (
                    $('#editarIngrediente').valid() &&
                    $('#unidadselect_edit,#tiposelect_edit,#estselect_edit').val() != '0'
                    )
            {
                formData.append('editIng', 'true');
                formData.append('idIngredient', $('#idIngredientEdit').val());
                formData.append('nombreIngrediente', $('#nombre_edit').val());
                formData.append('cantidad', $('#cantidad_edit').val());
                formData.append('codigoIngrediente', $('#codigo_edit').val());
                formData.append('barcodeIngrediente', $('#barcode_edit').val());
                formData.append('tipoIngrediente', $('#tiposelect_edit option:selected').val());
                formData.append('detalleIngrediente', $('#detalle_edit').val());
                formData.append('bodegaIngrediente', $('#bodega_edit').val());
                formData.append('minIngrediente', $('#minimo_edit').val());
                formData.append('precioIngrediente', $('#precioventa_edit').val());
                formData.append('compraIngrediente', $('#preciocompra_edit').val());
                if ($("#estado_checkbox_edit").prop('checked') == true) {
                    formData.append('estadoIngrediente', '1');
                } else {
                    formData.append('estadoIngrediente', '0');
                }
                $.ajax({
                    url: 'assets/inventory/control.php',
                    type: 'POST',
                    data: formData,
                    dataType: "json",
                    success: function (data) {
                        if (data.status == 'ok') {
                            pageLoadingFrame("hide");
                            $('.succesmessage_mb').html(data.msg);
                            $('#message-box-success').toggle();
                            $('input[type="text"] , select').val('');
                            console.log(data);
                            $.when(
                                    $(".agregarnuevo_panel,.editing_panel").slideUp("slow"),
                                    getIngredientes()
                                    ).then(function () {
                                $(".ingredientes_lista").slideDown("slow");
                            });
                        }
                        if (data.status == 'error') {
                            pageLoadingFrame("hide");
                            $('.errormessage_mb').html(data.msg);
                            $('#message-box-danger').toggle();
                            console.log(data);
                        }
                    },
                    error: function (error) {
                        pageLoadingFrame("hide");
                        $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                        $('#message-box-danger').toggle();
                        console.log(error);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            } else {
                pageLoadingFrame("hide");
                $('.errormessage_mb').html('Debe ingresar la informaci&oacute;n en todos los campos');
                $('#message-box-danger').toggle();
            }
        }, 1000);
    });

    //////////////////////////////// ACCION AL HACER CLIC EN ELIMINAR INGREDIENTE
    $(document).on('click', '.deleteitem_btn', function (e) {
        e.preventDefault();
        var self = this, ajaxData = new FormData(), est;
        pageLoadingFrame("show");
        setTimeout(function () {
            if ($("#estado_input_edit").val() == 1) {
                pageLoadingFrame("hide");
                $('.errormessage_mb').html('El ingrediente debe ser desactivado antes de poder ser eliminado');
                $('#message-box-danger').toggle();
            } else {
                ajaxData.append('deleteIng', 'true');
                ajaxData.append('deleteid', $('#codigo_edit').val());
                $.ajax({
                    url: 'assets/inventory/control.php',
                    type: 'POST',
                    data: ajaxData,
                    success: function (data) {
                        pageLoadingFrame("hide");
                        $('.succesmessage_mb').html(data);
                        $('#message-box-success').toggle();
                        $.when(
                                $(".agregarnuevo_panel,.editing_panel").slideUp("slow"),
                                getIngredientes()
                                ).then(function () {
                            $(".ingredientes_lista").slideDown("slow");
                        });
                    },
                    error: function (error) {
                        pageLoadingFrame("hide");
                        $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                        $('#message-box-danger').toggle();
                        console.log(error);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            }
        }, 1000);
    });

    //////////////////////////////////// CUANDO QUEREMOS REGRESAR A VER LA LISTA DE INGREDIENTES
    $(document).on('click', '.goback_ing_btn', function (e) {
        e.preventDefault();
        var self;
        self = this;
        $.when(
                $(".agregarnuevo_panel,.editing_panel,.historico_lista").slideUp("slow"),
                getIngredientes()
                ).then(function () {
            $(".ingredientes_lista").slideDown("slow");
        });
    });

    //////////////////////////////////// CANCELAR EDITAR INVENTARIO
    $(document).on('click', '.cancel_btn_newreg', function (e) {
        e.preventDefault();
        location.reload();
    });

    //////////////////////////////////// Nuevo Registro de edicion de inventario
    $(document).on('click', '.btn_newreg', function (e) {
        e.preventDefault();
        pageLoadingFrame("show");
        var self = this, addlist = {}, remlist = {}, formData = new FormData(), est = $("#selected_dinner").val();
        $(".cant_input_plus:visible").each(function (index, element) {
            addlist[index] = {};
            addlist[index]['codigo'] = $(element).parent().parent().find(".ing_codigo").html();
            addlist[index]['cantidad'] = $(element).find(".cant_input_plus_val").val();
            addlist[index]['nombre'] = $(element).parent().parent().find(".ing_nombreproducto").html();
        });
        $(".cant_input_minus:visible").each(function (index, element) {
            remlist[index] = {};
            remlist[index]['codigo'] = $(element).parent().parent().find(".ing_codigo").html();
            remlist[index]['cantidad'] = $(element).find(".cant_input_minus_val").val();
            remlist[index]['nombre'] = $(element).parent().parent().find(".ing_nombreproducto").html();
        });
        setTimeout(function () {
            formData.append('editInventory', 'true');
            formData.append('plusamounts', JSON.stringify(addlist));
            formData.append('lessamounts', JSON.stringify(remlist));
            formData.append('location', est);
            $.ajax({
                url: 'assets/inventory/control.php',
                type: 'POST',
                data: formData,
                dataType: "json",
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    if (data.status == 'ok') {
                        location.reload();
                        console.log(data);
                    }
                    if (data.status == 'error') {
                        pageLoadingFrame("hide");
                        $('.errormessage_mb').html(data.msg);
                        $('#message-box-danger').toggle();
                        console.log(data);
                    }
                },
                error: function (error) {
                    pageLoadingFrame("hide");
                    $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                    $('#message-box-danger').toggle();
                    console.log(error);
                }
            });
        }, 1000);
    });

    //////////////////////////////////// DESHABILITAMOS EL SELECT DE EDITAR ESTABLECIMIENTO
    $(document).on('click', '.ing_quickedit_plus', function (e) {
        e.preventDefault();
        var self = this;
        $.when(
                $(self).parent().find('button').fadeOut()
                ).then(function () {
            $(self).parent().find(".cant_input_plus").fadeIn();
        });
        $(".quickreg_drawer").animate({width: 'show'}, 600);
    });

    $(document).on('click', '.ing_quickedit_minus', function (e) {
        e.preventDefault();
        var self = this;
        $.when(
                $(self).parent().find('button').fadeOut()
                ).then(function () {
            $(self).parent().find(".cant_input_minus").fadeIn();
        });
        $(".quickreg_drawer").animate({width: 'show'}, 600);
    });

    ///////////////////////////////////////////////////////////////////// CUANDO HACES CLIC EN UNA COLUMNA PARA EDITAR EL INGREDIENTE
    $(document).on('click', '.singleing_row', function (e) {
        e.preventDefault();
        var self = this,
                idIngred = $(self).parent().find(".ing_id").val(),
                nombre = $(self).parent().find(".ing_nombreproducto").html(),
                cantidad = $(self).parent().find(".ing_cantidad").val(),
                codigo = $(self).parent().find(".ing_codigo").html(),
                codebar = $(self).parent().find(".ing_barcode").val(),
                tipo = $(self).parent().find(".ing_tipo").html(),
                detalle = $(self).parent().find(".ing_detalle").val(),
                bodega = $(self).parent().find(".ing_bodega").val(),
                min = $(self).parent().find(".ing_min").val(),
                venta = $(self).parent().find(".ing_precio").html(),
                compra = $(self).parent().find(".ing_compra").val(),
                estado = $(self).parent().find(".ing_status").val();

        $.when($(".agregarnuevo_panel,.ingredientes_lista").slideUp("slow")).then(function () {

            $('.editing_panel .panel .panel-heading h3').text(' Editar ingrediente: ' + nombre);
            $("#idIngredientEdit").val(idIngred);
            $("#nombre_edit").val(nombre);
            $("#cantidad_edit").val(cantidad);
            $("#codigo_edit").val(codigo);
            $("#barcode_edit").val(codebar);
            $("#tiposelect_edit").val(tipo);
            $("#detalle_edit").val(detalle);
            $("#bodega_edit").val(bodega);
            $("#minimo_edit").val(min);
            $("#precioventa_edit").val(venta);
            $("#preciocompra_edit").val(compra);
            if (estado == 1) {
                $('#estado_checkbox_edit').attr("checked", "checked");
                $('#estado_input_edit').val("1");
            } else {
                $('#estado_checkbox_edit').removeAttr("checked");
                $('#estado_input_edit').val("0");
            }

            var formData = new FormData();
            formData.append('meth', 'getRelsProd');
            formData.append('idIng', idIngred);
            $.ajax({
                url: 'api/api.php',
                type: 'POST',
                data: formData,
                dataType: "json",
                success: function (data) {
                    if (data.status == 'yes') {
                        $('.relListcont').html(data.html);
                        console.log('success');
                    }
                    if (data.status == 'error') {
                        $('.errormessage_mb').html('Error, check console');
                        $('#message-box-danger').toggle();
                        console.log(data);
                    }
                },
                error: function (error) {
                    pageLoadingFrame("hide");
                    $('.errormessage_mb').html('Error de red, revise su conexi&oacute;n');
                    $('#message-box-danger').toggle();
                    console.log(error);
                },
                cache: false,
                contentType: false,
                processData: false
            });

            $(".editing_panel").slideDown("slow");

        });
    });

    //////////////////////////////                      ACTUALIZAMOS UNA RELACION DE PRODUCTO CON EL INGREDIENTE
    $(document).on("click", ".editThisRel", function (event) {
        event.preventDefault();
        var
                self = this,
                idProducto = $(self).parent().find('.idProdRel').html(),
                idIngrediente = $(self).parent().find('.idIngRel').html(),
                relNewVal = $(self).parent().find(".relNewValInput").val();

        pageLoadingFrame("show");
        setTimeout(function () {
            if (relNewVal == '') {
                pageLoadingFrame("hide");
                $('.errormessage_mb').html("Debes ingresar un valor");
                $('#message-box-danger').toggle();
                console.log('empty');
                return;
            }
            var formData = new FormData();
            formData.append('meth', 'updateRel');
            formData.append('idProducto', idProducto);
            formData.append('idIngrediente', idIngrediente);
            formData.append('relNewVal', relNewVal);
            $.ajax({url: 'api/api.php', type: 'POST', dataType: "json", cache: false, contentType: false, processData: false, data: formData,
                success: function (data) {
                    setTimeout(function () {
                        $.when(
                                $(".agregarnuevo_panel,.editing_panel,.historico_lista").slideUp("slow")
                                ).then(function () {
                            $(".ingredientes_lista").slideDown("slow");
                            pageLoadingFrame("hide");
                        });
                    }, 1000);
                },
                error: function (error) {
                    pageLoadingFrame("hide");
                    console.log("Hubo un error de internet, intente de nuevo");
                    console.log(error);
                }
            });
        }, 1000);
    });


    //////////////////////////////// MOSTRAR LISTADO DE TRANSACCIONES
    $(document).on('click', '.listadohistorico_btn', function (e) {
        e.preventDefault();
        var self;
        self = this;
        $.when($(".ingredientes_lista,.editing_panel,.historico_lista").slideUp("slow")).then(function () {
            getHistorico();
            $(".historico_lista").slideDown("slow");
        });
    });

    function getIngredientes() {
        $.post('assets/inventory/control.php', {getList: 'true'}, function (data) {
            $('.listadeingredientes').html(data);
        });
    }

    function getHistorico() {
        $.post('assets/inventory/control.php', {getTrans: 'true', location: $("#selected_dinner").val()}, function (data) {
            $('.listahistorico').html(data);
        });
    }
</script>