<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li>Cocina </li>
</ul>
<!-- FIN BREADCRUMB -->

<!-- FIN BREADCRUMB -->
<div class="col-md-12 contenedorCocina" style="padding-top: 30px;display: flex;flex-wrap: wrap;">

</div>

<div class="tile tile-primary estadoP" style="background:white;font-size: 24px;width:751px;position: fixed;bottom: 5px;right: 5px;z-index: 1050;border: 5px solid rgb(136, 138, 134);" hidden>
    <div class="tituloP" style="text-align: center;color:black;">
    </div>

    <div class="btn-group" data-toggle="buttons">
        <label id="radioEstado" class="btn btn-info" style="font-size:20px;font-weight: bold;border: 1px solid #656C78;color:white;background:#ed4444;box-shadow:0px 6px 5px 0px #888888;">
            <input type="radio" name="options" id="rdEstado1" value="1" autocomplete="off">SOLICITADO
        </label>
        <label id="radioEstado" class="btn btn-warning" style="font-size:20px;font-weight: bold;border: 1px solid #656C78;color:#656C78;">
            <input type="radio" name="options" id="rdEstado2" value="2" autocomplete="off">EN PROCESO
        </label>
        <label id="radioEstado" class="btn btn-success" style="font-size:20px;font-weight: bold;border: 1px solid #656C78;color:#656C78;">
            <input type="radio" name="options" id="rdEstado3" value="3" autocomplete="off">LISTO PARA ENTREGAR
        </label>
        <label id="radioEstado" class="btn btn-default" style="font-size:20px;font-weight: bold;color:#656C78;border: 1px solid #656C78;">
            <input type="radio" name="options" id="rdEstado4" value="4" autocomplete="off">ENTREGADO
        </label>
    </div>
</div>


