<?php
/*
 *          ***********************************************************
 *          *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *          @date               2019-03-22
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2015-2019 Burton Tech
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/?show=home"><?php echo $_SESSION["usuario"]['nombreEstablecimiento']; ?></a></li>
    <li>Configuracion del Usuario </li>
</ul>
<!-- FIN BREADCRUMB -->
<div class="page-title">                    
    <h2><span class="fa fa-cog"></span> Editar configuración de la cuenta</h2>
</div>
<div class="page-content-wrap">  
    <div class="row customalert hidethis">
        <div class="col-md-12">
            <div class="widget widget-primary widget-item-icon">
                <div class="widget-item-left">
                    <span class="fa fa-exclamation"></span>
                </div>
                <div class="widget-data">
                    <div class="widget-title">Notificación</div>
                    <div class="widget-subtitle">
                        <div role="alert" class="customalert_text">
                            Mensaje de error
                        </div>
                    </div>
                </div>
                <div class="widget-controls">                                
                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                </div>                             
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">                                
            <div class="panel-body">
                <h3><span class="fa fa-user"></span> <?php echo $_SESSION["usuario"]["nombresUsuario"] . " " . $_SESSION["usuario"]["apellidosUsuario"]; ?></h3>
                <p><span class="fa fa-industry"></span> <?php echo $_SESSION["usuario"]["idPerfil"]; ?></p>
                <div class="text-center fotoPerfil">
                    <img src="<?php echo $_SESSION["usuario"]['userImg']; ?>" class="img-thumbnail">
                </div>                                    
            </div>
            <div class="panel-body form-group-separated">
                <div class="form-group">                                        
                    <div class="col-md-12 col-xs-12">
                        <a href="#" class="btn btn-info btn-block btn-rounded" data-toggle="modal" data-target="#modal_change_photo">Cambiar Foto</a>
                    </div>
                </div>
                <div class="form-group">                                        
                    <div class="col-md-12 col-xs-12">
                        <a href="#" class="btn btn-danger btn-block btn-rounded" data-toggle="modal" data-target="#modal_change_password">Cambiar contraseña</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4 editarImagenLogo">
        <div class="panel panel-default">     
            <div class="panel-heading">
                <h3>
                    <span class="fa fa-picture-o"></span> 
                    Cambiar Logo de la App
                    <span data-toggle="tooltip" data-placement="top" title="800px * 450px" class=" fa fa-exclamation-circle"></span>
                    <ul class="panel-controls">
                        <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                    </ul>   
                </h3> 
            </div>                       
            <div class="panel-body panel-body-image">
                <img src="assets/img/logo_rec.png" alt="Logo"/>
                <a href="#" class="panel-body-inform">
                    <i class="fas fa-image" style="transform: rotate(-45deg);"></i>
                </a>
            </div>
            <div class="panel-body">                                   
                <input  class="fileinput btn-info" type="file" name="updateNewLogo" id="updateNewLogo" data-filename-placement="inside" title="Buscar Imagen">
                <hr />
                <button class="pull-right btn btn-success" name="updateNewLogoBtn"  type="submit"  id="updateNewLogoBtn" data-toggle="tooltip" data-placement="right" title="Imagen del producto">
                    <span class="beforeLoad" ><span class="fa fa-upload"></span> Cambiar imagen </span>
                    <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                </button>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-4 editarImagenSlide1">
            <div class="panel panel-default">     
                <div class="panel-heading">
                    <h3>
                        <span class="fa fa-picture-o"></span> 
                        Cambiar Primer Slide
                        <span data-toggle="tooltip" data-placement="top" title="1920px * 1080px" class=" fa fa-exclamation-circle"></span>
                        <ul class="panel-controls">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                        </ul>   
                    </h3> 
                </div>                       
                <div class="panel-body panel-body-image">
                    <img src="assets/img/backgrounds/1.jpg" alt="Logo"/>
                    <a href="#" class="panel-body-inform">
                        <i class="fas fa-image" style="transform: rotate(-45deg);"></i>
                    </a>
                </div>
                <div class="panel-body">                                   
                    <input  class="fileinput btn-info" type="file" name="updateSlide1" id="updateSlide1" data-filename-placement="inside" title="Buscar Imagen">
                    <hr />
                    <button class="pull-right btn btn-success" name="updateSlide1Btn"  type="submit"  id="updateSlide1Btn" data-toggle="tooltip" data-placement="right" title="Imagen del producto">
                        <span class="beforeLoad" ><span class="fa fa-upload"></span> Cambiar imagen </span>
                        <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4 editarImagenSlide2">
            <div class="panel panel-default">     
                <div class="panel-heading">
                    <h3>
                        <span class="fa fa-picture-o"></span> 
                        Cambiar Segundo Slide
                        <span data-toggle="tooltip" data-placement="top" title="1920px * 1080px" class=" fa fa-exclamation-circle"></span>
                        <ul class="panel-controls">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                        </ul>   
                    </h3> 
                </div>                       
                <div class="panel-body panel-body-image">
                    <img src="assets/img/backgrounds/2.jpg" alt="Logo"/>
                    <a href="#" class="panel-body-inform">
                        <i class="fas fa-image" style="transform: rotate(-45deg);"></i>
                    </a>
                </div>
                <div class="panel-body">                                   
                    <input  class="fileinput btn-info" type="file" name="updateSlide2" id="updateSlide2" data-filename-placement="inside" title="Buscar Imagen">
                    <hr />
                    <button class="pull-right btn btn-success" name="updateSlide2Btn"  type="submit"  id="updateSlide2Btn" data-toggle="tooltip" data-placement="right" title="Imagen del producto">
                        <span class="beforeLoad" ><span class="fa fa-upload"></span> Cambiar imagen </span>
                        <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4 editarImagenSlide3">
            <div class="panel panel-default">     
                <div class="panel-heading">
                    <h3>
                        <span class="fa fa-picture-o"></span> 
                        Cambiar Tercer Slide
                        <span data-toggle="tooltip" data-placement="top" title="1920px * 1080px" class=" fa fa-exclamation-circle"></span>
                        <ul class="panel-controls">
                            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                        </ul>   
                    </h3> 
                </div>                       
                <div class="panel-body panel-body-image">
                    <img src="assets/img/backgrounds/3.jpg" alt="Logo"/>
                    <a href="#" class="panel-body-inform">
                        <i class="fas fa-image" style="transform: rotate(-45deg);"></i>
                    </a>
                </div>
                <div class="panel-body">                                   
                    <input  class="fileinput btn-info" type="file" name="updateSlide3" id="updateSlide3" data-filename-placement="inside" title="Buscar Imagen">
                    <hr />
                    <button class="pull-right btn btn-success" name="updateSlide3Btn"  type="submit"  id="updateSlide3Btn" data-toggle="tooltip" data-placement="right" title="Imagen del producto">
                        <span class="beforeLoad" ><span class="fa fa-upload"></span> Cambiar imagen </span>
                        <img class="loading_img" src="assets/img/loadingbar.gif" width="80" style="display: none;" />
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modal_change_photo" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title tituloModalPreferencias" style="color:white;"><center><i class="fa fa-file-image-o" aria-hidden="true"></i> Cambiar foto de perfil</center></h4>
            </div>
            <div class="modal-body">

                <form id="formImagen" name="formImagen">
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-1">
                            <input type="file" class="filestyle" data-placeholder="Ninguna imagen establecida." data-text="Seleccionar imagen.." data-btnClass="btn-primary" accept="image/*" name="fileImagen" id="fileImagen" required>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle" aria-hidden="true"></i> Cerrar</button>
                <button type="button" class="btn btn-primary btnSubeImagen" style="border: 1px solid;"><i class="fa fa-upload" aria-hidden="true"></i> Cambiar foto de perfil</button>
            </div>
        </div>

    </div>
</div>
<div id="confirmacionCambioFoto" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title tituloModalPreferencias" style="color:white;"><center><i class="fa fa-file-image-o" aria-hidden="true"></i> Confirmación de cambio de foto</center></h4>
            </div>
            <div class="modal-body">
                <div class="col-md-12">
                    <div class="col-md-12">
                        <center><h4>Esta seguro/a de cambiar esta foto de perfil</h4></center>
                        <div class="profile avatar" style="background:white;">
                            <div class="profile-image fotoAntigua">
                                <img src="<?php echo $_SESSION["usuario"]['userImg']; ?>" alt="Imagen anterior" class="mCS_img_loaded" >
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <center><h4>Por esta foto ?</h4></center>
                        <div class="profile avatar" style="background:white;">
                            <div class="profile-image">
                                <img class="nuevaImagen" src="" alt="Nueva imagen" class="mCS_img_loaded" >
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle" aria-hidden="true"></i> Cerrar</button>
                <button type="button" class="btn btn-primary btnConfirmaImagen" style="border: 1px solid;"><i class="fa fa-check" aria-hidden="true"></i> Sí</button>
            </div>
        </div>

    </div>
</div>
<div class="modal animated fadeIn" id="modal_change_password" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="passupdate"  method="post" enctype="multipart/form-data">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="smallModalHead">Cambiar contraseña</h4>
                </div>
                <div class="modal-body">
                    <p>Por favor introduzca los datos en los formularios a continuación para realizar el cambio de su contraseña</p>
                </div>
                <div class="modal-body form-horizontal form-group-separated">                        
                    <div class="form-group">
                        <label class="col-md-3 control-label">Contraseña anterior</label>
                        <div class="col-md-9">
                            <input name="oldpass" id="oldpass" type="password" class="form-control"/>
                            <span class="help-block">ingrese su contraseña actual</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Nueva contraseña</label>
                        <div class="col-md-9">
                            <input name="newpass" id="newpass" type="password" class="form-control"/>
                            <span class="help-block">ingrese una contraseña entre 8 a 16</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Repetir contraseña</label>
                        <div class="col-md-9">
                            <input name="reppass" id="reppass" type="password" class="form-control"/>
                            <span class="help-block">repita la contraseña anterior</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Salir</button>
                    <button name="meth" id="meth" class="btn btn-success" value="submitnewpass"><span class="fa fa-save"></span> Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div> 
<div id="modal_change_establecimiento" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header label-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title tituloModalPreferencias" style="color:white;"><center><i class="fa fa-home" aria-hidden="true"></i> Cambiar establecimiento</center></h4>
            </div>
            <div class="modal-body">
                <div class="col-md-8 col-md-offset-2">
                    <div class="btn-group-vertical radioEstablecimiento" data-toggle="buttons" style="width: 100%;">
                        <label class="btn btn-primary active">
                            <input type="radio" name="options" id="option1" autocomplete="off" value="" checked><br><h3 style="color:white;">Seleccione un establecimiento ..</h3><br>
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="options" id="option2" autocomplete="off" value="avmaestro"><img src="img/establecimientos/sucursal-norte-dirulo.png" alt="Imagen anterior" class="mCS_img_loaded" width="100" height="100"> <h3 style="color:white;">Dirulo Av. del Maestro</h3>
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="options" id="option3" autocomplete="off" value="quitosur"><img src="img/establecimientos/sucursal-sur-dirulo.png" alt="Imagen anterior" class="mCS_img_loaded" width="100" height="100"> <h3 style="color:white;">Dirulo Quito Sur</h3>
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="options" id="option4" autocomplete="off" value="villaflora"><img src="img/establecimientos/sucursal-villaflora-dirulo.png" alt="Imagen anterior" class="mCS_img_loaded" width="100" height="100"> <h3 style="color:white;">Dirulo Villaflora</h3>
                        </label>
                        <!--
                        <label class="btn btn-primary">
                            <input type="radio" name="options" id="option5" autocomplete="off" value="todos" ><img src="img/logo_rec.png" alt="Imagen anterior" class="mCS_img_loaded" width="200" style="padding: 10px 0px;"><h3 style="color:white;">Todos los establecimientos</h3>
                        </label>-->
                    </div>
                </div>

            </div>
            <div class="modal-footer label-primary">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle" aria-hidden="true"></i> Cerrar</button>
                <button type="button" class="btn btn-primary btnEstableceEstablecimiento" style="border: 1px solid;"><i class="fas fa-sync-alt" aria-hidden="true"></i> Cambiar establecimiento</button>
            </div>
        </div>

    </div>
</div>