<?php
/*        
 *          ***********************************************************
 * 	        *******************||  DROOM SOFTWARE   ||*****************
 *          ***********************************************************
 * 
 *	        @date           2019-03-22
 *          @author         Bayman Burton <bayman@burtonservers.com>
 *          @copyright      2015-2019 Burton Tech
 *          @license        https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *	        Integrated Restaurant Management Software.
 *          Focused on handling the full operation of the restaurant, including support for multi
 *          restaurants, kitchen control, teller management and Waiter module for wireless order submitting
 *          also comes with an Admin Dashboard and custom reports.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */


/****** PURIFICAMOS VARIABLES *******/
function broom($type, $string) {
    if ($type == "reg") { /* FILTRAR a - Z Y ESPACIOS */
        return preg_replace("/[^ \w]+/", "", $string);
    }
    if ($type == "text") { /* FILTRAR SOLO TEXTO PARA LECTURA SIN CARCTERES ESPECIALES */
        return preg_replace('#[^\p{L}\s-]#u', '', $string);
    }
    if ($type == "num") { /* FILTRAR TODO MENOS NUMEROS */
        return preg_replace('/\D/', '', $string);
    }
    if ($type == "spa") { /* CONVERTIR A ESPAñL */
        return preg_replace('#[^\p{L}\s-]#u', '', $string);
    }
    if ($type == "url") { /* TEXTO PARA URL */
        return str_replace('+', '_', urlencode(preg_replace("/[^ \w]+/", "", $string)));
    }
    if ($type == "syntec") { /* PARA NOMBRES TECNOMEGA*/     
        return preg_replace('/^[a-zA-Z\d]+$/', ' ', preg_replace('(&#8221;)', ' ', $string));
    }
}

function newNotif($user, $title, $msg, $class)
{
    $insert = "INSERT INTO notify  (`userNotif`,`titleNotif`,`msgNotif`,`dateNotif`,`statusNotif`,`classNotif`)  
            VALUES ('" . $user . "', '" . $title . "', '" . $msg . "', '" . date('Y-m-d H:i:s') . "', 'new', '" . $class . "')";
    $result = $dblink->query($insert) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $insert . "'}");
}
?>